// Code generated by tools/runtime-bundle/import.py; DO NOT EDIT.
// The GPL grammar payload is distributed only in this optional module.
package gtsadapter

import (
	"embed"
	gotreesitter "github.com/wotjr1649/go-treesitter/internal/runtime"
	"github.com/wotjr1649/go-treesitter/internal/runtime/grammars"
	grammarruntime "github.com/wotjr1649/go-treesitter/internal/runtime/grammars/runtime"
)

//go:embed grammar_blobs/*.bin
var blobs embed.FS

var RegisterExternalLexStates = grammars.RegisterExternalLexStates

func loader(name string) func() *gotreesitter.Language {
	return func() *gotreesitter.Language { return grammarruntime.Language(name) }
}

func init() {
	for _, name := range []string{"caddy", "disassembly", "jq"} {
		data, err := blobs.ReadFile("grammar_blobs/" + name + ".bin")
		if err != nil {
			panic(err)
		}
		grammarruntime.RegisterBlob(name, func() []byte { return data })
	}
	grammars.RegisterExternalScanner("caddy", CaddyExternalScanner{})
	grammars.RegisterExternalScanner("disassembly", DisassemblyExternalScanner{})
	grammars.Register(grammars.LangEntry{
		Name:           "caddy",
		Language:       loader("caddy"),
		GrammarSource:  grammars.GrammarSourceTS2GoBlob,
		HighlightQuery: "(comment) @comment @spell\n\n[ \n  (env)\n  (argv)\n  (block_variable)\n  (placeholder)\n] @constant\n\n(value) @variable\n(directive (keyword) @attribute)\n(global_options (option (keyword) @attribute))\n\n(keyword) @keyword\n\n(boolean) @boolean\n\n(placeholder\n  [\n    \"{\"\n    \"}\"\n  ] @punctuation.special)\n\n\n[\n  (auto)\n] @variable.builtin\n\n[\n  (string_literal)\n  (quoted_string_literal)\n  (address)\n] @string\n\n[ \n  (matcher) \n  (route)\n  (snippet_name)\n] @string.special\n\n[\n  (numeric_literal)\n  (time)\n  (size)\n  (ip_literal)\n] @number\n\n[\n  \"{\"\n  \"}\"\n] @punctuation.bracket\n\n",
	})
	grammars.Register(grammars.LangEntry{
		Name:           "disassembly",
		Extensions:     []string{".dis", ".dump"},
		Language:       loader("disassembly"),
		GrammarSource:  grammars.GrammarSourceTS2GoBlob,
		HighlightQuery: "(byte) @constant\n\n[\n  (address)\n  (hexadecimal)\n  (integer)\n] @number\n\n(identifier) @variable\n\n(bad_instruction) @text.warning\n(code_location (identifier) @function.call)\n(comment) @comment\n(instruction) @function\n(memory_dump) @string\n\n[\"<\" \">\"] @punctuation.special\n[\"+\" \":\"] @punctuation.delimiter\n",
	})
	grammars.Register(grammars.LangEntry{
		Name:           "jq",
		Extensions:     []string{".jq"},
		Language:       loader("jq"),
		GrammarSource:  grammars.GrammarSourceTS2GoBlob,
		HighlightQuery: "[\n \"and\"\n \"as\"\n \"break\"\n \"catch\"\n \"def\"\n \"elif\"\n \"else\"\n \"end\"\n \"foreach\"\n \"if\"\n \"import\"\n \"include\"\n \"label\"\n \"module\"\n \"or\"\n \"reduce\"\n \"then\"\n \"try\"\n ] @keyword\n",
	})
}
