// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/ColinKennedy/tree-sitter-disassembly 0229c0211dba909c5d45129ac784a3f4d49c243a src/parser.c

package gtsadapter

// disassemblyExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var disassemblyExternalLexStates = [][]bool{
	/* 0 */ {false, false, false, false},
	/* 1 */ {true, true, true, true},
	/* 2 */ {false, true, false, false},
	/* 3 */ {false, true, true, false},
	/* 4 */ {true, false, false, false},
}

func init() {
	RegisterExternalLexStates("disassembly", disassemblyExternalLexStates)
}
