//go:build !grammar_subset || grammar_subset_agda

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.

package grammars

import (
	grammarruntime "github.com/wotjr1649/go-treesitter/internal/runtime/grammars/runtime"
)

type AgdaExternalScanner = grammarruntime.AgdaExternalScanner
