// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.

package grammars

import (
	gotreesitter "github.com/wotjr1649/go-treesitter/internal/runtime"
	grammarruntime "github.com/wotjr1649/go-treesitter/internal/runtime/grammars/runtime"
	time "time"
)

func RegisterExternalScanner(name string, s gotreesitter.ExternalScanner) {
	grammarruntime.RegisterExternalScanner(name, s)
}
func RegisterExternalLexStates(name string, states [][]bool) {
	grammarruntime.RegisterExternalLexStates(name, states)
}

type ReservedWordTable = grammarruntime.ReservedWordTable

func RegisterReservedWords(name string, table ReservedWordTable) {
	grammarruntime.RegisterReservedWords(name, table)
}
func LookupReservedWords(name string) (ReservedWordTable, bool) {
	return grammarruntime.LookupReservedWords(name)
}
func LoadLanguage(name string, data []byte) (*gotreesitter.Language, error) {
	return grammarruntime.LoadLanguage(name, data)
}
func AttachLanguageSupport(name string, lang *gotreesitter.Language) bool {
	return grammarruntime.AttachLanguageSupport(name, lang)
}
func SetEmbeddedLanguageCacheLimit(limit int) { grammarruntime.SetEmbeddedLanguageCacheLimit(limit) }
func EmbeddedLanguageCacheStats() (loaded int, limit int) {
	return grammarruntime.EmbeddedLanguageCacheStats()
}
func UnloadEmbeddedLanguage(blobName string) bool {
	return grammarruntime.UnloadEmbeddedLanguage(blobName)
}
func PurgeEmbeddedLanguageCache() int              { return grammarruntime.PurgeEmbeddedLanguageCache() }
func SetEmbeddedLanguageIdleTTL(ttl time.Duration) { grammarruntime.SetEmbeddedLanguageIdleTTL(ttl) }
func SetEmbeddedLanguageIdleSweepInterval(interval time.Duration) {
	grammarruntime.SetEmbeddedLanguageIdleSweepInterval(interval)
}
func EmbeddedLanguageIdleConfig() (ttl time.Duration, sweepInterval time.Duration) {
	return grammarruntime.EmbeddedLanguageIdleConfig()
}
func LookupExternalScanner(name string) gotreesitter.ExternalScanner {
	return grammarruntime.LookupExternalScanner(name)
}
func LookupExternalLexStates(name string) [][]bool {
	return grammarruntime.LookupExternalLexStates(name)
}
func AdaptScannerForLanguage(name string, targetLang *gotreesitter.Language) bool {
	return grammarruntime.AdaptScannerForLanguage(name, targetLang)
}
