// Code generated by cmd/ts2go batch; DO NOT EDIT.

package grammars

import "github.com/wotjr1649/go-treesitter/internal/runtime"

// AdaLanguage returns the ada language definition.
func AdaLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("ada.bin")
}

// AgdaLanguage returns the agda language definition.
func AgdaLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("agda.bin")
}

// AngularLanguage returns the angular language definition.
func AngularLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("angular.bin")
}

// ApexLanguage returns the apex language definition.
func ApexLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("apex.bin")
}

// ArduinoLanguage returns the arduino language definition.
func ArduinoLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("arduino.bin")
}

// AsmLanguage returns the asm language definition.
func AsmLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("asm.bin")
}

// AstroLanguage returns the astro language definition.
func AstroLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("astro.bin")
}

// AuthzedLanguage returns the authzed language definition.
func AuthzedLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("authzed.bin")
}

// AwkLanguage returns the awk language definition.
func AwkLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("awk.bin")
}

// BashLanguage returns the bash language definition.
func BashLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("bash.bin")
}

// BassLanguage returns the bass language definition.
func BassLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("bass.bin")
}

// BeancountLanguage returns the beancount language definition.
func BeancountLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("beancount.bin")
}

// BibtexLanguage returns the bibtex language definition.
func BibtexLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("bibtex.bin")
}

// BicepLanguage returns the bicep language definition.
func BicepLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("bicep.bin")
}

// BitbakeLanguage returns the bitbake language definition.
func BitbakeLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("bitbake.bin")
}

// BladeLanguage returns the blade language definition.
func BladeLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("blade.bin")
}

// BrightscriptLanguage returns the brightscript language definition.
func BrightscriptLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("brightscript.bin")
}

// CLanguage returns the c language definition.
func CLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("c.bin")
}

// CSharpLanguage returns the c_sharp language definition.
func CSharpLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("c_sharp.bin")
}

// CaddyLanguage returns the caddy language definition.
func CaddyLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("caddy.bin")
}

// CairoLanguage returns the cairo language definition.
func CairoLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("cairo.bin")
}

// CapnpLanguage returns the capnp language definition.
func CapnpLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("capnp.bin")
}

// ChatitoLanguage returns the chatito language definition.
func ChatitoLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("chatito.bin")
}

// CircomLanguage returns the circom language definition.
func CircomLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("circom.bin")
}

// ClojureLanguage returns the clojure language definition.
func ClojureLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("clojure.bin")
}

// CmakeLanguage returns the cmake language definition.
func CmakeLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("cmake.bin")
}

// CobolLanguage returns the cobol language definition.
func CobolLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("cobol.bin")
}

// CommentLanguage returns the comment language definition.
func CommentLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("comment.bin")
}

// CommonlispLanguage returns the commonlisp language definition.
func CommonlispLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("commonlisp.bin")
}

// CooklangLanguage returns the cooklang language definition.
func CooklangLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("cooklang.bin")
}

// CornLanguage returns the corn language definition.
func CornLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("corn.bin")
}

// CponLanguage returns the cpon language definition.
func CponLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("cpon.bin")
}

// CppLanguage returns the cpp language definition.
func CppLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("cpp.bin")
}

// CrystalLanguage returns the crystal language definition.
func CrystalLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("crystal.bin")
}

// CssLanguage returns the css language definition.
func CssLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("css.bin")
}

// CsvLanguage returns the csv language definition.
func CsvLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("csv.bin")
}

// CudaLanguage returns the cuda language definition.
func CudaLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("cuda.bin")
}

// CueLanguage returns the cue language definition.
func CueLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("cue.bin")
}

// CylcLanguage returns the cylc language definition.
func CylcLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("cylc.bin")
}

// DLanguage returns the d language definition.
func DLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("d.bin")
}

// DartLanguage returns the dart language definition.
func DartLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("dart.bin")
}

// DesktopLanguage returns the desktop language definition.
func DesktopLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("desktop.bin")
}

// DevicetreeLanguage returns the devicetree language definition.
func DevicetreeLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("devicetree.bin")
}

// DhallLanguage returns the dhall language definition.
func DhallLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("dhall.bin")
}

// DiffLanguage returns the diff language definition.
func DiffLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("diff.bin")
}

// DisassemblyLanguage returns the disassembly language definition.
func DisassemblyLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("disassembly.bin")
}

// DjotLanguage returns the djot language definition.
func DjotLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("djot.bin")
}

// DockerfileLanguage returns the dockerfile language definition.
func DockerfileLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("dockerfile.bin")
}

// DotLanguage returns the dot language definition.
func DotLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("dot.bin")
}

// DoxygenLanguage returns the doxygen language definition.
func DoxygenLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("doxygen.bin")
}

// DtdLanguage returns the dtd language definition.
func DtdLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("dtd.bin")
}

// EarthfileLanguage returns the earthfile language definition.
func EarthfileLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("earthfile.bin")
}

// EbnfLanguage returns the ebnf language definition.
func EbnfLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("ebnf.bin")
}

// EditorconfigLanguage returns the editorconfig language definition.
func EditorconfigLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("editorconfig.bin")
}

// EdsLanguage returns the eds language definition.
func EdsLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("eds.bin")
}

// EexLanguage returns the eex language definition.
func EexLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("eex.bin")
}

// ElispLanguage returns the elisp language definition.
func ElispLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("elisp.bin")
}

// ElixirLanguage returns the elixir language definition.
func ElixirLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("elixir.bin")
}

// ElmLanguage returns the elm language definition.
func ElmLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("elm.bin")
}

// ElsaLanguage returns the elsa language definition.
func ElsaLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("elsa.bin")
}

// EmbeddedTemplateLanguage returns the embedded_template language definition.
func EmbeddedTemplateLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("embedded_template.bin")
}

// EnforceLanguage returns the enforce language definition.
func EnforceLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("enforce.bin")
}

// ErlangLanguage returns the erlang language definition.
func ErlangLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("erlang.bin")
}

// FacilityLanguage returns the facility language definition.
func FacilityLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("facility.bin")
}

// FaustLanguage returns the faust language definition.
func FaustLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("faust.bin")
}

// FennelLanguage returns the fennel language definition.
func FennelLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("fennel.bin")
}

// FidlLanguage returns the fidl language definition.
func FidlLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("fidl.bin")
}

// FirrtlLanguage returns the firrtl language definition.
func FirrtlLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("firrtl.bin")
}

// FishLanguage returns the fish language definition.
func FishLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("fish.bin")
}

// FoamLanguage returns the foam language definition.
func FoamLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("foam.bin")
}

// ForthLanguage returns the forth language definition.
func ForthLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("forth.bin")
}

// FortranLanguage returns the fortran language definition.
func FortranLanguage() *gotreesitter.Language {
	return loadPreferredLanguage("fortran")
}

// FsharpLanguage returns the fsharp language definition.
func FsharpLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("fsharp.bin")
}

// GdscriptLanguage returns the gdscript language definition.
func GdscriptLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("gdscript.bin")
}

// GitConfigLanguage returns the git_config language definition.
func GitConfigLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("git_config.bin")
}

// GitRebaseLanguage returns the git_rebase language definition.
func GitRebaseLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("git_rebase.bin")
}

// GitattributesLanguage returns the gitattributes language definition.
func GitattributesLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("gitattributes.bin")
}

// GitcommitLanguage returns the gitcommit language definition.
func GitcommitLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("gitcommit.bin")
}

// GitignoreLanguage returns the gitignore language definition.
func GitignoreLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("gitignore.bin")
}

// GleamLanguage returns the gleam language definition.
func GleamLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("gleam.bin")
}

// GlslLanguage returns the glsl language definition.
func GlslLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("glsl.bin")
}

// GnLanguage returns the gn language definition.
func GnLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("gn.bin")
}

// GoLanguage returns the go language definition.
func GoLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("go.bin")
}

// GodotResourceLanguage returns the godot_resource language definition.
func GodotResourceLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("godot_resource.bin")
}

// GomodLanguage returns the gomod language definition.
func GomodLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("gomod.bin")
}

// GraphqlLanguage returns the graphql language definition.
func GraphqlLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("graphql.bin")
}

// GroovyLanguage returns the groovy language definition.
func GroovyLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("groovy.bin")
}

// HackLanguage returns the hack language definition.
func HackLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("hack.bin")
}

// HareLanguage returns the hare language definition.
func HareLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("hare.bin")
}

// HaskellLanguage returns the haskell language definition.
func HaskellLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("haskell.bin")
}

// HaxeLanguage returns the haxe language definition.
func HaxeLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("haxe.bin")
}

// HclLanguage returns the hcl language definition.
func HclLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("hcl.bin")
}

// HeexLanguage returns the heex language definition.
func HeexLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("heex.bin")
}

// HlslLanguage returns the hlsl language definition.
func HlslLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("hlsl.bin")
}

// HtmlLanguage returns the html language definition.
func HtmlLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("html.bin")
}

// HttpLanguage returns the http language definition.
func HttpLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("http.bin")
}

// HurlLanguage returns the hurl language definition.
func HurlLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("hurl.bin")
}

// HyprlangLanguage returns the hyprlang language definition.
func HyprlangLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("hyprlang.bin")
}

// IniLanguage returns the ini language definition.
func IniLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("ini.bin")
}

// JanetLanguage returns the janet language definition.
func JanetLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("janet.bin")
}

// JavaLanguage returns the java language definition.
func JavaLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("java.bin")
}

// JavascriptLanguage returns the javascript language definition.
func JavascriptLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("javascript.bin")
}

// Jinja2Language returns the jinja2 language definition.
func Jinja2Language() *gotreesitter.Language {
	return loadEmbeddedLanguage("jinja2.bin")
}

// JqLanguage returns the jq language definition.
func JqLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("jq.bin")
}

// JsdocLanguage returns the jsdoc language definition.
func JsdocLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("jsdoc.bin")
}

// JsonLanguage returns the json language definition.
func JsonLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("json.bin")
}

// Json5Language returns the json5 language definition.
func Json5Language() *gotreesitter.Language {
	return loadEmbeddedLanguage("json5.bin")
}

// JsonnetLanguage returns the jsonnet language definition.
func JsonnetLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("jsonnet.bin")
}

// JuliaLanguage returns the julia language definition.
func JuliaLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("julia.bin")
}

// JustLanguage returns the just language definition.
func JustLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("just.bin")
}

// KconfigLanguage returns the kconfig language definition.
func KconfigLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("kconfig.bin")
}

// KdlLanguage returns the kdl language definition.
func KdlLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("kdl.bin")
}

// KotlinLanguage returns the kotlin language definition.
func KotlinLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("kotlin.bin")
}

// LedgerLanguage returns the ledger language definition.
func LedgerLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("ledger.bin")
}

// LessLanguage returns the less language definition.
func LessLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("less.bin")
}

// LinkerscriptLanguage returns the linkerscript language definition.
func LinkerscriptLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("linkerscript.bin")
}

// LiquidLanguage returns the liquid language definition.
func LiquidLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("liquid.bin")
}

// LlvmLanguage returns the llvm language definition.
func LlvmLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("llvm.bin")
}

// LuaLanguage returns the lua language definition.
func LuaLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("lua.bin")
}

// LuauLanguage returns the luau language definition.
func LuauLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("luau.bin")
}

// MakeLanguage returns the make language definition.
func MakeLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("make.bin")
}

// MarkdownLanguage returns the markdown language definition.
func MarkdownLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("markdown.bin")
}

// MarkdownInlineLanguage returns the markdown_inline language definition.
func MarkdownInlineLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("markdown_inline.bin")
}

// MatlabLanguage returns the matlab language definition.
func MatlabLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("matlab.bin")
}

// MermaidLanguage returns the mermaid language definition.
func MermaidLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("mermaid.bin")
}

// MesonLanguage returns the meson language definition.
func MesonLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("meson.bin")
}

// MojoLanguage returns the mojo language definition.
func MojoLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("mojo.bin")
}

// MoveLanguage returns the move language definition.
func MoveLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("move.bin")
}

// NginxLanguage returns the nginx language definition.
func NginxLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("nginx.bin")
}

// NickelLanguage returns the nickel language definition.
func NickelLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("nickel.bin")
}

// NimLanguage returns the nim language definition.
func NimLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("nim.bin")
}

// NinjaLanguage returns the ninja language definition.
func NinjaLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("ninja.bin")
}

// NixLanguage returns the nix language definition.
func NixLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("nix.bin")
}

// NorgLanguage returns the norg language definition.
func NorgLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("norg.bin")
}

// NushellLanguage returns the nushell language definition.
func NushellLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("nushell.bin")
}

// ObjcLanguage returns the objc language definition.
func ObjcLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("objc.bin")
}

// OcamlLanguage returns the ocaml language definition.
func OcamlLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("ocaml.bin")
}

// OdinLanguage returns the odin language definition.
func OdinLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("odin.bin")
}

// OrgLanguage returns the org language definition.
func OrgLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("org.bin")
}

// PascalLanguage returns the pascal language definition.
func PascalLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("pascal.bin")
}

// PemLanguage returns the pem language definition.
func PemLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("pem.bin")
}

// PerlLanguage returns the perl language definition.
func PerlLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("perl.bin")
}

// PhpLanguage returns the php language definition.
func PhpLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("php.bin")
}

// PklLanguage returns the pkl language definition.
func PklLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("pkl.bin")
}

// PowershellLanguage returns the powershell language definition.
func PowershellLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("powershell.bin")
}

// PrismaLanguage returns the prisma language definition.
func PrismaLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("prisma.bin")
}

// PrologLanguage returns the prolog language definition.
func PrologLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("prolog.bin")
}

// PromqlLanguage returns the promql language definition.
func PromqlLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("promql.bin")
}

// PropertiesLanguage returns the properties language definition.
func PropertiesLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("properties.bin")
}

// ProtoLanguage returns the proto language definition.
func ProtoLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("proto.bin")
}

// PugLanguage returns the pug language definition.
func PugLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("pug.bin")
}

// PuppetLanguage returns the puppet language definition.
func PuppetLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("puppet.bin")
}

// PurescriptLanguage returns the purescript language definition.
func PurescriptLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("purescript.bin")
}

// PythonLanguage returns the python language definition.
func PythonLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("python.bin")
}

// QlLanguage returns the ql language definition.
func QlLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("ql.bin")
}

// RLanguage returns the r language definition.
func RLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("r.bin")
}

// RacketLanguage returns the racket language definition.
func RacketLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("racket.bin")
}

// RegexLanguage returns the regex language definition.
func RegexLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("regex.bin")
}

// RegoLanguage returns the rego language definition.
func RegoLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("rego.bin")
}

// RequirementsLanguage returns the requirements language definition.
func RequirementsLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("requirements.bin")
}

// RescriptLanguage returns the rescript language definition.
func RescriptLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("rescript.bin")
}

// RobotLanguage returns the robot language definition.
func RobotLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("robot.bin")
}

// RonLanguage returns the ron language definition.
func RonLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("ron.bin")
}

// RstLanguage returns the rst language definition.
func RstLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("rst.bin")
}

// RubyLanguage returns the ruby language definition.
func RubyLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("ruby.bin")
}

// RustLanguage returns the rust language definition.
func RustLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("rust.bin")
}

// ScalaLanguage returns the scala language definition.
func ScalaLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("scala.bin")
}

// SchemeLanguage returns the scheme language definition.
func SchemeLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("scheme.bin")
}

// ScssLanguage returns the scss language definition.
func ScssLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("scss.bin")
}

// SmithyLanguage returns the smithy language definition.
func SmithyLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("smithy.bin")
}

// SolidityLanguage returns the solidity language definition.
func SolidityLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("solidity.bin")
}

// SparqlLanguage returns the sparql language definition.
func SparqlLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("sparql.bin")
}

// SqlLanguage returns the sql language definition.
func SqlLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("sql.bin")
}

// SquirrelLanguage returns the squirrel language definition.
func SquirrelLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("squirrel.bin")
}

// SshConfigLanguage returns the ssh_config language definition.
func SshConfigLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("ssh_config.bin")
}

// StarlarkLanguage returns the starlark language definition.
func StarlarkLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("starlark.bin")
}

// SvelteLanguage returns the svelte language definition.
func SvelteLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("svelte.bin")
}

// SwiftLanguage returns the swift language definition.
func SwiftLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("swift.bin")
}

// TablegenLanguage returns the tablegen language definition.
func TablegenLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("tablegen.bin")
}

// TclLanguage returns the tcl language definition.
func TclLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("tcl.bin")
}

// TealLanguage returns the teal language definition.
func TealLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("teal.bin")
}

// TemplLanguage returns the templ language definition.
func TemplLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("templ.bin")
}

// TextprotoLanguage returns the textproto language definition.
func TextprotoLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("textproto.bin")
}

// ThriftLanguage returns the thrift language definition.
func ThriftLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("thrift.bin")
}

// TlaplusLanguage returns the tlaplus language definition.
func TlaplusLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("tlaplus.bin")
}

// TmuxLanguage returns the tmux language definition.
func TmuxLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("tmux.bin")
}

// TodotxtLanguage returns the todotxt language definition.
func TodotxtLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("todotxt.bin")
}

// TomlLanguage returns the toml language definition.
func TomlLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("toml.bin")
}

// TsxLanguage returns the tsx language definition.
func TsxLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("tsx.bin")
}

// TurtleLanguage returns the turtle language definition.
func TurtleLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("turtle.bin")
}

// TwigLanguage returns the twig language definition.
func TwigLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("twig.bin")
}

// TypescriptLanguage returns the typescript language definition.
func TypescriptLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("typescript.bin")
}

// TypstLanguage returns the typst language definition.
func TypstLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("typst.bin")
}

// UxntalLanguage returns the uxntal language definition.
func UxntalLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("uxntal.bin")
}

// VLanguage returns the v language definition.
func VLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("v.bin")
}

// VerilogLanguage returns the verilog language definition.
func VerilogLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("verilog.bin")
}

// VhdlLanguage returns the vhdl language definition.
func VhdlLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("vhdl.bin")
}

// VimdocLanguage returns the vimdoc language definition.
func VimdocLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("vimdoc.bin")
}

// VueLanguage returns the vue language definition.
func VueLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("vue.bin")
}

// WatLanguage returns the wat language definition.
func WatLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("wat.bin")
}

// WgslLanguage returns the wgsl language definition.
func WgslLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("wgsl.bin")
}

// WolframLanguage returns the wolfram language definition.
func WolframLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("wolfram.bin")
}

// XmlLanguage returns the xml language definition.
func XmlLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("xml.bin")
}

// YamlLanguage returns the yaml language definition.
func YamlLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("yaml.bin")
}

// YuckLanguage returns the yuck language definition.
func YuckLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("yuck.bin")
}

// ZigLanguage returns the zig language definition.
func ZigLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("zig.bin")
}
