// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.

package grammars

import (
	grammarruntime "github.com/wotjr1649/go-treesitter/internal/runtime/grammars/runtime"
)

type ExternalScannerSourceFile = grammarruntime.ExternalScannerSourceFile
type ExternalScannerSpec = grammarruntime.ExternalScannerSpec

func RegisterExternalScannerSpec(spec ExternalScannerSpec) {
	grammarruntime.RegisterExternalScannerSpec(spec)
}
func LookupExternalScannerSpec(name string) (ExternalScannerSpec, bool) {
	return grammarruntime.LookupExternalScannerSpec(name)
}
func ExternalScannerSpecs() []ExternalScannerSpec { return grammarruntime.ExternalScannerSpecs() }
