//go:build !grammar_subset

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.

package grammars

import (
	gotreesitter "github.com/wotjr1649/go-treesitter/internal/runtime"
	grammarruntime "github.com/wotjr1649/go-treesitter/internal/runtime/grammars/runtime"
)

type GenericTokenSource = grammarruntime.GenericTokenSource

func NewGenericTokenSource(src []byte, lang *gotreesitter.Language) (*GenericTokenSource, error) {
	return grammarruntime.NewGenericTokenSource(src, lang)
}
func NewGenericTokenSourceOrEOF(src []byte, lang *gotreesitter.Language) gotreesitter.TokenSource {
	return grammarruntime.NewGenericTokenSourceOrEOF(src, lang)
}
