//go:build !grammar_subset || grammar_subset_json

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.

package grammars

import (
	gotreesitter "github.com/wotjr1649/go-treesitter/internal/runtime"
	grammarruntime "github.com/wotjr1649/go-treesitter/internal/runtime/grammars/runtime"
)

type JSONTokenSource = grammarruntime.JSONTokenSource

func NewJSONTokenSource(src []byte, lang *gotreesitter.Language) (*JSONTokenSource, error) {
	return grammarruntime.NewJSONTokenSource(src, lang)
}
func NewJSONTokenSourceOrEOF(src []byte, lang *gotreesitter.Language) gotreesitter.TokenSource {
	return grammarruntime.NewJSONTokenSourceOrEOF(src, lang)
}
