//go:build !grammar_subset || grammar_subset_lua

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.

package grammars

import (
	gotreesitter "github.com/wotjr1649/go-treesitter/internal/runtime"
	grammarruntime "github.com/wotjr1649/go-treesitter/internal/runtime/grammars/runtime"
)

type LuaTokenSource = grammarruntime.LuaTokenSource

func NewLuaTokenSource(src []byte, lang *gotreesitter.Language) (*LuaTokenSource, error) {
	return grammarruntime.NewLuaTokenSource(src, lang)
}
func NewLuaTokenSourceOrEOF(src []byte, lang *gotreesitter.Language) gotreesitter.TokenSource {
	return grammarruntime.NewLuaTokenSourceOrEOF(src, lang)
}
