package grammars

// ParseSmokeSamples maps language names to minimal source snippets used
// for smoke testing. Each sample should parse without errors under the
// language's supported backend.
//
// Languages not listed here fall back to "x\n" as a generic probe.
var ParseSmokeSamples = map[string]string{
	"agda":              "module M where\n",
	"authzed":           "definition user {}\n",
	"bash":              "echo hi\n",
	"c":                 "int main(void) { return 0; }\n",
	"capnp":             "@0xdbb9ad1f14bf0b36;\nstruct Person {\n  name @0 :Text;\n}\n",
	"c_sharp":           "using System;\n",
	"comment":           "TODO: implement feature\n",
	"corn":              "{ x = 1 }\n",
	"cpp":               "#include <iostream>\nint main() { std::cout << 1; return 0; }\n",
	"css":               "body { color: red; }\n",
	"desktop":           "[Desktop Entry]\n",
	"dtd":               "<!ELEMENT note (#PCDATA)>\n",
	"doxygen":           "/**\n * @param x A\n */\n",
	"earthfile":         "FROM alpine\n",
	"editorconfig":      "root = true\n",
	"go":                "package main\n\nfunc main() {\n\tprintln(1)\n}\n",
	"embedded_template": "<% if true %>\n  hello\n<% end %>\n",
	"facility":          "service Example {\n}\n",
	"foam":              "FoamFile\n{\n    version 2.0;\n}\n",
	"fidl":              "library example;\ntype Foo = struct {};\n",
	"firrtl":            "circuit Top :\n",
	"haskell":           "module Main where\nimport Data.List\nmain :: IO ()\nmain = putStrLn \"hello\"",
	"html":              "<html><body>Hello</body></html>\n",
	"java":              "class Main { int x; }\n",
	"javascript":        "function f() { return 1; }\nconst x = () => x + 1;\n",
	"json":              "{\"a\": 1}\n",
	"julia":             "module M\nx = 1\nend\n",
	"kotlin":            "fun main() {\n    val x: Int? = null\n    println(x)\n}\n",
	"lua":               "local x = 1\n",
	"php":               "<?php echo 1;\n",
	"python":            "def f():\n    return 1\n",
	"regex":             "a+b*\n",
	"ruby":              "def f\n  1\nend\n",
	"rust":              "fn main() { let x = 1; }\n",
	"sql":               "SELECT id, name FROM users WHERE id = 1;\n",
	"swift":             "let x = 1\n",
	"toml":              "a = 1\ntitle = \"hello\"\ntags = [\"x\", \"y\"]\n",
	"tsx":               "function App(): JSX.Element {\n  const x = 1;\n  return <div>{x}</div>;\n}\n",
	"typescript":        "function f(): number { return 1; }\n",
	"yaml":              "key: value\nnested:\n  inner: data\n",
	"zig":               "const x: i32 = 1;\n",
	"scala":             "object Main { def f(x: Int): Int = x + 1 }\n",
	"elixir":            "defmodule M do\n  def f(x), do: x\nend\n",
	"graphql":           "type Query { hello: String }\n",
	"hcl":               "a = 1\n",
	"nix":               "let x = 1; in x\n",
	"ocaml":             "let x = 1\n",
	"verilog":           "module m;\nendmodule\n",

	// RE/binary analysis grammars
	"asm":         "main:\n    mov eax, 1\n    ret\n",
	"disassembly": "0x400601 <__libc_csu_init+33>   sub    %r12,%rbp\n1000: 55                   push   rbp\n",
	"wat":         "(module\n  (func $add (param i32 i32) (result i32)\n    local.get 0\n    local.get 1\n    i32.add))\n",

	// Phase 2: DFA-only languages
	"dot":        "digraph G { a -> b; }\n",
	"git_config": "[core]\n\tbare = false\n",
	"ini":        "[section]\nkey = value\n",
	"json5":      "{ \"key\": \"value\" }\n",
	"make":       "all:\n\t@echo hi\n",
	"llvm":       "define i32 @main() {\n  call void @puts()\n  ret i32 0\n}\n",
	"move":       "module 0x1::m {}\n",
	"ninja":      "rule cc\n  command = gcc\n",
	"pascal":     "program Hello;\nvar x: integer;\nbegin\n  x := 42;\nend.\n",
	"v":          "fn main() {}\n",
	"caddy":      ":8080 {\n}\n",
	"d":          "module m;\nint main() { return 0; }\n",
	"scss":       ".a { color: red; }\n",
	"vimdoc":     "*tag*\n\n",

	// Phase 3: scanner-needed languages (targeted samples that avoid external tokens)
	"jsdoc":      "/**\n * @param {string} name\n * @returns {number}\n */\n",
	"wgsl":       "fn main() {}\n",
	"nginx":      "http {\n  server {\n    listen 80;\n    server_name example.com;\n  }\n}\n",
	"svelte":     "<script>\n  let count = 0;\n</script>\n<p>{count}</p>\n",
	"xml":        "<root/>\n",
	"r":          "x <- 1\n",
	"rescript":   "1\n",
	"purescript": "module Main where",
	"rst":        "Title\n=====\n",
	"vhdl":       "-- comment\n",

	// DFA with external scanner (trailing newline breaks nushell root node)
	"nushell": "let x = 1",

	// Phase 5: new grammars
	"gdscript":       "extends Node\n",
	"godot_resource": "x = 1\n",
	"groovy":         "def x = 1\n",
	"hare":           "export fn main() void = void;\n",
	"hyprlang":       "general {\n}\n",
	"ledger":         "2024-01-01 Groceries\n  Expenses:Food  $50\n  Assets:Bank\n",
	"liquid":         "{{ name }}\n",
	"nickel":         "1 + 2\n",
	"pem":            "-----BEGIN CERTIFICATE-----\nMIIC\n-----END CERTIFICATE-----\n",
	"pkl":            "x = 1\n",
	"prisma":         "model User {\n  id Int @id\n}\n",
	"promql":         "up{job=\"prometheus\"}\n",
	"ql":             "from int x where x = 1 select x\n",
	"rego":           "package p\n",
	"ron":            "(x: 1)\n",
	"squirrel":       "local x = 1;\n",
	"tablegen":       "class Foo;\n",
	"thrift":         "struct Foo {}\n",
	"uxntal":         "|00 @System &vector $2\n",

	// Phase 6 new grammars
	"crystal":   "x = 1\n",
	"elisp":     "(message \"hello\")\n",
	"fsharp":    "module M\n",
	"haxe":      "class Main {\n  static function main() {}\n}\n",
	"teal":      "local x: number = 1\n",
	"forth":     ": square dup * ;\n",
	"cobol":     "       IDENTIFICATION DIVISION.\n       PROGRAM-ID. HELLO.\n",
	"heex":      "<p>hello</p>\n",
	"templ":     "templ T() { <div>ok</div> }\n",
	"jinja2":    "{% if x %}ok{% endif %}\n",
	"gomod":     "module example.com/foo\n\ngo 1.21\n",
	"jq":        "def f: . | length; .foo | f\n",
	"smithy":    "namespace example\n",
	"textproto": "name: \"hello\"\n",
	"tlaplus":   "---- MODULE Test ----\n====\n",
	"matlab":    "1\n",
	"sparql":    "SELECT ?x WHERE { ?x a ?y }\n",
	"turtle":    "@prefix ex: <http://example.org/> .\n",
	"yuck":      "(box :class \"main\" (label :text \"hi\"))\n",
	"typst":     "1\n",

	// Phase 7: missing popular languages
	"perl":    "my $x = 1;\n",
	"prolog":  "parent(tom, bob).\n",
	"mojo":    "fn main():\n    print(1)\n",
	"wolfram": "f[x] := x^2\nTable[f[i], {i, 10}]\n",
	"norg":    "* Heading\n  Some text here.\n",

	// Phase 8: remaining languages (complete coverage)
	"ada":             "procedure Hello is\nbegin\n  null;\nend Hello;\n",
	"angular":         "<div>hello</div>\n",
	"apex":            "public class Hello {\n  public void run() {}\n}\n",
	"arduino":         "void setup() {}\nvoid loop() {}\n",
	"astro":           "---\n---\n<html><body>hello</body></html>\n",
	"awk":             "{ print $1 }\n",
	"bass":            "(def x 1)\n",
	"beancount":       "2024-01-01 open Assets:Bank\n",
	"bibtex":          "@article{key, author={A}}\n",
	"bicep":           "param name string\n",
	"bitbake":         "SUMMARY = \"hello\"\n",
	"blade":           "@if (true)\n  <div>hello</div>\n@endif\n",
	"brightscript":    "sub main()\nend sub\n",
	"cairo":           "fn main() {}\n",
	"chatito":         "%[greet]\n    hi\n",
	"circom":          "template Main() {}\n",
	"clojure":         "(def x 1)\n",
	"cmake":           "cmake_minimum_required(VERSION 3.10)\n",
	"commonlisp":      "(defun f () 1)\n",
	"cooklang":        "Add @salt{1%tsp}\n",
	"cpon":            "{\"a\":1}\n",
	"csv":             "a,b,c\n1,2,3\n",
	"cuda":            "__global__ void kernel() {}\n",
	"cue":             "x: 1\n",
	"cylc":            "[scheduling]\n",
	"dart":            "void main() {}\n",
	"devicetree":      "/dts-v1/;\n/ {\n};\n",
	"dhall":           "let x = 1 in x\n",
	"diff":            "--- a/file\n+++ b/file\n@@ -1 +1 @@\n-old\n+new\n",
	"djot":            "Hello world\n",
	"dockerfile":      "FROM alpine\nRUN echo hi\n",
	"ebnf":            "rule = \"a\" ;\n",
	"eds":             "[1000]\nParameterName=Device type\n",
	"eex":             "<%= 1 + 1 %>\n",
	"elm":             "module Main exposing (main)\nmain = 1\n",
	"elsa":            "let x = y\n",
	"enforce":         "package p;\n",
	"erlang":          "-module(hello).\n",
	"faust":           "process = _;\n",
	"fennel":          "(let [x 1] x)\n",
	"fish":            "set x 1\n",
	"fortran":         "program hello\n  implicit none\nend program hello\n",
	"git_rebase":      "pick abc1234 Initial commit\nreword def5678 Fix typo\n",
	"gitattributes":   "*.txt text\n",
	"gitcommit":       "Initial commit\n",
	"gitignore":       "*.o\n",
	"gleam":           "pub fn main() {}\n",
	"glsl":            "void main() { gl_Position = vec4(0.0); }\n",
	"gn":              "group(\"all\") {}\n",
	"hack":            "<<__EntryPoint>>\nfunction main(): void {}\n",
	"hlsl":            "float4 main() : SV_Target { return 0; }\n",
	"http":            "GET /path\n",
	"hurl":            "GET http://example.com\nHTTP 200\n",
	"janet":           "(def x 1)\n",
	"jsonnet":         "{ x: 1 }\n",
	"just":            "default:\n  echo hello\n",
	"kconfig":         "config FOO\n  bool \"Enable foo\"\n",
	"kdl":             "node \"value\"\n",
	"less":            "body { color: red; }\n",
	"linkerscript":    "SECTIONS { .text : { *(.text) } }\n",
	"luau":            "local x: number = 1\n",
	"markdown":        "# Heading\n",
	"markdown_inline": "hello **world**\n",
	"mermaid":         "flowchart TD\nA-->B\n",
	"meson":           "message('hello')\n",
	"nim":             "echo \"hello\"\n",
	"objc":            "@interface Foo : NSObject\n@end\n",
	"odin":            "package main\n",
	"org":             "* TODO Heading\n",
	"powershell":      "$x = 1\n",
	"properties":      "key=value\n",
	"proto":           "syntax = \"proto3\";\n",
	"pug":             "p hello\n",
	"puppet":          "class hello {}\n",
	"racket":          "#lang racket\n(define x 1)\n",
	"requirements":    "flask==2.0\n",
	"robot":           "*** Test Cases ***\nTest\n  Log  hello\n",
	"scheme":          "(define x 1)\n",
	"solidity":        "pragma solidity ^0.8.0;\n",
	"ssh_config":      "Host example\n  User admin\n",
	"starlark":        "x = 1\n",
	"tcl":             "set x 1\n",
	"tmux":            "set -g status on\n",
	"todotxt":         "(A) Buy milk @store\n",
	"twig":            "{{ name }}\n",
	"vue":             "<template><div>hello</div></template>\n",
}

// ParseSmokeSample returns the smoke test sample for the given language,
// falling back to "x\n" for languages without a dedicated sample.
func ParseSmokeSample(name string) string {
	if sample, ok := ParseSmokeSamples[name]; ok {
		return sample
	}
	return "x\n"
}
