//go:build !grammar_subset || grammar_subset_toml

// Code generated by cmd/gen_grammar_packages; DO NOT EDIT.

package grammars

import (
	gotreesitter "github.com/wotjr1649/go-treesitter/internal/runtime"
	grammarruntime "github.com/wotjr1649/go-treesitter/internal/runtime/grammars/runtime"
)

type TomlTokenSource = grammarruntime.TomlTokenSource

func NewTomlTokenSource(src []byte, lang *gotreesitter.Language) (*TomlTokenSource, error) {
	return grammarruntime.NewTomlTokenSource(src, lang)
}
func NewTomlTokenSourceOrEOF(src []byte, lang *gotreesitter.Language) gotreesitter.TokenSource {
	return grammarruntime.NewTomlTokenSourceOrEOF(src, lang)
}
