//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_jinja2

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/jinja2.bin
var subsetBlobFS_jinja2 embed.FS

func init() { registerSubsetEmbeddedBlob("jinja2.bin", subsetBlobFS_jinja2) }
