//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_rst

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/rst.bin
var subsetBlobFS_rst embed.FS

func init() { registerSubsetEmbeddedBlob("rst.bin", subsetBlobFS_rst) }
