//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_tablegen

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/tablegen.bin
var subsetBlobFS_tablegen embed.FS

func init() { registerSubsetEmbeddedBlob("tablegen.bin", subsetBlobFS_tablegen) }
