//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_ledger

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/ledger.bin
var subsetBlobFS_ledger embed.FS

func init() { registerSubsetEmbeddedBlob("ledger.bin", subsetBlobFS_ledger) }
