//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_cairo

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/cairo.bin
var subsetBlobFS_cairo embed.FS

func init() { registerSubsetEmbeddedBlob("cairo.bin", subsetBlobFS_cairo) }
