//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_purescript

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/purescript.bin
var subsetBlobFS_purescript embed.FS

func init() { registerSubsetEmbeddedBlob("purescript.bin", subsetBlobFS_purescript) }
