//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_gitcommit

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/gitcommit.bin
var subsetBlobFS_gitcommit embed.FS

func init() { registerSubsetEmbeddedBlob("gitcommit.bin", subsetBlobFS_gitcommit) }
