//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_elsa

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/elsa.bin
var subsetBlobFS_elsa embed.FS

func init() { registerSubsetEmbeddedBlob("elsa.bin", subsetBlobFS_elsa) }
