//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_racket

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/racket.bin
var subsetBlobFS_racket embed.FS

func init() { registerSubsetEmbeddedBlob("racket.bin", subsetBlobFS_racket) }
