//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_pascal

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/pascal.bin
var subsetBlobFS_pascal embed.FS

func init() { registerSubsetEmbeddedBlob("pascal.bin", subsetBlobFS_pascal) }
