//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_hcl

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/hcl.bin
var subsetBlobFS_hcl embed.FS

func init() { registerSubsetEmbeddedBlob("hcl.bin", subsetBlobFS_hcl) }
