//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_bitbake

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/bitbake.bin
var subsetBlobFS_bitbake embed.FS

func init() { registerSubsetEmbeddedBlob("bitbake.bin", subsetBlobFS_bitbake) }
