//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_odin

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/odin.bin
var subsetBlobFS_odin embed.FS

func init() { registerSubsetEmbeddedBlob("odin.bin", subsetBlobFS_odin) }
