//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_sparql

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/sparql.bin
var subsetBlobFS_sparql embed.FS

func init() { registerSubsetEmbeddedBlob("sparql.bin", subsetBlobFS_sparql) }
