//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_commonlisp

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/commonlisp.bin
var subsetBlobFS_commonlisp embed.FS

func init() { registerSubsetEmbeddedBlob("commonlisp.bin", subsetBlobFS_commonlisp) }
