//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_dhall

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/dhall.bin
var subsetBlobFS_dhall embed.FS

func init() { registerSubsetEmbeddedBlob("dhall.bin", subsetBlobFS_dhall) }
