//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_cobol

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/cobol.bin
var subsetBlobFS_cobol embed.FS

func init() { registerSubsetEmbeddedBlob("cobol.bin", subsetBlobFS_cobol) }
