//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_wgsl

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/wgsl.bin
var subsetBlobFS_wgsl embed.FS

func init() { registerSubsetEmbeddedBlob("wgsl.bin", subsetBlobFS_wgsl) }
