//go:build grammar_subset && grammar_subset_jsonnet

package grammars

func init() {
	Register(LangEntry{
		Name:           "jsonnet",
		Extensions:     []string{".jsonnet", ".libsonnet"},
		Language:       JsonnetLanguage,
		GrammarSource:  GrammarSourceTS2GoBlob,
		HighlightQuery: "(id) @variable\n(comment) @comment\n\n; Literals\n(null) @constant.builtin\n(string) @string\n(number) @number\n[\n  (true)\n  (false)\n] @boolean\n\n; Keywords\n\"for\" @repeat\n\"in\" @keyword.operator\n\"function\" @keyword.function\n[\n  \"if\"\n  \"then\"\n  \"else\"\n] @conditional\n[\n  (local)\n  (tailstrict)\n  \"function\"\n  \"assert\"\n  \"error\"\n] @keyword\n\n[\n  (dollar)\n  (self)\n  (super)\n] @variable.builtin\n((id) @variable.builtin\n (#eq? @variable.builtin \"std\"))\n\n; Operators\n[\n  (multiplicative)\n  (additive)\n  (bitshift)\n  (comparison)\n  (equality)\n  (bitand)\n  (bitxor)\n  (bitor)\n  (and)\n  (or)\n  (unaryop)\n] @operator\n\n; Punctuation\n[\n  \"[\"\n  \"]\"\n  \"{\"\n  \"}\"\n  \"(\"\n  \")\"\n] @punctuation.bracket\n\n[\n  \".\"\n  \",\"\n  \";\"\n  \":\"\n] @punctuation.delimiter\n\n[\n  \"::\"\n  \":::\"\n] @punctuation.special\n\n(field\n  (fieldname) \"+\" @punctuation.special)\n\n; Imports\n[\n  (import)\n  (importstr)\n] @include\n\n; References\n\n; Make reference same color as parameter \n; (may incur performance issues on big files)\n; Depends on locals.scm\n((id) @parameter.reference\n (#is? @parameter.reference parameter))\n\n((id) @function.reference\n (#is? @function.reference function))\n\n((id) @var.reference\n (#is? @var.reference var))\n((id) @define\n (#is? @var.reference var))\n\n; References do not apply to static field IDs\n; Workaround for `(#is-not? local)` not supported\n(fieldname (id) @field)\n(fieldname (string\n             (string_start) @text.strong\n             (string_content) @field\n             (string_end) @text.strong\n           ))\n\n; But it does apply if ID in an expression\n(fieldname\n (\"[\"\n  (id) @parameter.reference\n  \"]\"\n  (#is? @parameter.reference parameter)))\n(fieldname\n (\"[\"\n  (id) @define\n  \"]\"\n  (#is? @var.reference var)))\n\n; Functions\n(field\n  function: (fieldname (id) @function))\n(field\n  function: (fieldname\n              (string\n                (string_start) @text.strong\n                (string_content) @function\n                (string_end) @text.strong\n              )))\n(param\n  identifier: (id) @parameter)\n\n(bind (id) @define)\n(bind function: (id) @function)\n\n; Function call\n(functioncall\n  (fieldaccess\n    last: (id) @function.call\n  )?\n  (fieldaccess_super\n    (id) @function.call\n  )?\n  (id)? @function.call\n  \"(\"\n  (args\n    (named_argument\n      (id) @parameter\n    )\n  )?\n  \")\"\n)\n\n; Emphasize implicit plus usage\n(implicit_plus\n  (_ \"}\"? @text.danger)\n  (object\n    \"{\" @text.danger\n  )\n)\n\n; ERROR\n(ERROR) @error\n",
	})
}
