//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_prisma

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/prisma.bin
var subsetBlobFS_prisma embed.FS

func init() { registerSubsetEmbeddedBlob("prisma.bin", subsetBlobFS_prisma) }
