//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_r

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/r.bin
var subsetBlobFS_r embed.FS

func init() { registerSubsetEmbeddedBlob("r.bin", subsetBlobFS_r) }
