//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_diff

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/diff.bin
var subsetBlobFS_diff embed.FS

func init() { registerSubsetEmbeddedBlob("diff.bin", subsetBlobFS_diff) }
