//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_wolfram

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/wolfram.bin
var subsetBlobFS_wolfram embed.FS

func init() { registerSubsetEmbeddedBlob("wolfram.bin", subsetBlobFS_wolfram) }
