//go:build grammar_subset && grammar_subset_puppet

package grammars

func init() {
	Register(LangEntry{
		Name:           "puppet",
		Extensions:     []string{".pp"},
		Language:       PuppetLanguage,
		GrammarSource:  GrammarSourceTS2GoBlob,
		HighlightQuery: "; Variables\n\n(identifier) @variable\n\n; Includes\n\n\"include\" @include\n\n(include_statement (identifier) @type)\n\n(include_statement (class_identifier (identifier) @type . ))\n\n; Keywords\n\n[\n  \"class\"\n  \"inherits\"\n  \"node\"\n  \"type\"\n  \"tag\"\n] @keyword\n\n[\n  \"define\"\n  \"function\"\n] @keyword.function\n\n[\n  \"if\"\n  \"elsif\"\n  \"else\"\n  \"unless\"\n  \"case\"\n] @conditional\n\n(default_case \"default\" @conditional)\n\n; Properties\n\n(attribute name: (identifier) @property)\n(attribute name: (variable (identifier) @property))\n\n; Parameters\n\n(lambda (variable (identifier) @parameter))\n\n(parameter (variable (identifier) @parameter))\n\n(function_call (identifier) @parameter)\n\n; Functions\n\n(function_declaration\n  \"function\" . (identifier) @function)\n\n(function_call\n  (identifier) @function.call \"(\")\n\n(function_call\n  (field_expression \".\" (identifier) @method.call) \"(\")\n\n(defined_resource_type\n  \"define\" . (identifier) @function)\n\n; Methods\n\n(function_declaration\n  \"function\" . (class_identifier (identifier) @method . ))\n\n(function_call\n  (class_identifier (identifier) @method.call . ))\n\n(defined_resource_type\n  \"define\" . (class_identifier (identifier) @method . ))\n\n; Types\n\n(type) @type\n\n(builtin_type) @type.builtin\n\n(class_definition\n  (identifier) @type)\n(class_definition\n  (class_identifier (identifier) @type . ))\n\n(class_inherits (identifier) @type)\n(class_inherits (class_identifier (identifier) @type . ))\n\n(resource_declaration\n  (identifier) @type)\n(resource_declaration\n  (class_identifier (identifier) @type . ))\n\n(node_definition (node_name (identifier) @type))\n\n((identifier) @type\n  (#lua-match? @type \"^[A-Z]\"))\n\n((identifier) @type.builtin\n  (#any-of? @type.builtin \"Boolean\" \"Integer\" \"Float\" \"String\" \"Array\" \"Hash\" \"Regexp\" \"Variant\" \"Data\" \"Undef\" \"Default\" \"File\"))\n\n; \"Namespaces\"\n\n(class_identifier . (identifier) @namespace)\n\n; Operators\n\n[\n  \"or\"\n  \"and\"\n  \"in\"\n] @keyword.operator\n\n[\n  \"=\"\n  \"+=\"\n  \"->\"\n  \"~>\"\n  \"<<|\"\n  \"<|\"\n  \"|>\"\n  \"|>>\"\n  \"?\"\n  \">\"\n  \">=\"\n  \"<=\"\n  \"<\"\n  \"==\"\n  \"!=\"\n  \"<<\"\n  \">>\"\n  \"+\"\n  \"-\"\n  \"*\"\n  \"/\"\n  \"%\"\n  \"=~\"\n  \"!~\"\n] @operator\n\n; Punctuation\n\n[\n  \"|\"\n  \".\"\n  \",\"\n  \";\"\n  \":\"\n  \"::\"\n  \"=>\"\n] @punctuation.delimiter\n\n[ \"{\" \"}\" ] @punctuation.bracket\n\n[ \"[\" \"]\" ] @punctuation.bracket\n\n[ \"(\" \")\" ] @punctuation.bracket\n\n(interpolation [ \"${\" \"}\" ] @punctuation.special)\n\n[\n  \"$\"\n  \"@\"\n  \"@@\"\n] @punctuation.special\n\n; Literals\n\n(number) @number\n\n(float) @float\n\n(string) @string\n\n(escape_sequence) @string.escape\n\n(regex) @string.regex\n\n(boolean) @boolean\n\n[\n  (undef)\n  (default)\n] @variable.builtin\n\n; Comments\n\n(comment) @comment @spell\n\n; Errors\n\n(ERROR) @error\n",
	})
}
