//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_php

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/php.bin
var subsetBlobFS_php embed.FS

func init() { registerSubsetEmbeddedBlob("php.bin", subsetBlobFS_php) }
