//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_toml

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/toml.bin
var subsetBlobFS_toml embed.FS

func init() { registerSubsetEmbeddedBlob("toml.bin", subsetBlobFS_toml) }
