//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_kdl

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/kdl.bin
var subsetBlobFS_kdl embed.FS

func init() { registerSubsetEmbeddedBlob("kdl.bin", subsetBlobFS_kdl) }
