//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_vimdoc

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/vimdoc.bin
var subsetBlobFS_vimdoc embed.FS

func init() { registerSubsetEmbeddedBlob("vimdoc.bin", subsetBlobFS_vimdoc) }
