//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_turtle

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/turtle.bin
var subsetBlobFS_turtle embed.FS

func init() { registerSubsetEmbeddedBlob("turtle.bin", subsetBlobFS_turtle) }
