//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_cylc

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/cylc.bin
var subsetBlobFS_cylc embed.FS

func init() { registerSubsetEmbeddedBlob("cylc.bin", subsetBlobFS_cylc) }
