//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_rescript

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/rescript.bin
var subsetBlobFS_rescript embed.FS

func init() { registerSubsetEmbeddedBlob("rescript.bin", subsetBlobFS_rescript) }
