//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_requirements

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/requirements.bin
var subsetBlobFS_requirements embed.FS

func init() { registerSubsetEmbeddedBlob("requirements.bin", subsetBlobFS_requirements) }
