//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_nim

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/nim.bin
var subsetBlobFS_nim embed.FS

func init() { registerSubsetEmbeddedBlob("nim.bin", subsetBlobFS_nim) }
