//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_perl

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/perl.bin
var subsetBlobFS_perl embed.FS

func init() { registerSubsetEmbeddedBlob("perl.bin", subsetBlobFS_perl) }
