//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_bibtex

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/bibtex.bin
var subsetBlobFS_bibtex embed.FS

func init() { registerSubsetEmbeddedBlob("bibtex.bin", subsetBlobFS_bibtex) }
