//go:build grammar_subset && grammar_subset_sql

package grammars

func init() {
	Register(LangEntry{
		Name:           "sql",
		Extensions:     []string{".sql"},
		Language:       SqlLanguage,
		GrammarSource:  GrammarSourceTS2GoBlob,
		HighlightQuery: "(string) @string\n(number) @number\n(comment) @comment\n\n(function_call\n    function: (identifier) @function)\n\n[\n  (NULL)\n  (TRUE)\n  (FALSE)\n] @constant.builtin\n\n([\n  (type_cast\n   (type (identifier) @type.builtin))\n  (create_function_statement\n   (type (identifier) @type.builtin))\n  (create_function_statement\n   (create_function_parameters\n     (create_function_parameter (type (identifier) @type.builtin))))\n  (create_type_statement\n    (type_spec_composite (type (identifier) @type.builtin)))\n  (create_table_statement\n   (table_parameters\n     (table_column (type (identifier) @type.builtin))))\n ]\n (#match?\n   @type.builtin\n    \"^(bigint|BIGINT|int8|INT8|bigserial|BIGSERIAL|serial8|SERIAL8|bit|BIT|varbit|VARBIT|boolean|BOOLEAN|bool|BOOL|box|BOX|bytea|BYTEA|character|CHARACTER|char|CHAR|varchar|VARCHAR|cidr|CIDR|circle|CIRCLE|date|DATE|float8|FLOAT8|inet|INET|integer|INTEGER|int|INT|int4|INT4|interval|INTERVAL|json|JSON|jsonb|JSONB|line|LINE|lseg|LSEG|macaddr|MACADDR|money|MONEY|numeric|NUMERIC|decimal|DECIMAL|path|PATH|pg_lsn|PG_LSN|point|POINT|polygon|POLYGON|real|REAL|float4|FLOAT4|smallint|SMALLINT|int2|INT2|smallserial|SMALLSERIAL|serial2|SERIAL2|serial|SERIAL|serial4|SERIAL4|text|TEXT|time|TIME|time|TIME|timestamp|TIMESTAMP|tsquery|TSQUERY|tsvector|TSVECTOR|txid_snapshot|TXID_SNAPSHOT|enum|ENUM|range|RANGE)$\"))\n\n(identifier) @variable\n\n[\n  \"::\"\n  \"<\"\n  \"<=\"\n  \"<>\"\n  \"=\"\n  \">\"\n  \">=\"\n] @operator\n\n[\n  \"(\"\n  \")\"\n  \"[\"\n  \"]\"\n] @punctuation.bracket\n\n[\n  \";\"\n  \".\"\n] @punctuation.delimiter\n\n[\n  (type)\n  (array_type)\n] @type\n\n[\n (primary_key_constraint)\n (unique_constraint)\n (null_constraint)\n] @keyword\n\n[\n  \"AND\"\n  \"AS\"\n  \"AUTO_INCREMENT\"\n  \"CREATE\"\n  \"CREATE_DOMAIN\"\n  \"CREATE_OR_REPLACE_FUNCTION\"\n  \"CREATE_SCHEMA\"\n  \"TABLE\"\n  \"TEMPORARY\"\n  \"CREATE_TYPE\"\n  \"DATABASE\"\n  \"FROM\"\n  \"GRANT\"\n  \"GROUP_BY\"\n  \"IF_NOT_EXISTS\"\n  \"INDEX\"\n  \"INNER\"\n  \"INSERT\"\n  \"INTO\"\n  \"IN\"\n  \"JOIN\"\n  \"LANGUAGE\"\n  \"LEFT\"\n  \"LOCAL\"\n  \"NOT\"\n  \"ON\"\n  \"OR\"\n  \"ORDER_BY\"\n  \"OUTER\"\n  \"PRIMARY_KEY\"\n  \"PUBLIC\"\n  \"RETURNS\"\n  \"SCHEMA\"\n  \"SELECT\"\n  \"SESSION\"\n  \"SET\"\n  \"TABLE\"\n  \"TIME_ZONE\"\n  \"TO\"\n  \"UNIQUE\"\n  \"UPDATE\"\n  \"USAGE\"\n  \"VALUES\"\n  \"WHERE\"\n  \"WITH\"\n  \"WITHOUT\"\n] @keyword\n",
	})
}
