//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_starlark

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/starlark.bin
var subsetBlobFS_starlark embed.FS

func init() { registerSubsetEmbeddedBlob("starlark.bin", subsetBlobFS_starlark) }
