//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_angular

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/angular.bin
var subsetBlobFS_angular embed.FS

func init() { registerSubsetEmbeddedBlob("angular.bin", subsetBlobFS_angular) }
