//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_ssh_config

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/ssh_config.bin
var subsetBlobFS_ssh_config embed.FS

func init() { registerSubsetEmbeddedBlob("ssh_config.bin", subsetBlobFS_ssh_config) }
