//go:build grammar_subset && grammar_subset_linkerscript

package grammars

func init() {
	Register(LangEntry{
		Name:           "linkerscript",
		Extensions:     []string{".ld", ".lds"},
		Language:       LinkerscriptLanguage,
		GrammarSource:  GrammarSourceTS2GoBlob,
		HighlightQuery: "; Keywords\n\n[\n  \"ENTRY\"\n  \"SECTIONS\"\n  \"AT\"\n  \"OVERLAY\"\n  \"NOCROSSREFS\"\n  \"MEMORY\"\n  \"PHDRS\"\n  \"FILEHDR\"\n] @keyword\n\n; Conditionals\n\n(conditional_expression [ \"?\" \":\" ] @conditional.ternary)\n\n; Variables\n\n(symbol) @variable\n\n(filename) @string.special @text.underline\n\n; Functions\n\n(call_expression\n  function: (symbol) @function.call)\n\n((call_expression\n  function: (symbol) @preproc)\n  (#eq? @preproc \"DEFINED\"))\n\n((call_expression\n  function: (symbol) @function.builtin)\n  (#any-of? @function.builtin\n   \"ABSOLUTE\" \"ALIAS\" \"ADDR\" \"ALIGN\" \"ALIGNOF\" \"BASE\" \"BLOCK\" \"CHIP\" \"DATA_SEGMENT_ALIGN\"\n   \"DATA_SEGMENT_END\" \"DATA_SEGMENT_RELRO_END\" \"END\" \"LENGTH\" \"LOADADDR\" \"LOG2CEIL\" \"MAX\" \"MIN\"\n   \"NEXT\" \"ORIGIN\" \"SEGMENT_START\" \"SIZEOF\" \"BYTE\" \"FILL\" \"LONG\" \"SHORT\" \"QUAD\" \"SQUAD\" \"WORD\"))\n\n[\n  \"KEEP\"\n  \"PROVIDE\"\n  \"PROVIDE_HIDDEN\"\n] @function.builtin\n\n; Types\n\n(section_type \"(\" [ \"NOLOAD\" \"DSECT\" \"COPY\" \"INFO\" \"OVERLAY\" ] @type.builtin \")\")\n\n; Fields\n\n[\n  \"ORIGIN\" \"org\" \"o\"\n  \"LENGTH\" \"len\" \"l\"\n] @field.builtin\n\n; Constants\n\n((symbol) @constant\n  (#lua-match? @constant \"^[%u_][%u%d_]+$\"))\n\n; Labels\n\n(entry_command name: (symbol) @label)\n\n(output_section name: (symbol) @label)\n\n(memory_command name: (symbol) @label)\n\n(phdrs_command name: (symbol) @label)\n\n(region \">\" (symbol) @label)\n\n(lma_region \">\" (symbol) @label)\n\n(phdr \":\" (symbol) @label)\n\n([(symbol) (filename)] @label\n  (#lua-match? @label \"^%.\"))\n\n; Exceptions\n\n\"ASSERT\" @exception\n\n[\n  \"/DISCARD/\"\n  \".\"\n] @variable.builtin\n\n; Operators\n\n[\n  \"+\"\n  \"-\"\n  \"*\"\n  \"/\"\n  \"%\"\n  \"||\"\n  \"&&\"\n  \"|\"\n  \"&\"\n  \"==\"\n  \"!=\"\n  \">\"\n  \">=\"\n  \"<=\"\n  \"<\"\n  \"<<\"\n  \">>\"\n  \"!\"\n  \"~\"\n  \"=\"\n  \"+=\"\n  \"-=\"\n  \"*=\"\n  \"/=\"\n  \"<<=\"\n  \">>=\"\n  \"&=\"\n  \"|=\"\n] @operator\n\n; Literals\n\n(number) @number\n\n(quoted_symbol) @string\n\n(wildcard_pattern [ \"*\" \"[\" \"]\" ] @character.special)\n\n(attributes) @character.special\n\n; Punctuation\n\n[ \"{\" \"}\" \"(\" \")\" ] @punctuation.bracket\n\n[\n  \":\"\n  \";\"\n] @punctuation.delimiter\n\n\">\" @punctuation.special\n\n; Comments\n\n(comment) @comment @spell\n",
	})
}
