//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_ql

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/ql.bin
var subsetBlobFS_ql embed.FS

func init() { registerSubsetEmbeddedBlob("ql.bin", subsetBlobFS_ql) }
