//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_tlaplus

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/tlaplus.bin
var subsetBlobFS_tlaplus embed.FS

func init() { registerSubsetEmbeddedBlob("tlaplus.bin", subsetBlobFS_tlaplus) }
