//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_agda

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/agda.bin
var subsetBlobFS_agda embed.FS

func init() { registerSubsetEmbeddedBlob("agda.bin", subsetBlobFS_agda) }
