//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_move

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/move.bin
var subsetBlobFS_move embed.FS

func init() { registerSubsetEmbeddedBlob("move.bin", subsetBlobFS_move) }
