//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_apex

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/apex.bin
var subsetBlobFS_apex embed.FS

func init() { registerSubsetEmbeddedBlob("apex.bin", subsetBlobFS_apex) }
