//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_groovy

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/groovy.bin
var subsetBlobFS_groovy embed.FS

func init() { registerSubsetEmbeddedBlob("groovy.bin", subsetBlobFS_groovy) }
