//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_linkerscript

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/linkerscript.bin
var subsetBlobFS_linkerscript embed.FS

func init() { registerSubsetEmbeddedBlob("linkerscript.bin", subsetBlobFS_linkerscript) }
