//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_python

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/python.bin
var subsetBlobFS_python embed.FS

func init() { registerSubsetEmbeddedBlob("python.bin", subsetBlobFS_python) }
