//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_meson

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/meson.bin
var subsetBlobFS_meson embed.FS

func init() { registerSubsetEmbeddedBlob("meson.bin", subsetBlobFS_meson) }
