//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_arduino

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/arduino.bin
var subsetBlobFS_arduino embed.FS

func init() { registerSubsetEmbeddedBlob("arduino.bin", subsetBlobFS_arduino) }
