//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_objc

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/objc.bin
var subsetBlobFS_objc embed.FS

func init() { registerSubsetEmbeddedBlob("objc.bin", subsetBlobFS_objc) }
