//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_hlsl

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/hlsl.bin
var subsetBlobFS_hlsl embed.FS

func init() { registerSubsetEmbeddedBlob("hlsl.bin", subsetBlobFS_hlsl) }
