//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_scheme

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/scheme.bin
var subsetBlobFS_scheme embed.FS

func init() { registerSubsetEmbeddedBlob("scheme.bin", subsetBlobFS_scheme) }
