//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_bass

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/bass.bin
var subsetBlobFS_bass embed.FS

func init() { registerSubsetEmbeddedBlob("bass.bin", subsetBlobFS_bass) }
