//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_capnp

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/capnp.bin
var subsetBlobFS_capnp embed.FS

func init() { registerSubsetEmbeddedBlob("capnp.bin", subsetBlobFS_capnp) }
