//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_http

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/http.bin
var subsetBlobFS_http embed.FS

func init() { registerSubsetEmbeddedBlob("http.bin", subsetBlobFS_http) }
