//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_matlab

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/matlab.bin
var subsetBlobFS_matlab embed.FS

func init() { registerSubsetEmbeddedBlob("matlab.bin", subsetBlobFS_matlab) }
