//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_devicetree

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/devicetree.bin
var subsetBlobFS_devicetree embed.FS

func init() { registerSubsetEmbeddedBlob("devicetree.bin", subsetBlobFS_devicetree) }
