//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_sql

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/sql.bin
var subsetBlobFS_sql embed.FS

func init() { registerSubsetEmbeddedBlob("sql.bin", subsetBlobFS_sql) }
