//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_gleam

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/gleam.bin
var subsetBlobFS_gleam embed.FS

func init() { registerSubsetEmbeddedBlob("gleam.bin", subsetBlobFS_gleam) }
