//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_norg

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/norg.bin
var subsetBlobFS_norg embed.FS

func init() { registerSubsetEmbeddedBlob("norg.bin", subsetBlobFS_norg) }
