//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_editorconfig

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/editorconfig.bin
var subsetBlobFS_editorconfig embed.FS

func init() { registerSubsetEmbeddedBlob("editorconfig.bin", subsetBlobFS_editorconfig) }
