//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_hack

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/hack.bin
var subsetBlobFS_hack embed.FS

func init() { registerSubsetEmbeddedBlob("hack.bin", subsetBlobFS_hack) }
