//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_enforce

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/enforce.bin
var subsetBlobFS_enforce embed.FS

func init() { registerSubsetEmbeddedBlob("enforce.bin", subsetBlobFS_enforce) }
