//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_teal

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/teal.bin
var subsetBlobFS_teal embed.FS

func init() { registerSubsetEmbeddedBlob("teal.bin", subsetBlobFS_teal) }
