//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_heex

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/heex.bin
var subsetBlobFS_heex embed.FS

func init() { registerSubsetEmbeddedBlob("heex.bin", subsetBlobFS_heex) }
