//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_puppet

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/puppet.bin
var subsetBlobFS_puppet embed.FS

func init() { registerSubsetEmbeddedBlob("puppet.bin", subsetBlobFS_puppet) }
