//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_mermaid

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/mermaid.bin
var subsetBlobFS_mermaid embed.FS

func init() { registerSubsetEmbeddedBlob("mermaid.bin", subsetBlobFS_mermaid) }
