//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_todotxt

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/todotxt.bin
var subsetBlobFS_todotxt embed.FS

func init() { registerSubsetEmbeddedBlob("todotxt.bin", subsetBlobFS_todotxt) }
