//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_git_rebase

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/git_rebase.bin
var subsetBlobFS_git_rebase embed.FS

func init() { registerSubsetEmbeddedBlob("git_rebase.bin", subsetBlobFS_git_rebase) }
