//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_comment

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/comment.bin
var subsetBlobFS_comment embed.FS

func init() { registerSubsetEmbeddedBlob("comment.bin", subsetBlobFS_comment) }
