//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_elm

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/elm.bin
var subsetBlobFS_elm embed.FS

func init() { registerSubsetEmbeddedBlob("elm.bin", subsetBlobFS_elm) }
