//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_jq

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/jq.bin
var subsetBlobFS_jq embed.FS

func init() { registerSubsetEmbeddedBlob("jq.bin", subsetBlobFS_jq) }
