//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_nickel

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/nickel.bin
var subsetBlobFS_nickel embed.FS

func init() { registerSubsetEmbeddedBlob("nickel.bin", subsetBlobFS_nickel) }
