//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_godot_resource

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/godot_resource.bin
var subsetBlobFS_godot_resource embed.FS

func init() { registerSubsetEmbeddedBlob("godot_resource.bin", subsetBlobFS_godot_resource) }
