//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_tsx

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/tsx.bin
var subsetBlobFS_tsx embed.FS

func init() { registerSubsetEmbeddedBlob("tsx.bin", subsetBlobFS_tsx) }
