//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_rust

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/rust.bin
var subsetBlobFS_rust embed.FS

func init() { registerSubsetEmbeddedBlob("rust.bin", subsetBlobFS_rust) }
