//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_smithy

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/smithy.bin
var subsetBlobFS_smithy embed.FS

func init() { registerSubsetEmbeddedBlob("smithy.bin", subsetBlobFS_smithy) }
