//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_disassembly

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/disassembly.bin
var subsetBlobFS_disassembly embed.FS

func init() { registerSubsetEmbeddedBlob("disassembly.bin", subsetBlobFS_disassembly) }
