//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_liquid

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/liquid.bin
var subsetBlobFS_liquid embed.FS

func init() { registerSubsetEmbeddedBlob("liquid.bin", subsetBlobFS_liquid) }
