//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_facility

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/facility.bin
var subsetBlobFS_facility embed.FS

func init() { registerSubsetEmbeddedBlob("facility.bin", subsetBlobFS_facility) }
