//go:build grammar_subset && grammar_subset_fortran

package grammars

func init() {
	Register(LangEntry{
		Name:           "fortran",
		Extensions:     []string{".f", ".f90", ".f95", ".f03", ".f08"},
		Language:       FortranLanguage,
		GrammarSource:  GrammarSourceTS2GoBlob,
		HighlightQuery: "(identifier) @variable\n(string_literal) @string\n(number_literal) @number\n(boolean_literal) @boolean\n(comment) @comment\n\n[\n (intrinsic_type)\n \"allocatable\"\n \"attributes\"\n \"device\"\n \"dimension\"\n \"endtype\"\n \"global\"\n \"grid_global\"\n \"host\"\n \"import\"\n \"in\"\n \"inout\"\n \"intent\"\n \"optional\"\n \"out\"\n \"pointer\"\n \"type\"\n \"value\"\n ] @type\n\n[\n \"contains\"\n \"private\"\n \"public\"\n ] @include\n\n[\n (none)\n \"implicit\"\n ] @attribute\n\n[\n \"endfunction\"\n \"endprogram\"\n \"endsubroutine\"\n \"function\"\n \"procedure\"\n \"subroutine\"\n ] @keyword.function\n\n[\n (default)\n (procedure_qualifier)\n \"abstract\"\n \"bind\"\n \"call\"\n \"class\"\n \"continue\"\n \"cycle\"\n \"endenum\"\n \"endinterface\"\n \"endmodule\"\n \"endprocedure\"\n \"endprogram\"\n \"endsubmodule\"\n \"enum\"\n \"enumerator\"\n \"equivalence\"\n \"exit\"\n \"extends\"\n \"format\"\n \"goto\"\n \"include\"\n \"interface\"\n \"intrinsic\"\n \"non_intrinsic\"\n \"module\"\n \"namelist\"\n \"only\"\n \"parameter\"\n \"print\"\n \"procedure\"\n \"program\"\n \"read\"\n \"stop\"\n \"submodule\"\n \"use\"\n \"write\"\n ] @keyword\n\n\"return\" @keyword.return\n\n[\n \"else\"\n \"elseif\"\n \"elsewhere\"\n \"endif\"\n \"endwhere\"\n \"if\"\n \"then\"\n \"where\"\n ] @conditional\n\n[\n \"do\"\n \"enddo\"\n \"forall\"\n \"while\"\n ] @repeat\n\n[\n \"*\"\n \"+\"\n \"-\"\n \"/\"\n \"=\"\n \"<\"\n \">\"\n \"<=\"\n \">=\"\n \"==\"\n \"/=\"\n ] @operator\n\n[\n \"\\\\.and\\\\.\"\n \"\\\\.or\\\\.\"\n \"\\\\.lt\\\\.\"\n \"\\\\.gt\\\\.\"\n \"\\\\.ge\\\\.\"\n \"\\\\.le\\\\.\"\n \"\\\\.eq\\\\.\"\n \"\\\\.eqv\\\\.\"\n \"\\\\.neqv\\\\.\"\n ] @keyword.operator\n\n;; Brackets\n[\n \"(\"\n \")\"\n \"[\"\n \"]\"\n \"<<<\"\n \">>>\"\n ] @punctuation.bracket\n\n;; Delimiter\n[\n \"::\"\n \",\"\n \"%\"\n ] @punctuation.delimiter\n\n(parameters\n  (identifier) @parameter)\n\n(program_statement\n  (name) @namespace)\n\n(module_statement\n  (name) @namespace)\n\n(submodule_statement\n  (module_name) (name) @namespace)\n\n(function_statement\n  (name) @function)\n\n(subroutine_statement\n  (name) @function)\n\n(module_procedure_statement\n  (name) @function)\n\n(end_program_statement\n  (name) @namespace)\n\n(end_module_statement\n  (name) @namespace)\n\n(end_submodule_statement\n  (name) @namespace)\n\n(end_function_statement\n  (name) @function)\n\n(end_subroutine_statement\n  (name) @function)\n\n(end_module_procedure_statement\n  (name) @function)\n\n(subroutine_call\n  (identifier) @function)\n\n(keyword_argument\n  name: (identifier) @keyword)\n\n(derived_type_member_expression\n  (type_member) @property)\n\n(call_expression\n  (identifier) @function.call)\n",
	})
}
