//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_hare

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/hare.bin
var subsetBlobFS_hare embed.FS

func init() { registerSubsetEmbeddedBlob("hare.bin", subsetBlobFS_hare) }
