//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_foam

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/foam.bin
var subsetBlobFS_foam embed.FS

func init() { registerSubsetEmbeddedBlob("foam.bin", subsetBlobFS_foam) }
