//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_kconfig

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/kconfig.bin
var subsetBlobFS_kconfig embed.FS

func init() { registerSubsetEmbeddedBlob("kconfig.bin", subsetBlobFS_kconfig) }
