//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_vhdl

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/vhdl.bin
var subsetBlobFS_vhdl embed.FS

func init() { registerSubsetEmbeddedBlob("vhdl.bin", subsetBlobFS_vhdl) }
