//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_clojure

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/clojure.bin
var subsetBlobFS_clojure embed.FS

func init() { registerSubsetEmbeddedBlob("clojure.bin", subsetBlobFS_clojure) }
