//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_blade

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/blade.bin
var subsetBlobFS_blade embed.FS

func init() { registerSubsetEmbeddedBlob("blade.bin", subsetBlobFS_blade) }
