//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_forth

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/forth.bin
var subsetBlobFS_forth embed.FS

func init() { registerSubsetEmbeddedBlob("forth.bin", subsetBlobFS_forth) }
