//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_doxygen

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/doxygen.bin
var subsetBlobFS_doxygen embed.FS

func init() { registerSubsetEmbeddedBlob("doxygen.bin", subsetBlobFS_doxygen) }
