//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_faust

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/faust.bin
var subsetBlobFS_faust embed.FS

func init() { registerSubsetEmbeddedBlob("faust.bin", subsetBlobFS_faust) }
