//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_twig

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/twig.bin
var subsetBlobFS_twig embed.FS

func init() { registerSubsetEmbeddedBlob("twig.bin", subsetBlobFS_twig) }
