//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_swift

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/swift.bin
var subsetBlobFS_swift embed.FS

func init() { registerSubsetEmbeddedBlob("swift.bin", subsetBlobFS_swift) }
