//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_embedded_template

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/embedded_template.bin
var subsetBlobFS_embedded_template embed.FS

func init() { registerSubsetEmbeddedBlob("embedded_template.bin", subsetBlobFS_embedded_template) }
