//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_textproto

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/textproto.bin
var subsetBlobFS_textproto embed.FS

func init() { registerSubsetEmbeddedBlob("textproto.bin", subsetBlobFS_textproto) }
