//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_ebnf

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/ebnf.bin
var subsetBlobFS_ebnf embed.FS

func init() { registerSubsetEmbeddedBlob("ebnf.bin", subsetBlobFS_ebnf) }
