//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_gdscript

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/gdscript.bin
var subsetBlobFS_gdscript embed.FS

func init() { registerSubsetEmbeddedBlob("gdscript.bin", subsetBlobFS_gdscript) }
