//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_wat

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/wat.bin
var subsetBlobFS_wat embed.FS

func init() { registerSubsetEmbeddedBlob("wat.bin", subsetBlobFS_wat) }
