//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_yaml

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/yaml.bin
var subsetBlobFS_yaml embed.FS

func init() { registerSubsetEmbeddedBlob("yaml.bin", subsetBlobFS_yaml) }
