//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_erlang

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/erlang.bin
var subsetBlobFS_erlang embed.FS

func init() { registerSubsetEmbeddedBlob("erlang.bin", subsetBlobFS_erlang) }
