//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_jsdoc

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/jsdoc.bin
var subsetBlobFS_jsdoc embed.FS

func init() { registerSubsetEmbeddedBlob("jsdoc.bin", subsetBlobFS_jsdoc) }
