//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_solidity

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/solidity.bin
var subsetBlobFS_solidity embed.FS

func init() { registerSubsetEmbeddedBlob("solidity.bin", subsetBlobFS_solidity) }
