//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_rego

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/rego.bin
var subsetBlobFS_rego embed.FS

func init() { registerSubsetEmbeddedBlob("rego.bin", subsetBlobFS_rego) }
