//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_ninja

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/ninja.bin
var subsetBlobFS_ninja embed.FS

func init() { registerSubsetEmbeddedBlob("ninja.bin", subsetBlobFS_ninja) }
