//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_xml

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/xml.bin
var subsetBlobFS_xml embed.FS

func init() { registerSubsetEmbeddedBlob("xml.bin", subsetBlobFS_xml) }
