//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_fennel

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/fennel.bin
var subsetBlobFS_fennel embed.FS

func init() { registerSubsetEmbeddedBlob("fennel.bin", subsetBlobFS_fennel) }
