//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_astro

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/astro.bin
var subsetBlobFS_astro embed.FS

func init() { registerSubsetEmbeddedBlob("astro.bin", subsetBlobFS_astro) }
