//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_bicep

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/bicep.bin
var subsetBlobFS_bicep embed.FS

func init() { registerSubsetEmbeddedBlob("bicep.bin", subsetBlobFS_bicep) }
