//go:build grammar_subset && grammar_subset_nix

package grammars

func init() {
	Register(LangEntry{
		Name:           "nix",
		Extensions:     []string{".nix"},
		Language:       NixLanguage,
		GrammarSource:  GrammarSourceTS2GoBlob,
		HighlightQuery: "(comment) @comment\n\n[\n  \"if\"\n  \"then\"\n  \"else\"\n  \"let\"\n  \"inherit\"\n  \"in\"\n  \"rec\"\n  \"with\"\n  \"assert\"\n  \"or\"\n] @keyword\n\n((identifier) @variable.builtin\n (#match? @variable.builtin \"^(__currentSystem|__currentTime|__langVersion|__nixPath|__nixVersion|__storeDir|builtins|false|null|true)$\")\n (#is-not? local))\n\n((identifier) @function.builtin\n (#match? @function.builtin \"^(__add|__addErrorContext|__all|__any|__appendContext|__attrNames|__attrValues|__bitAnd|__bitOr|__bitXor|__catAttrs|__ceil|__compareVersions|__concatLists|__concatMap|__concatStringsSep|__deepSeq|__div|__elem|__elemAt|__fetchurl|__filter|__filterSource|__findFile|__flakeRefToString|__floor|__foldl'|__fromJSON|__functionArgs|__genList|__genericClosure|__getAttr|__getContext|__getEnv|__getFlake|__groupBy|__hasAttr|__hasContext|__hashFile|__hashString|__head|__intersectAttrs|__isAttrs|__isBool|__isFloat|__isFunction|__isInt|__isList|__isPath|__isString|__length|__lessThan|__listToAttrs|__mapAttrs|__match|__mul|__parseDrvName|__parseFlakeRef|__partition|__path|__pathExists|__readDir|__readFile|__readFileType|__replaceStrings|__seq|__sort|__split|__splitVersion|__storePath|__stringLength|__sub|__substring|__tail|__toFile|__toJSON|__toPath|__toXML|__trace|__traceVerbose|__tryEval|__typeOf|__unsafeDiscardOutputDependency|__unsafeDiscardStringContext|__unsafeGetAttrPos|__zipAttrsWith|abort|baseNameOf|break|derivation|derivationStrict|dirOf|fetchGit|fetchMercurial|fetchTarball|fetchTree|fromTOML|import|isNull|map|placeholder|removeAttrs|scopedImport|throw|toString)$\")\n (#is-not? local))\n\n[\n  (integer_expression)\n  (float_expression)\n] @number\n\n(escape_sequence) @escape\n(dollar_escape) @escape\n\n(function_expression\n  universal: (identifier) @variable.parameter\n)\n\n(formal\n  name: (identifier) @variable.parameter\n  \"?\"? @punctuation.delimiter)\n\n(select_expression\n  attrpath: (attrpath (identifier)) @property)\n\n(apply_expression\n  function: [\n    (variable_expression (identifier)) @function\n    (select_expression\n      attrpath: (attrpath\n        attr: (identifier) @function .))])\n\n(unary_expression\n  operator: _ @operator)\n\n(binary_expression\n  operator: _ @operator)\n\n(variable_expression (identifier) @variable)\n\n(binding\n  attrpath: (attrpath (identifier)) @property)\n\n(identifier) @property\n\n(inherit_from attrs: (inherited_attrs attr: (identifier) @property) )\n\n[\n  \";\"\n  \".\"\n  \",\"\n  \"=\"\n] @punctuation.delimiter\n\n[\n  \"(\"\n  \")\"\n  \"[\"\n  \"]\"\n  \"{\"\n  \"}\"\n] @punctuation.bracket\n\n(identifier) @variable\n\n[\n  (string_expression)\n  (indented_string_expression)\n] @string\n\n[\n  (path_expression)\n  (hpath_expression)\n  (spath_expression)\n] @string.special.path\n\n(uri_expression) @string.special.uri\n\n(interpolation\n  \"${\" @punctuation.special\n  (_) @embedded\n  \"}\" @punctuation.special)\n",
	})
}
