//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_nginx

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/nginx.bin
var subsetBlobFS_nginx embed.FS

func init() { registerSubsetEmbeddedBlob("nginx.bin", subsetBlobFS_nginx) }
