//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_c

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/c.bin
var subsetBlobFS_c embed.FS

func init() { registerSubsetEmbeddedBlob("c.bin", subsetBlobFS_c) }
