//go:build grammar_subset && grammar_subset_pkl

package grammars

func init() {
	Register(LangEntry{
		Name:           "pkl",
		Extensions:     []string{".pkl"},
		Language:       PklLanguage,
		GrammarSource:  GrammarSourceTS2GoBlob,
		HighlightQuery: "; Types\n\n(clazz (identifier) @type)\n(typeAlias (identifier) @type)\n((identifier) @type\n (#match? @type \"^[A-Z]\"))\n\n(typeArgumentList\n  \"<\" @punctuation.bracket\n  \">\" @punctuation.bracket)\n\n; Method definitions\n\n(classMethod (methodHeader (identifier)) @function.method)\n(objectMethod (methodHeader (identifier)) @function.method)\n\n; Identifiers\n\n(classProperty (identifier) @property)\n(objectProperty (identifier) @property)\n\n(parameterList (typedIdentifier (identifier) @variable.parameter))\n(objectBodyParameters (typedIdentifier (identifier) @variable.parameter))\n\n(identifier) @variable\n\n; Literals\n\n(stringConstant) @string\n(slStringLiteralExpr) @string\n(mlStringLiteralExpr) @string\n\n(escapeSequence) @escape\n\n(intLiteralExpr) @number\n(floatLiteralExpr) @number\n\n(stringInterpolation\n  \"\\\\(\" @punctuation.special\n  \")\" @punctuation.special) @embedded\n\n(stringInterpolation\n \"\\\\#(\" @punctuation.special\n \")\" @punctuation.special) @embedded\n\n(stringInterpolation\n  \"\\\\##(\" @punctuation.special\n  \")\" @punctuation.special) @embedded\n\n(lineComment) @comment\n(blockComment) @comment\n(docComment) @comment\n(shebangComment) @comment\n\n; Operators\n\n\"??\" @operator\n\"@\"  @operator\n\"=\"  @operator\n\"<\"  @operator\n\">\"  @operator\n\"!\"  @operator\n\"==\" @operator\n\"!=\" @operator\n\"<=\" @operator\n\">=\" @operator\n\"&&\" @operator\n\"||\" @operator\n\"+\"  @operator\n\"-\"  @operator\n\"**\" @operator\n\"*\"  @operator\n\"/\"  @operator\n\"~/\" @operator\n\"%\"  @operator\n\"|>\" @operator\n\n\",\" @punctuation.delimiter\n\":\" @punctuation.delimiter\n\".\" @punctuation.delimiter\n\"?.\" @punctuation.delimiter\n\n\"(\" @punctuation.bracket\n\")\" @punctuation.bracket\n\"[\" @punctuation.bracket\n\"]\" @punctuation.bracket\n\"{\" @punctuation.bracket\n\"}\" @punctuation.bracket\n\n; Keywords\n\n\"abstract\" @keyword\n\"amends\" @keyword\n\"as\" @keyword\n\"class\" @keyword\n\"else\" @keyword\n\"extends\" @keyword\n\"external\" @keyword\n(falseLiteralExpr) @constant.builtin\n\"for\" @keyword\n\"function\" @keyword\n\"hidden\" @keyword\n\"if\" @keyword\n(importExpr \"import\" @function.method.builtin)\n(importExpr \"import*\" @function.method.builtin)\n\"import\" @keyword\n\"import*\" @keyword\n\"in\" @keyword\n\"is\" @keyword\n\"let\" @keyword\n\"local\" @keyword\n(moduleExpr \"module\" @type.builtin)\n\"module\" @keyword\n\"new\" @keyword\n(nullLiteralExpr) @constant.builtin\n\"open\" @keyword\n\"out\" @keyword\n(outerExpr) @variable.builtin\n\"read\" @function.method.builtin\n\"read?\" @function.method.builtin\n\"read*\" @function.method.builtin\n\"super\" @variable.builtin\n(thisExpr) @variable.builtin\n\"throw\" @function.method.builtin\n\"trace\" @function.method.builtin\n(trueLiteralExpr) @constant.builtin\n\"typealias\" @keyword\n\"when\" @keyword\n",
	})
}
