//go:build grammar_subset && grammar_subset_firrtl

package grammars

func init() {
	Register(LangEntry{
		Name:           "firrtl",
		Extensions:     []string{".fir"},
		Language:       FirrtlLanguage,
		GrammarSource:  GrammarSourceTS2GoBlob,
		HighlightQuery: "; Namespaces\n\n(circuit (identifier) @namespace)\n\n(module (identifier) @namespace)\n\n; Types\n\n((identifier) @type\n  (#lua-match? @type \"^[A-Z][A-Za-z0-9_$]*$\"))\n\n; Keywords\n\n[\n  \"circuit\"\n  \"module\"\n  \"extmodule\"\n\n  \"flip\"\n  \"parameter\"\n  \"reset\"\n  \"wire\"\n\n  \"cmem\"\n  \"smem\"\n  \"mem\"\n\n  \"reg\"\n  \"with\"\n  \"mport\"\n  \"inst\"\n  \"of\"\n  \"node\"\n  \"is\"\n  \"invalid\"\n  \"skip\"\n\n  \"infer\"\n  \"read\"\n  \"write\"\n  \"rdwr\"\n] @keyword\n\n[\n  \"defname\"\n] @keyword.variable\n\n; Qualifiers\n\n(qualifier) @type.qualifier\n\n; Storageclasses\n\n[\n  \"input\"\n  \"output\"\n] @storageclass\n\n; Conditionals\n\n[\n  \"when\"\n  \"else\"\n] @conditional\n\n; Annotations\n\n(info) @annotation\n\n; Builtins\n\n[\n  \"stop\"\n  \"printf\"\n  \"assert\"\n  \"assume\"\n  \"cover\"\n  \"attach\"\n  \"mux\"\n  \"validif\"\n] @function.builtin\n\n[\n  \"UInt\"\n  \"SInt\"\n  \"Analog\"\n  \"Fixed\"\n  \"Clock\"\n  \"AsyncReset\"\n  \"Reset\"\n] @type.builtin\n\n; Fields\n\n[\n  \"data-type\"\n  \"depth\"\n  \"read-latency\"\n  \"write-latency\"\n  \"read-under-write\"\n  \"reader\"\n  \"writer\"\n  \"readwriter\"\n] @field.builtin\n\n((field_id) @field\n  (#set! \"priority\" 105))\n\n(port (identifier) @field)\n\n(wire (identifier) @field)\n\n(cmem (identifier) @field)\n\n(smem (identifier) @field)\n\n(memory (identifier) @field)\n\n(register (identifier) @field)\n\n; Parameters\n\n(primitive_operation (identifier) @parameter)\n\n(mux (identifier) @parameter)\n(printf (identifier) @parameter)\n(reset (identifier) @parameter)\n(stop (identifier) @parameter)\n\n; Variables\n\n(identifier) @variable\n\n; Operators\n\n(primop) @keyword.operator\n\n[\n  \"+\"\n  \"-\"\n  \"=\"\n  \"=>\"\n  \"<=\"\n  \"<-\"\n] @operator\n\n; Literals\n\n[\n  (uint)\n  (number)\n] @number\n\n(number_str) @string.special\n\n(double) @float\n\n(string) @string\n\n(escape_sequence) @string.escape\n\n[\n  \"old\"\n  \"new\"\n  \"undefined\"\n] @constant.builtin\n\n; Punctuation\n\n[ \"{\" \"}\" ] @punctuation.bracket\n\n[ \"[\" \"]\" ] @punctuation.bracket\n\n[ \"<\" \">\" ] @punctuation.bracket\n\n[ \"(\" \")\" ] @punctuation.bracket\n\n[\n  \",\"\n  \".\"\n  \":\"\n] @punctuation.delimiter\n\n; Comments\n\n(comment) @comment @spell\n\n[\"=>\" \"<=\" \"=\"] @operator\n\n; Error\n(ERROR) @error\n",
	})
}
