//go:build grammar_subset && grammar_subset_enforce

package grammars

func init() {
	Register(LangEntry{
		Name:           "enforce",
		Extensions:     []string{".enf"},
		Language:       EnforceLanguage,
		GrammarSource:  GrammarSourceTS2GoBlob,
		HighlightQuery: "[\n  (comment_line)\n  (comment_block)\n] @comment @spell\n\n[\n  (doc_line)\n  (doc_block)\n] @comment.documentation @spell\n\n(literal_bool) @boolean\n\n(literal_int) @number\n\n(literal_float) @number.float\n\n(literal_string) @string\n\n(escape_sequence) @string.escape\n\n(identifier) @variable\n\n(formal_parameter\n  name: (identifier) @variable.parameter)\n\n((identifier) @constant\n  (#lua-match? @constant \"^[A-Z_][A-Z%d_]+$\"))\n\n; Preprocessor directives\n[\n  (include)\n  (define)\n  (ifdef)\n  (ifndef)\n  (else)\n  (endif)\n] @keyword.directive\n\n(preproc_const) @constant.macro\n\n; Constant fields\n(decl_field\n  ((field_modifier) @_modifier\n    (#eq? @_modifier \"const\"))\n  type: (_)\n  name: (identifier) @constant)\n\n(enum_member\n  name: (identifier) @constant)\n\n[\n  \"+\"\n  \"-\"\n  \"*\"\n  \"/\"\n  \"%\"\n  \"^\"\n  \"++\"\n  \"--\"\n  \"=\"\n  \"+=\"\n  \"-=\"\n  \"*=\"\n  \"/=\"\n  \"&=\"\n  \"^=\"\n  \"|=\"\n  \"<<=\"\n  \">>=\"\n  \"<\"\n  \"<=\"\n  \">=\"\n  \">\"\n  \"==\"\n  \"!=\"\n  \"!\"\n  \"&&\"\n  \"||\"\n  \">>\"\n  \"<<\"\n  \"&\"\n  \"|\"\n  \"^\"\n  \"~\"\n] @operator\n\n[\n  \"(\"\n  \")\"\n  \"[\"\n  \"]\"\n  \"{\"\n  \"}\"\n] @punctuation.bracket\n\n; TODO: <> in decl_class\n(types\n  [\n    \"<\"\n    \">\"\n  ] @punctuation.bracket)\n\n[\n  \",\"\n  \".\"\n  \":\"\n  \";\"\n] @punctuation.delimiter\n\n[\n  \"default\"\n  \"extends\"\n] @keyword\n\n[\n  \"new\"\n  \"delete\"\n] @keyword.operator\n\n\"return\" @keyword.return\n\n[\n  \"if\"\n  \"else\"\n  \"switch\"\n  \"case\"\n] @keyword.conditional\n\n[\n  \"while\"\n  \"for\"\n  \"foreach\"\n  \"continue\"\n  \"break\"\n] @keyword.repeat\n\n[\n  \"enum\"\n  \"class\"\n  \"typedef\"\n] @keyword.type\n\n[\n  (variable_modifier)\n  (method_modifier)\n  (class_modifier)\n  (field_modifier)\n  (formal_parameter_modifier)\n] @keyword.modifier\n\n\"ref\" @type\n\n(decl_class\n  typename: (identifier) @type)\n\n(decl_class\n  superclass: (superclass\n    typename: (identifier) @type))\n\n(decl_enum\n  typename: (identifier) @type)\n\n(type_identifier\n  (identifier) @type)\n\n[\n  \"auto\"\n  (type_primitive)\n] @type.builtin\n\n[\n  (super)\n  (this)\n] @variable.builtin\n\n(literal_null) @constant.builtin\n\n(decl_method\n  name: (identifier) @function.method)\n\n(invokation\n  invoked: (identifier) @function.method.call)\n\n; Constructor and deconstructor (function with same name of the class)\n(decl_class\n  typename: (identifier) @_classname\n  body: (class_body\n    (decl_method\n      name: (identifier) @constructor\n      (#eq? @constructor @_classname))))\n",
	})
}
