//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_glsl

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/glsl.bin
var subsetBlobFS_glsl embed.FS

func init() { registerSubsetEmbeddedBlob("glsl.bin", subsetBlobFS_glsl) }
