//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_zig

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/zig.bin
var subsetBlobFS_zig embed.FS

func init() { registerSubsetEmbeddedBlob("zig.bin", subsetBlobFS_zig) }
