//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_robot

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/robot.bin
var subsetBlobFS_robot embed.FS

func init() { registerSubsetEmbeddedBlob("robot.bin", subsetBlobFS_robot) }
