//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_ini

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/ini.bin
var subsetBlobFS_ini embed.FS

func init() { registerSubsetEmbeddedBlob("ini.bin", subsetBlobFS_ini) }
