//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_ocaml

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/ocaml.bin
var subsetBlobFS_ocaml embed.FS

func init() { registerSubsetEmbeddedBlob("ocaml.bin", subsetBlobFS_ocaml) }
