//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_typst

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/typst.bin
var subsetBlobFS_typst embed.FS

func init() { registerSubsetEmbeddedBlob("typst.bin", subsetBlobFS_typst) }
