//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_powershell

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/powershell.bin
var subsetBlobFS_powershell embed.FS

func init() { registerSubsetEmbeddedBlob("powershell.bin", subsetBlobFS_powershell) }
