//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_elisp

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/elisp.bin
var subsetBlobFS_elisp embed.FS

func init() { registerSubsetEmbeddedBlob("elisp.bin", subsetBlobFS_elisp) }
