//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_just

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/just.bin
var subsetBlobFS_just embed.FS

func init() { registerSubsetEmbeddedBlob("just.bin", subsetBlobFS_just) }
