//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_authzed

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/authzed.bin
var subsetBlobFS_authzed embed.FS

func init() { registerSubsetEmbeddedBlob("authzed.bin", subsetBlobFS_authzed) }
