//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_graphql

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/graphql.bin
var subsetBlobFS_graphql embed.FS

func init() { registerSubsetEmbeddedBlob("graphql.bin", subsetBlobFS_graphql) }
