//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_julia

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/julia.bin
var subsetBlobFS_julia embed.FS

func init() { registerSubsetEmbeddedBlob("julia.bin", subsetBlobFS_julia) }
