//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_cmake

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/cmake.bin
var subsetBlobFS_cmake embed.FS

func init() { registerSubsetEmbeddedBlob("cmake.bin", subsetBlobFS_cmake) }
