//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_lua

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/lua.bin
var subsetBlobFS_lua embed.FS

func init() { registerSubsetEmbeddedBlob("lua.bin", subsetBlobFS_lua) }
