//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_uxntal

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/uxntal.bin
var subsetBlobFS_uxntal embed.FS

func init() { registerSubsetEmbeddedBlob("uxntal.bin", subsetBlobFS_uxntal) }
