//go:build grammar_subset && grammar_subset_ruby

package grammars

func init() {
	Register(LangEntry{
		Name:           "ruby",
		Extensions:     []string{".rb"},
		Language:       RubyLanguage,
		GrammarSource:  GrammarSourceTS2GoBlob,
		HighlightQuery: "(identifier) @variable\n\n((identifier) @function.method\n (#is-not? local))\n\n[\n  \"alias\"\n  \"and\"\n  \"begin\"\n  \"break\"\n  \"case\"\n  \"class\"\n  \"def\"\n  \"do\"\n  \"else\"\n  \"elsif\"\n  \"end\"\n  \"ensure\"\n  \"for\"\n  \"if\"\n  \"in\"\n  \"module\"\n  \"next\"\n  \"or\"\n  \"rescue\"\n  \"retry\"\n  \"return\"\n  \"then\"\n  \"unless\"\n  \"until\"\n  \"when\"\n  \"while\"\n  \"yield\"\n] @keyword\n\n((identifier) @keyword\n (#match? @keyword \"^(private|protected|public)$\"))\n\n(constant) @constructor\n\n; Function calls\n\n\"defined?\" @function.method.builtin\n\n(call\n  method: [(identifier) (constant)] @function.method)\n\n((identifier) @function.method.builtin\n (#eq? @function.method.builtin \"require\"))\n\n; Function definitions\n\n(alias (identifier) @function.method)\n(setter (identifier) @function.method)\n(method name: [(identifier) (constant)] @function.method)\n(singleton_method name: [(identifier) (constant)] @function.method)\n\n; Identifiers\n\n[\n  (class_variable)\n  (instance_variable)\n] @property\n\n((identifier) @constant.builtin\n (#match? @constant.builtin \"^__(FILE|LINE|ENCODING)__$\"))\n\n(file) @constant.builtin\n(line) @constant.builtin\n(encoding) @constant.builtin\n\n(hash_splat_nil\n  \"**\" @operator) @constant.builtin\n\n((constant) @constant\n (#match? @constant \"^[A-Z\\\\d_]+$\"))\n\n[\n  (self)\n  (super)\n] @variable.builtin\n\n(block_parameter (identifier) @variable.parameter)\n(block_parameters (identifier) @variable.parameter)\n(destructured_parameter (identifier) @variable.parameter)\n(hash_splat_parameter (identifier) @variable.parameter)\n(lambda_parameters (identifier) @variable.parameter)\n(method_parameters (identifier) @variable.parameter)\n(splat_parameter (identifier) @variable.parameter)\n\n(keyword_parameter name: (identifier) @variable.parameter)\n(optional_parameter name: (identifier) @variable.parameter)\n\n; Literals\n\n[\n  (string)\n  (bare_string)\n  (subshell)\n  (heredoc_body)\n  (heredoc_beginning)\n] @string\n\n[\n  (simple_symbol)\n  (delimited_symbol)\n  (hash_key_symbol)\n  (bare_symbol)\n] @string.special.symbol\n\n(regex) @string.special.regex\n(escape_sequence) @escape\n\n[\n  (integer)\n  (float)\n] @number\n\n[\n  (nil)\n  (true)\n  (false)\n] @constant.builtin\n\n(interpolation\n  \"#{\" @punctuation.special\n  \"}\" @punctuation.special) @embedded\n\n(comment) @comment\n\n; Operators\n\n[\n\"=\"\n\"=>\"\n\"->\"\n] @operator\n\n[\n  \",\"\n  \";\"\n  \".\"\n] @punctuation.delimiter\n\n[\n  \"(\"\n  \")\"\n  \"[\"\n  \"]\"\n  \"{\"\n  \"}\"\n  \"%w(\"\n  \"%i(\"\n] @punctuation.bracket\n",
	})
}
