//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_luau

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/luau.bin
var subsetBlobFS_luau embed.FS

func init() { registerSubsetEmbeddedBlob("luau.bin", subsetBlobFS_luau) }
