//go:build grammar_subset && grammar_subset_java

package grammars

func init() {
	Register(LangEntry{
		Name:           "java",
		Extensions:     []string{".java"},
		Language:       JavaLanguage,
		GrammarSource:  GrammarSourceTS2GoBlob,
		HighlightQuery: "; Variables\n\n(identifier) @variable\n\n; Methods\n\n(method_declaration\n  name: (identifier) @function.method)\n(method_invocation\n  name: (identifier) @function.method)\n(super) @function.builtin\n\n; Annotations\n\n(annotation\n  name: (identifier) @attribute)\n(marker_annotation\n  name: (identifier) @attribute)\n\n\"@\" @operator\n\n; Types\n\n(type_identifier) @type\n\n(interface_declaration\n  name: (identifier) @type)\n(class_declaration\n  name: (identifier) @type)\n(enum_declaration\n  name: (identifier) @type)\n\n((field_access\n  object: (identifier) @type)\n (#match? @type \"^[A-Z]\"))\n((scoped_identifier\n  scope: (identifier) @type)\n (#match? @type \"^[A-Z]\"))\n((method_invocation\n  object: (identifier) @type)\n (#match? @type \"^[A-Z]\"))\n((method_reference\n  . (identifier) @type)\n (#match? @type \"^[A-Z]\"))\n\n(constructor_declaration\n  name: (identifier) @type)\n\n[\n  (boolean_type)\n  (integral_type)\n  (floating_point_type)\n  (floating_point_type)\n  (void_type)\n] @type.builtin\n\n; Constants\n\n((identifier) @constant\n (#match? @constant \"^_*[A-Z][A-Z\\\\d_]+$\"))\n\n; Builtins\n\n(this) @variable.builtin\n\n; Literals\n\n[\n  (hex_integer_literal)\n  (decimal_integer_literal)\n  (octal_integer_literal)\n  (decimal_floating_point_literal)\n  (hex_floating_point_literal)\n] @number\n\n[\n  (character_literal)\n  (string_literal)\n] @string\n(escape_sequence) @string.escape\n\n[\n  (true)\n  (false)\n  (null_literal)\n] @constant.builtin\n\n[\n  (line_comment)\n  (block_comment)\n] @comment\n\n; Keywords\n\n[\n  \"abstract\"\n  \"assert\"\n  \"break\"\n  \"case\"\n  \"catch\"\n  \"class\"\n  \"continue\"\n  \"default\"\n  \"do\"\n  \"else\"\n  \"enum\"\n  \"exports\"\n  \"extends\"\n  \"final\"\n  \"finally\"\n  \"for\"\n  \"if\"\n  \"implements\"\n  \"import\"\n  \"instanceof\"\n  \"interface\"\n  \"module\"\n  \"native\"\n  \"new\"\n  \"non-sealed\"\n  \"open\"\n  \"opens\"\n  \"package\"\n  \"permits\"\n  \"private\"\n  \"protected\"\n  \"provides\"\n  \"public\"\n  \"requires\"\n  \"record\"\n  \"return\"\n  \"sealed\"\n  \"static\"\n  \"strictfp\"\n  \"switch\"\n  \"synchronized\"\n  \"throw\"\n  \"throws\"\n  \"to\"\n  \"transient\"\n  \"transitive\"\n  \"try\"\n  \"uses\"\n  \"volatile\"\n  \"when\"\n  \"while\"\n  \"with\"\n  \"yield\"\n] @keyword\n",
	})
}
