//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_pug

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/pug.bin
var subsetBlobFS_pug embed.FS

func init() { registerSubsetEmbeddedBlob("pug.bin", subsetBlobFS_pug) }
