//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_cpon

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/cpon.bin
var subsetBlobFS_cpon embed.FS

func init() { registerSubsetEmbeddedBlob("cpon.bin", subsetBlobFS_cpon) }
