//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_javascript

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/javascript.bin
var subsetBlobFS_javascript embed.FS

func init() { registerSubsetEmbeddedBlob("javascript.bin", subsetBlobFS_javascript) }
