//go:build grammar_subset && grammar_subset_powershell

package grammars

func init() {
	Register(LangEntry{
		Name:           "powershell",
		Extensions:     []string{".ps1", ".psm1", ".psd1"},
		Language:       PowershellLanguage,
		GrammarSource:  GrammarSourceTS2GoBlob,
		HighlightQuery: "\"param\" @keyword\n\"dynamicparam\" @keyword\n\"begin\" @keyword\n\"process\" @keyword\n\"end\" @keyword\n\"if\" @keyword\n\"elseif\" @keyword\n\"else\" @keyword\n\"switch\" @keyword\n\"foreach\" @keyword\n\"for\" @keyword\n\"while\" @keyword\n\"do\" @keyword\n\"until\" @keyword\n\"function\" @keyword\n\"filter\" @keyword\n\"workflow\" @keyword\n\"break\" @keyword\n\"continue\" @keyword\n\"throw\" @keyword\n\"return\" @keyword\n\"exit\" @keyword\n\"trap\" @keyword\n\"try\" @keyword\n\"catch\" @keyword\n\"finally\" @keyword\n\"data\" @keyword\n\"inlinescript\" @keyword\n\"parallel\" @keyword\n\"sequence\" @keyword\n\n\"-as\" @operator\n\"-ccontains\" @operator\n\"-ceq\" @operator\n\"-cge\" @operator\n\"-cgt\" @operator\n\"-cle\" @operator\n\"-clike\" @operator\n\"-clt\" @operator\n\"-cmatch\" @operator\n\"-cne\" @operator\n\"-cnotcontains\" @operator\n\"-cnotlike\" @operator\n\"-cnotmatch\" @operator\n\"-contains\" @operator\n\"-creplace\" @operator\n\"-csplit\" @operator\n\"-eq\" @operator\n\"-ge\" @operator\n\"-gt\" @operator\n\"-icontains\" @operator\n\"-ieq\" @operator\n\"-ige\" @operator\n\"-igt\" @operator\n\"-ile\" @operator\n\"-ilike\" @operator\n\"-ilt\" @operator\n\"-imatch\" @operator\n\"-in\" @operator\n\"-ine\" @operator\n\"-inotcontains\" @operator\n\"-inotlike\" @operator\n\"-inotmatch\" @operator\n\"-ireplace\" @operator\n\"-is\" @operator\n\"-isnot\" @operator\n\"-isplit\" @operator\n\"-join\" @operator\n\"-le\" @operator\n\"-like\" @operator\n\"-lt\" @operator\n\"-match\" @operator\n\"-ne\" @operator\n\"-notcontains\" @operator\n\"-notin\" @operator\n\"-notlike\" @operator\n\"-notmatch\" @operator\n\"-replace\" @operator\n\"-shl\" @operator\n\"-shr\" @operator\n\"-split\" @operator\n\"-and\" @operator\n\"-or\" @operator\n\"-xor\" @operator\n\"-band\" @operator\n\"-bor\" @operator\n\"-bxor\" @operator\n\"+\" @operator\n\"-\" @operator\n\"/\" @operator\n\"\\\\\" @operator\n\"%\" @operator\n\"*\" @operator\n\"..\" @operator\n\"-not\" @operator\n\n\n\";\" @delimiter\n\n(string_literal) @string\n\n(integer_literal) @number\n(real_literal) @number\n\n(command\n  command_name: (command_name) @function)\n\n(function_statement\n  (function_name) @function)\n\n(invokation_expression\n  (member_name) @function)\n\n(member_access\n  (member_name) @property)\n\n(command_invokation_operator) @operator\n\n(type_spec) @type\n\n(variable) @variable\n\n(comment) @comment\n\n(array_expression) @array\n\n(assignment_expression\n  value: (pipeline) @assignvalue)",
	})
}
