//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_fsharp

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/fsharp.bin
var subsetBlobFS_fsharp embed.FS

func init() { registerSubsetEmbeddedBlob("fsharp.bin", subsetBlobFS_fsharp) }
