//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_squirrel

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/squirrel.bin
var subsetBlobFS_squirrel embed.FS

func init() { registerSubsetEmbeddedBlob("squirrel.bin", subsetBlobFS_squirrel) }
