//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_dockerfile

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/dockerfile.bin
var subsetBlobFS_dockerfile embed.FS

func init() { registerSubsetEmbeddedBlob("dockerfile.bin", subsetBlobFS_dockerfile) }
