//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_earthfile

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/earthfile.bin
var subsetBlobFS_earthfile embed.FS

func init() { registerSubsetEmbeddedBlob("earthfile.bin", subsetBlobFS_earthfile) }
