//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_eex

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/eex.bin
var subsetBlobFS_eex embed.FS

func init() { registerSubsetEmbeddedBlob("eex.bin", subsetBlobFS_eex) }
