//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_caddy

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/caddy.bin
var subsetBlobFS_caddy embed.FS

func init() { registerSubsetEmbeddedBlob("caddy.bin", subsetBlobFS_caddy) }
