//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_gitattributes

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/gitattributes.bin
var subsetBlobFS_gitattributes embed.FS

func init() { registerSubsetEmbeddedBlob("gitattributes.bin", subsetBlobFS_gitattributes) }
