//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_nushell

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/nushell.bin
var subsetBlobFS_nushell embed.FS

func init() { registerSubsetEmbeddedBlob("nushell.bin", subsetBlobFS_nushell) }
