//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_pem

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/pem.bin
var subsetBlobFS_pem embed.FS

func init() { registerSubsetEmbeddedBlob("pem.bin", subsetBlobFS_pem) }
