//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_beancount

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/beancount.bin
var subsetBlobFS_beancount embed.FS

func init() { registerSubsetEmbeddedBlob("beancount.bin", subsetBlobFS_beancount) }
