//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_typescript

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/typescript.bin
var subsetBlobFS_typescript embed.FS

func init() { registerSubsetEmbeddedBlob("typescript.bin", subsetBlobFS_typescript) }
