//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_eds

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/eds.bin
var subsetBlobFS_eds embed.FS

func init() { registerSubsetEmbeddedBlob("eds.bin", subsetBlobFS_eds) }
