//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_jsonnet

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/jsonnet.bin
var subsetBlobFS_jsonnet embed.FS

func init() { registerSubsetEmbeddedBlob("jsonnet.bin", subsetBlobFS_jsonnet) }
