//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_brightscript

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/brightscript.bin
var subsetBlobFS_brightscript embed.FS

func init() { registerSubsetEmbeddedBlob("brightscript.bin", subsetBlobFS_brightscript) }
