//go:build grammar_subset && grammar_subset_matlab

package grammars

func init() {
	Register(LangEntry{
		Name:           "matlab",
		Extensions:     []string{".m", ".mat"},
		Language:       MatlabLanguage,
		GrammarSource:  GrammarSourceTS2GoBlob,
		HighlightQuery: "; Constants\n\n(events (identifier) @constant)\n(attribute (identifier) @constant)\n\n\"~\" @constant.builtin\n\n; Fields/Properties\n\n(superclass \".\" (identifier) @variable.other.member)\n(property_name \".\" (identifier) @variable.other.member)\n(property name: (identifier) @variable.other.member)\n\n; Types\n\n(class_definition name: (identifier) @keyword.storage.type)\n(attributes (identifier) @constant)\n(enum . (identifier) @type.enum.variant)\n\n; Functions\n\n(function_definition\n  \"function\" @keyword.function\n  name: (identifier) @function\n  [ \"end\" \"endfunction\" ]? @keyword.function)\n\n(function_signature name: (identifier) @function)\n(function_call name: (identifier) @function)\n(handle_operator (identifier) @function)\n(validation_functions (identifier) @function)\n(command (command_name) @function.macro)\n(command_argument) @string\n(return_statement) @keyword.control.return\n\n; Assignments\n\n(assignment left: (_) @variable)\n(multioutput_variable (_) @variable)\n\n; Parameters\n\n(function_arguments (identifier) @variable.parameter)\n\n; Conditionals\n\n(if_statement [ \"if\" \"end\" ] @keyword.control.conditional)\n(elseif_clause \"elseif\" @keyword.control.conditional)\n(else_clause \"else\" @keyword.control.conditional)\n(switch_statement [ \"switch\" \"end\" ] @keyword.control.conditional)\n(case_clause \"case\" @keyword.control.conditional)\n(otherwise_clause \"otherwise\" @keyword.control.conditional)\n(break_statement) @keyword.control.conditional\n\n; Repeats\n\n(for_statement [ \"for\" \"parfor\" \"end\" ] @keyword.control.repeat)\n(while_statement [ \"while\" \"end\" ] @keyword.control.repeat)\n(continue_statement) @keyword.control.repeat\n\n; Exceptions\n\n(try_statement [ \"try\" \"end\" ] @keyword.control.exception)\n(catch_clause \"catch\" @keyword.control.exception)\n\n; Punctuation\n\n[ \";\" \",\" \".\" ] @punctuation.delimiter\n[ \"(\" \")\" \"[\" \"]\" \"{\" \"}\" ] @punctuation.bracket\n\n; Literals\n\n(escape_sequence) @constant.character.escape\n(formatting_sequence) @constant.character.escape\n(string) @string\n(number) @constant.numeric.float\n(unary_operator [\"+\" \"-\"] @constant.numeric.float)\n\n; Comments\n\n[ (comment) (line_continuation) ] @comment.line\n\n; Operators\n\n[\n  \"+\"\n  \".+\"\n  \"-\"\n  \".*\"\n  \"*\"\n  \".*\"\n  \"/\"\n  \"./\"\n  \"\\\\\"\n  \".\\\\\"\n  \"^\"\n  \".^\"\n  \"'\"\n  \".'\"\n  \"|\"\n  \"&\"\n  \"?\"\n  \"@\"\n  \"<\"\n  \"<=\"\n  \">\"\n  \">=\"\n  \"==\"\n  \"~=\"\n  \"=\"\n  \"&&\"\n  \"||\"\n  \":\"\n] @operator\n\n; Keywords\n\n\"classdef\" @keyword.storage.type\n[\n  \"arguments\"\n  \"end\"\n  \"enumeration\"\n  \"events\"\n  \"global\"\n  \"methods\"\n  \"persistent\"\n  \"properties\"\n] @keyword\n",
	})
}
