//go:build grammar_subset && grammar_subset_haxe

package grammars

func init() {
	Register(LangEntry{
		Name:           "haxe",
		Extensions:     []string{".hx"},
		Language:       HaxeLanguage,
		GrammarSource:  GrammarSourceTS2GoBlob,
		HighlightQuery: "(identifier) @variable\n(comment) @comment\n\n; Preprocessor Statement\n; --------\n(preprocessor_statement) @tag\n; (metadata name: (identifier) @type) @tag\n\n; MetaData\n; --------\n(metadata) @tag\n(metadata name: (identifier) @type) @tag\n\n; Generic/Type Params\n; --------------\n(type_params\n  \"<\" @punctuation.bracket\n  \">\" @punctuation.bracket\n)\n\n; Declarations\n; ------------\n\n(class_declaration name: (identifier) @type.definition)\n(interface_declaration name: (identifier) @type.definition)\n(typedef_declaration name: (identifier) @type.definition)\n\n(function_declaration name: (identifier) @function)\n(function_arg name: (identifier) @variable.parameter)\n\n; Expressions\n; -----------\n; (call_expression name: (identifier) @variable.parameter)\n\n; TODO: Figure out how to determined when \"nested member call\" is last ident.\n; apparently this is a known issue https://github.com/tree-sitter/tree-sitter/issues/880\n(call_expression object: [\n  (_) @function\n  (_ (identifier) @function .)\n;   (_(_ (identifier) @function .))\n;   (_(_(_ (identifier) @function .)))\n;   (_(_(_(_ (identifier) @function .))))\n;   (_(_(_(_(_ (identifier) @function .)))))\n])\n\n; Literals\n; --------\n; [(keyword) (null)] @keyword\n; (type) @type\n(type_name) @type\n(package_name) @module\n(type (identifier) !built_in) @type\n(type built_in: (identifier)) @type.builtin\n[(integer) (float)] @number\n(string) @string\n(bool) @boolean\n(operator) @operator\n(escape_sequence) @punctuation\n(null) @constant.builtin\n(access_identifiers \"null\" @keyword)\n\n; Keywords\n; --------\n[\n  \"abstract\"\n  \"as\"\n  \"break\"\n  \"case\"\n  \"cast\"\n  \"catch\"\n  \"class\"\n  \"continue\"\n  \"default\"\n  \"do\"\n  \"dynamic\"\n  \"else\"\n  \"enum\"\n  \"extends\"\n  \"extern\"\n  \"final\"\n  \"for\"\n  \"function\"\n  \"if\"\n  \"implements\"\n  \"import\"\n  \"in\"\n  \"inline\"\n  \"interface\"\n  \"macro\"\n  \"operator\"\n  \"overload\"\n  \"override\"\n  \"package\"\n  \"private\"\n  \"public\"\n  \"return\"\n  \"static\"\n  \"switch\"\n  \"this\"\n  \"throw\"\n  \"try\"\n  \"typedef\"\n  \"untyped\"\n  \"using\"\n  \"var\"\n  \"while\"\n] @keyword\n\n(function_declaration name: \"new\" @constructor)\n(call_expression\n  \"new\" @keyword\n  constructor: (type_name) @constructor\n)\n\n; Tokens\n; ------\n\n(\":\") @punctuation.special\n(pair [\":\" \"=>\"] @punctuation.special)\n\n[\n  \"(\"\n  \")\"\n  \"[\"\n  \"]\"\n  \"{\"\n  \"}\"\n]  @punctuation.bracket\n;\n[\n;   \";\"\n;   \"?.\"\n;   \".\"\n  \",\"\n] @punctuation.delimiter\n\n\n; Interpolation\n; -------------\n(interpolation \"$\" @punctuation.special)\n(interpolation\n  \"${\" @punctuation.special\n  \"}\" @punctuation.special\n) @embedded\n\n",
	})
}
