//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_gn

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/gn.bin
var subsetBlobFS_gn embed.FS

func init() { registerSubsetEmbeddedBlob("gn.bin", subsetBlobFS_gn) }
