//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_haskell

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/haskell.bin
var subsetBlobFS_haskell embed.FS

func init() { registerSubsetEmbeddedBlob("haskell.bin", subsetBlobFS_haskell) }
