//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_prolog

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/prolog.bin
var subsetBlobFS_prolog embed.FS

func init() { registerSubsetEmbeddedBlob("prolog.bin", subsetBlobFS_prolog) }
