//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_cuda

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/cuda.bin
var subsetBlobFS_cuda embed.FS

func init() { registerSubsetEmbeddedBlob("cuda.bin", subsetBlobFS_cuda) }
