//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_d

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/d.bin
var subsetBlobFS_d embed.FS

func init() { registerSubsetEmbeddedBlob("d.bin", subsetBlobFS_d) }
