//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_ron

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/ron.bin
var subsetBlobFS_ron embed.FS

func init() { registerSubsetEmbeddedBlob("ron.bin", subsetBlobFS_ron) }
