//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_v

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/v.bin
var subsetBlobFS_v embed.FS

func init() { registerSubsetEmbeddedBlob("v.bin", subsetBlobFS_v) }
