//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_scala

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/scala.bin
var subsetBlobFS_scala embed.FS

func init() { registerSubsetEmbeddedBlob("scala.bin", subsetBlobFS_scala) }
