//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_elixir

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/elixir.bin
var subsetBlobFS_elixir embed.FS

func init() { registerSubsetEmbeddedBlob("elixir.bin", subsetBlobFS_elixir) }
