//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_templ

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/templ.bin
var subsetBlobFS_templ embed.FS

func init() { registerSubsetEmbeddedBlob("templ.bin", subsetBlobFS_templ) }
