//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_html

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/html.bin
var subsetBlobFS_html embed.FS

func init() { registerSubsetEmbeddedBlob("html.bin", subsetBlobFS_html) }
