//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_fish

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/fish.bin
var subsetBlobFS_fish embed.FS

func init() { registerSubsetEmbeddedBlob("fish.bin", subsetBlobFS_fish) }
