//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_promql

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/promql.bin
var subsetBlobFS_promql embed.FS

func init() { registerSubsetEmbeddedBlob("promql.bin", subsetBlobFS_promql) }
