//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_vue

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/vue.bin
var subsetBlobFS_vue embed.FS

func init() { registerSubsetEmbeddedBlob("vue.bin", subsetBlobFS_vue) }
