//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_go

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/go.bin
var subsetBlobFS_go embed.FS

func init() { registerSubsetEmbeddedBlob("go.bin", subsetBlobFS_go) }
