//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_java

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/java.bin
var subsetBlobFS_java embed.FS

func init() { registerSubsetEmbeddedBlob("java.bin", subsetBlobFS_java) }
