//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_djot

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/djot.bin
var subsetBlobFS_djot embed.FS

func init() { registerSubsetEmbeddedBlob("djot.bin", subsetBlobFS_djot) }
