//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_git_config

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/git_config.bin
var subsetBlobFS_git_config embed.FS

func init() { registerSubsetEmbeddedBlob("git_config.bin", subsetBlobFS_git_config) }
