//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_awk

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/awk.bin
var subsetBlobFS_awk embed.FS

func init() { registerSubsetEmbeddedBlob("awk.bin", subsetBlobFS_awk) }
