//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_circom

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/circom.bin
var subsetBlobFS_circom embed.FS

func init() { registerSubsetEmbeddedBlob("circom.bin", subsetBlobFS_circom) }
