//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_pkl

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/pkl.bin
var subsetBlobFS_pkl embed.FS

func init() { registerSubsetEmbeddedBlob("pkl.bin", subsetBlobFS_pkl) }
