//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_verilog

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/verilog.bin
var subsetBlobFS_verilog embed.FS

func init() { registerSubsetEmbeddedBlob("verilog.bin", subsetBlobFS_verilog) }
