//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_crystal

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/crystal.bin
var subsetBlobFS_crystal embed.FS

func init() { registerSubsetEmbeddedBlob("crystal.bin", subsetBlobFS_crystal) }
