//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_c_sharp

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/c_sharp.bin
var subsetBlobFS_c_sharp embed.FS

func init() { registerSubsetEmbeddedBlob("c_sharp.bin", subsetBlobFS_c_sharp) }
