//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_json5

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/json5.bin
var subsetBlobFS_json5 embed.FS

func init() { registerSubsetEmbeddedBlob("json5.bin", subsetBlobFS_json5) }
