//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_fortran

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/fortran.bin
var subsetBlobFS_fortran embed.FS

func init() { registerSubsetEmbeddedBlob("fortran.bin", subsetBlobFS_fortran) }
