//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_markdown_inline

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/markdown_inline.bin
var subsetBlobFS_markdown_inline embed.FS

func init() { registerSubsetEmbeddedBlob("markdown_inline.bin", subsetBlobFS_markdown_inline) }
