//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_ada

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/ada.bin
var subsetBlobFS_ada embed.FS

func init() { registerSubsetEmbeddedBlob("ada.bin", subsetBlobFS_ada) }
