//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_yuck

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/yuck.bin
var subsetBlobFS_yuck embed.FS

func init() { registerSubsetEmbeddedBlob("yuck.bin", subsetBlobFS_yuck) }
