//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_make

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/make.bin
var subsetBlobFS_make embed.FS

func init() { registerSubsetEmbeddedBlob("make.bin", subsetBlobFS_make) }
