//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_tcl

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/tcl.bin
var subsetBlobFS_tcl embed.FS

func init() { registerSubsetEmbeddedBlob("tcl.bin", subsetBlobFS_tcl) }
