//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_firrtl

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/firrtl.bin
var subsetBlobFS_firrtl embed.FS

func init() { registerSubsetEmbeddedBlob("firrtl.bin", subsetBlobFS_firrtl) }
