//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_less

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/less.bin
var subsetBlobFS_less embed.FS

func init() { registerSubsetEmbeddedBlob("less.bin", subsetBlobFS_less) }
