//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_org

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/org.bin
var subsetBlobFS_org embed.FS

func init() { registerSubsetEmbeddedBlob("org.bin", subsetBlobFS_org) }
