//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_dart

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/dart.bin
var subsetBlobFS_dart embed.FS

func init() { registerSubsetEmbeddedBlob("dart.bin", subsetBlobFS_dart) }
