//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_hurl

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/hurl.bin
var subsetBlobFS_hurl embed.FS

func init() { registerSubsetEmbeddedBlob("hurl.bin", subsetBlobFS_hurl) }
