//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_dtd

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/dtd.bin
var subsetBlobFS_dtd embed.FS

func init() { registerSubsetEmbeddedBlob("dtd.bin", subsetBlobFS_dtd) }
