//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_desktop

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/desktop.bin
var subsetBlobFS_desktop embed.FS

func init() { registerSubsetEmbeddedBlob("desktop.bin", subsetBlobFS_desktop) }
