//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_nix

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/nix.bin
var subsetBlobFS_nix embed.FS

func init() { registerSubsetEmbeddedBlob("nix.bin", subsetBlobFS_nix) }
