//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_regex

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/regex.bin
var subsetBlobFS_regex embed.FS

func init() { registerSubsetEmbeddedBlob("regex.bin", subsetBlobFS_regex) }
