//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_fidl

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/fidl.bin
var subsetBlobFS_fidl embed.FS

func init() { registerSubsetEmbeddedBlob("fidl.bin", subsetBlobFS_fidl) }
