//go:build grammar_subset && grammar_subset_hurl

package grammars

func init() {
	Register(LangEntry{
		Name:           "hurl",
		Extensions:     []string{".hurl"},
		Language:       HurlLanguage,
		GrammarSource:  GrammarSourceTS2GoBlob,
		HighlightQuery: "; highlights.scm\n\n\"[Query]\" @property\n\"[QueryStringParams]\" @property\n\"[Form]\" @property\n\"[FormParams]\" @property\n\"[Multipart]\" @property\n\"[MultipartFormData]\" @property\n\"[Cookies]\" @property\n\"[Captures]\" @property\n\"[Asserts]\" @property\n\"[Options]\" @property\n\"[BasicAuth]\" @property\n\n(comment) @comment @spell\n\n(key_string) @property\n(json_key_string) @property\n\n(value_string) @string\n(quoted_string) @string\n(json_string) @string\n(file_value) @string.special\n(regex) @string.regex\n\n\"\\\\\" @string.escape\n(regex_escaped_char) @string.escape\n(quoted_string_escaped_char) @string.escape\n(key_string_escaped_char) @string.escape\n(value_string_escaped_char) @string.escape\n(oneline_string_escaped_char) @string.escape\n(multiline_string_escaped_char) @string.escape\n(filename_escaped_char) @string.escape\n(json_string_escaped_char) @string.escape\n\n(method) @type.builtin\n(multiline_string_type) @type\n\n\"status\" @function.builtin\n\"url\" @function.builtin\n\"header\" @function.builtin\n\"cookie\" @function.builtin\n\"body\" @function.builtin\n\"xpath\" @function.builtin\n\"jsonpath\" @function.builtin\n\"regex\" @function.builtin\n\"variable\" @function.builtin\n\"duration\" @function.builtin\n\"sha256\" @function.builtin\n\"md5\" @function.builtin\n\"bytes\" @function.builtin\n\"daysAfterNow\" @function.builtin\n\"daysBeforeNow\" @function.builtin\n\"htmlEscape\" @function.builtin\n\"htmlUnescape\" @function.builtin\n\"decode\" @function.builtin\n\"format\" @function.builtin\n\"nth\" @function.builtin\n\"replace\" @function.builtin\n\"split\" @function.builtin\n\"toDate\" @function.builtin\n\"toInt\" @function.builtin\n\"urlEncode\" @function.builtin\n\"urlDecode\" @function.builtin\n\"count\" @function.builtin\n\n(filter _) @attribute\n\n(version) @string.special\n\n\"null\" @constant.builtin\n(option (_ key: _ @constant.builtin) )\n\n(boolean) @boolean\n\n(variable_name) @variable\n\n\"==\" @operator\n\"!=\" @operator\n\">\" @operator\n\">=\" @operator\n\"<\" @operator\n\"<=\" @operator\n(_ predicate_name: _ @keyword.operator)\n\n\n(integer) @number\n(float) @float\n(status) @number\n(json_number) @float\n\n\":\" @punctuation.delimiter\n\",\" @punctuation.delimiter\n\n\"[\" @punctuation.bracket\n\"]\" @punctuation.bracket\n\"{\" @punctuation.bracket\n\"}\" @punctuation.bracket\n\"{{\" @punctuation.special\n\"}}\" @punctuation.special\n\n\"base64,\" @string.special\n\"file,\" @string.special\n\"hex,\" @string.special\n",
	})
}
