//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_janet

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/janet.bin
var subsetBlobFS_janet embed.FS

func init() { registerSubsetEmbeddedBlob("janet.bin", subsetBlobFS_janet) }
