//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_hyprlang

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/hyprlang.bin
var subsetBlobFS_hyprlang embed.FS

func init() { registerSubsetEmbeddedBlob("hyprlang.bin", subsetBlobFS_hyprlang) }
