//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_tmux

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/tmux.bin
var subsetBlobFS_tmux embed.FS

func init() { registerSubsetEmbeddedBlob("tmux.bin", subsetBlobFS_tmux) }
