//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_thrift

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/thrift.bin
var subsetBlobFS_thrift embed.FS

func init() { registerSubsetEmbeddedBlob("thrift.bin", subsetBlobFS_thrift) }
