//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_scss

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/scss.bin
var subsetBlobFS_scss embed.FS

func init() { registerSubsetEmbeddedBlob("scss.bin", subsetBlobFS_scss) }
