//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_svelte

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/svelte.bin
var subsetBlobFS_svelte embed.FS

func init() { registerSubsetEmbeddedBlob("svelte.bin", subsetBlobFS_svelte) }
