//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_haxe

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/haxe.bin
var subsetBlobFS_haxe embed.FS

func init() { registerSubsetEmbeddedBlob("haxe.bin", subsetBlobFS_haxe) }
