//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_json

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/json.bin
var subsetBlobFS_json embed.FS

func init() { registerSubsetEmbeddedBlob("json.bin", subsetBlobFS_json) }
