//go:build grammar_subset && !grammar_blobs_external && !grammar_set_core && grammar_subset_gomod

// Code generated by cmd/gen_subset_blob_embeds; DO NOT EDIT.

package grammars

import "embed"

//go:embed grammar_blobs/gomod.bin
var subsetBlobFS_gomod embed.FS

func init() { registerSubsetEmbeddedBlob("gomod.bin", subsetBlobFS_gomod) }
