//go:build !grammar_subset || grammar_subset_angular

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/dlvandenberg/tree-sitter-angular f0d0685701b70883fa2dfe94ee7dc27965cab841 src/parser.c

package grammarruntime

// angularExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var angularExternalLexStates = [][]bool{
	/*  0 */ {false, false, false, false, false, false, false, false, false, false, false, false},
	/*  1 */ {true, true, true, true, true, false, true, true, true, true, true, true},
	/*  2 */ {false, false, false, false, false, false, false, false, true, true, false, true},
	/*  3 */ {false, false, false, false, false, false, false, false, true, false, false, false},
	/*  4 */ {false, false, false, false, false, false, false, false, true, false, true, false},
	/*  5 */ {false, false, false, false, false, false, true, false, true, true, false, true},
	/*  6 */ {false, false, false, false, false, true, false, false, true, false, false, false},
	/*  7 */ {false, false, false, false, false, false, false, false, true, false, false, true},
	/*  8 */ {false, false, false, false, false, false, false, true, true, false, false, false},
	/*  9 */ {true, true, true, false, false, false, false, false, true, false, false, false},
	/* 10 */ {false, false, false, true, true, false, false, false, true, false, false, false},
	/* 11 */ {false, false, false, false, true, false, false, false, true, false, false, false},
	/* 12 */ {false, false, false, true, false, false, false, false, true, false, false, false},
}

func init() {
	RegisterExternalLexStates("angular", angularExternalLexStates)
}
