//go:build !grammar_subset || grammar_subset_arduino

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/ObserverOfTime/tree-sitter-arduino 53eb391da4c6c5857f8defa2c583c46c2594f565 src/parser.c

package grammarruntime

// arduinoExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var arduinoExternalLexStates = [][]bool{
	/* 0 */ {false, false},
	/* 1 */ {true, true},
	/* 2 */ {true, false},
	/* 3 */ {false, true},
}

func init() {
	RegisterExternalLexStates("arduino", arduinoExternalLexStates)
}
