//go:build !grammar_subset || grammar_subset_astro

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/virchau13/tree-sitter-astro 213f6e6973d9b456c6e50e86f19f66877e7ef0ee src/parser.c

package grammarruntime

// astroExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var astroExternalLexStates = [][]bool{
	/*  0 */ {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
	/*  1 */ {true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
	/*  2 */ {false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false},
	/*  3 */ {false, false, false, false, false, false, true, false, true, true, false, false, false, false, false, false},
	/*  4 */ {false, false, false, false, false, false, false, false, true, true, true, false, false, false, true, false},
	/*  5 */ {false, false, false, false, false, true, false, false, true, false, false, false, false, false, false, false},
	/*  6 */ {false, false, false, false, false, false, false, false, true, false, false, false, false, true, false, false},
	/*  7 */ {true, true, true, false, false, false, false, false, true, false, false, false, false, false, false, true},
	/*  8 */ {false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
	/*  9 */ {false, false, false, true, true, false, false, false, true, false, false, false, false, false, false, true},
	/* 10 */ {false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false},
	/* 11 */ {false, false, false, true, false, false, false, false, true, false, false, false, false, false, false, true},
	/* 12 */ {false, false, false, false, false, false, false, false, true, false, false, true, false, false, false, false},
	/* 13 */ {false, false, false, false, true, false, false, false, true, false, false, false, false, false, false, false},
	/* 14 */ {false, false, false, false, false, false, false, false, true, false, false, false, true, false, false, false},
}

func init() {
	RegisterExternalLexStates("astro", astroExternalLexStates)
}
