//go:build !grammar_subset || grammar_subset_awk

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/Beaglefoot/tree-sitter-awk 34bbdc7cce8e803096f47b625979e34c1be38127 src/parser.c

package grammarruntime

// awkExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var awkExternalLexStates = [][]bool{
	/* 0 */ {false, false, false, false},
	/* 1 */ {true, true, true, true},
	/* 2 */ {false, true, false, false},
	/* 3 */ {true, true, false, true},
	/* 4 */ {true, true, false, false},
	/* 5 */ {true, false, false, false},
	/* 6 */ {true, false, false, true},
	/* 7 */ {false, false, false, true},
	/* 8 */ {false, false, true, false},
}

func init() {
	RegisterExternalLexStates("awk", awkExternalLexStates)
}
