//go:build !grammar_subset || grammar_subset_beancount

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/polarmutex/tree-sitter-beancount d7a03a7506fbbbc4b16a9a2054ff7c2b337744b8 src/parser.c

package grammarruntime

// beancountExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var beancountExternalLexStates = [][]bool{
	/* 0 */ {false, false, false},
	/* 1 */ {true, true, true},
	/* 2 */ {true, false, false},
	/* 3 */ {true, true, false},
}

func init() {
	RegisterExternalLexStates("beancount", beancountExternalLexStates)
}
