//go:build !grammar_subset || grammar_subset_bicep

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/amaanq/tree-sitter-bicep bff59884307c0ab009bd5e81afd9324b46a6c0f9 src/parser.c

package grammarruntime

// bicepExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var bicepExternalLexStates = [][]bool{
	/* 0 */ {false, false},
	/* 1 */ {true, true},
	/* 2 */ {true, false},
	/* 3 */ {false, true},
}

func init() {
	RegisterExternalLexStates("bicep", bicepExternalLexStates)
}
