//go:build !grammar_subset || grammar_subset_bitbake

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/amaanq/tree-sitter-bitbake a5d04fdb5a69a02b8fa8eb5525a60dfb5309b73b src/parser.c

package grammarruntime

// bitbakeExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var bitbakeExternalLexStates = [][]bool{
	/*  0 */ {false, false, false, false, false, false, false, false, false, false, false, false, false},
	/*  1 */ {true, true, true, true, true, true, true, true, true, true, true, true, true},
	/*  2 */ {false, false, false, false, false, false, false, false, true, false, false, false, false},
	/*  3 */ {false, false, false, true, true, false, false, false, true, false, false, false, false},
	/*  4 */ {false, true, true, false, true, false, false, false, true, false, false, false, false},
	/*  5 */ {false, true, false, false, true, false, false, false, true, false, false, false, false},
	/*  6 */ {false, false, false, false, true, false, false, false, true, false, false, false, false},
	/*  7 */ {false, false, false, false, true, false, false, false, true, false, false, true, false},
	/*  8 */ {false, false, false, false, true, false, false, false, true, false, true, false, false},
	/*  9 */ {false, false, false, false, true, false, false, false, true, true, false, false, false},
	/* 10 */ {false, true, false, false, false, false, false, false, true, false, false, false, false},
	/* 11 */ {false, false, false, false, false, false, false, false, true, false, false, true, false},
	/* 12 */ {false, false, false, false, false, false, false, false, true, true, false, false, false},
	/* 13 */ {false, false, false, false, false, false, false, false, true, false, true, false, false},
	/* 14 */ {true, false, false, false, false, false, false, false, true, false, false, false, false},
	/* 15 */ {false, false, false, false, false, true, true, true, true, false, false, false, false},
	/* 16 */ {false, false, false, false, false, false, false, false, true, false, false, true, true},
}

func init() {
	RegisterExternalLexStates("bitbake", bitbakeExternalLexStates)
}
