//go:build !grammar_subset || grammar_subset_blade

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/EmranMR/tree-sitter-blade 42b3c5a06bc29fbd2c2cbd52b96113365fbed646 src/parser.c

package grammarruntime

// bladeExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var bladeExternalLexStates = [][]bool{
	/*  0 */ {false, false, false, false, false, false, false, false, false},
	/*  1 */ {true, true, true, true, true, true, true, true, true},
	/*  2 */ {false, false, false, false, false, false, false, false, true},
	/*  3 */ {false, false, false, false, false, false, true, false, true},
	/*  4 */ {false, false, false, false, false, true, false, false, true},
	/*  5 */ {true, true, true, false, false, false, false, false, true},
	/*  6 */ {false, false, false, false, false, false, false, true, true},
	/*  7 */ {false, false, false, true, true, false, false, false, true},
	/*  8 */ {false, false, false, true, false, false, false, false, true},
	/*  9 */ {false, false, false, false, true, false, false, false, true},
	/* 10 */ {true, false, false, false, false, false, false, false, true},
}

func init() {
	RegisterExternalLexStates("blade", bladeExternalLexStates)
}
