//go:build !grammar_subset || grammar_subset_caddy

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/opa-oz/tree-sitter-caddy 9b3fde99d3d74345b85b655a6d8065e004fbe26f src/parser.c

package grammarruntime

// caddyExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var caddyExternalLexStates = [][]bool{
	/* 0 */ {false, false, false},
	/* 1 */ {true, true, true},
	/* 2 */ {true, false, false},
}

func init() {
	RegisterExternalLexStates("caddy", caddyExternalLexStates)
}
