//go:build !grammar_subset || grammar_subset_cairo

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/amaanq/tree-sitter-cairo 6238f609bea233040fe927858156dee5515a0745 src/parser.c

package grammarruntime

// cairoExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var cairoExternalLexStates = [][]bool{
	/* 0 */ {false, false, false},
	/* 1 */ {false, true, true},
	/* 2 */ {true, false, false},
	/* 3 */ {false, true, false},
}

func init() {
	RegisterExternalLexStates("cairo", cairoExternalLexStates)
}
