//go:build !grammar_subset || grammar_subset_cmake

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/uyha/tree-sitter-cmake c7b2a71e7f8ecb167fad4c97227c838439280175 src/parser.c

package grammarruntime

// cmakeExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var cmakeExternalLexStates = [][]bool{
	/* 0 */ {false, false, false, false, false, false, false},
	/* 1 */ {true, true, true, true, true, true, true},
	/* 2 */ {false, false, false, true, false, false, true},
	/* 3 */ {true, false, false, true, false, false, true},
	/* 4 */ {true, false, false, false, false, false, false},
	/* 5 */ {false, false, false, false, false, true, false},
	/* 6 */ {false, false, false, false, true, false, false},
	/* 7 */ {false, false, true, false, false, false, false},
	/* 8 */ {false, true, false, false, false, false, false},
}

func init() {
	RegisterExternalLexStates("cmake", cmakeExternalLexStates)
}
