//go:build !grammar_subset || grammar_subset_cooklang

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/addcninblue/tree-sitter-cooklang 4ebe237c1cf64cf3826fc249e9ec0988fe07e58e src/parser.c

package grammarruntime

// cooklangExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var cooklangExternalLexStates = [][]bool{
	/* 0 */ {false},
	/* 1 */ {true},
}

func init() {
	RegisterExternalLexStates("cooklang", cooklangExternalLexStates)
}
