//go:build !grammar_subset || grammar_subset_cpp

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/tree-sitter/tree-sitter-cpp 8b5b49eb196bec7040441bee33b2c9a4838d6967 src/parser.c

package grammarruntime

// cppExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var cppExternalLexStates = [][]bool{
	/* 0 */ {false, false},
	/* 1 */ {true, true},
	/* 2 */ {true, false},
	/* 3 */ {false, true},
}

func init() {
	RegisterExternalLexStates("cpp", cppExternalLexStates)
}
