//go:build !grammar_subset || grammar_subset_css

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/tree-sitter/tree-sitter-css dda5cfc5722c429eaba1c910ca32c2c0c5bb1a3f src/parser.c

package grammarruntime

// cssExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var cssExternalLexStates = [][]bool{
	/* 0 */ {false, false, false},
	/* 1 */ {true, true, true},
	/* 2 */ {false, true, false},
	/* 3 */ {true, true, false},
}

func init() {
	RegisterExternalLexStates("css", cssExternalLexStates)
}
