//go:build !grammar_subset || grammar_subset_cuda

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/theHamsta/tree-sitter-cuda 48b066f334f4cf2174e05a50218ce2ed98b6fd01 src/parser.c

package grammarruntime

// cudaExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var cudaExternalLexStates = [][]bool{
	/* 0 */ {false, false},
	/* 1 */ {true, true},
	/* 2 */ {true, false},
	/* 3 */ {false, true},
}

func init() {
	RegisterExternalLexStates("cuda", cudaExternalLexStates)
}
