//go:build !grammar_subset || grammar_subset_cue

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/eonpatapon/tree-sitter-cue be0f609c73cc2929811a9bce0ed90ca71ea87604 src/parser.c

package grammarruntime

// cueExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var cueExternalLexStates = [][]bool{
	/* 0 */ {false, false, false, false, false, false},
	/* 1 */ {true, true, true, true, true, true},
	/* 2 */ {false, true, false, false, false, false},
	/* 3 */ {false, false, false, true, false, false},
	/* 4 */ {false, false, false, false, false, true},
	/* 5 */ {true, false, false, false, false, false},
	/* 6 */ {false, false, true, false, false, false},
	/* 7 */ {false, false, false, false, true, false},
}

func init() {
	RegisterExternalLexStates("cue", cueExternalLexStates)
}
