//go:build !grammar_subset || grammar_subset_d

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/gdamore/tree-sitter-d fb028c8f14f4188286c2eef143f105def6fbf24f src/parser.c

package grammarruntime

// dExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var dExternalLexStates = [][]bool{
	/* 0 */ {false, false, false, false, false, false, false, false},
	/* 1 */ {true, true, true, true, true, true, true, true},
	/* 2 */ {true, false, false, false, false, false, false, false},
	/* 3 */ {true, true, true, true, false, false, false, false},
	/* 4 */ {true, true, true, true, true, true, false, false},
	/* 5 */ {true, false, false, false, true, true, false, false},
	/* 6 */ {true, true, false, false, false, false, false, false},
	/* 7 */ {true, false, false, false, false, false, true, false},
}

func init() {
	RegisterExternalLexStates("d", dExternalLexStates)
}
