//go:build !grammar_subset || grammar_subset_dart

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/UserNobody14/tree-sitter-dart 0fc19c3a57b1109802af41d2b8f60d8835c5da3a src/parser.c

package grammarruntime

// dartExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var dartExternalLexStates = [][]bool{
	/*  0 */ {false, false, false, false, false, false, false},
	/*  1 */ {true, true, true, true, true, true, true},
	/*  2 */ {false, false, false, false, false, true, true},
	/*  3 */ {false, true, false, false, false, true, true},
	/*  4 */ {true, false, false, false, false, true, true},
	/*  5 */ {false, true, false, false, true, true, true},
	/*  6 */ {false, false, true, false, false, true, true},
	/*  7 */ {false, false, false, true, false, true, true},
	/*  8 */ {true, false, false, false, true, true, true},
	/*  9 */ {false, false, false, true, true, true, true},
	/* 10 */ {false, false, true, false, true, true, true},
}

func init() {
	RegisterExternalLexStates("dart", dartExternalLexStates)
}
