//go:build !grammar_subset || grammar_subset_dockerfile

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/camdencheek/tree-sitter-dockerfile 971acdd908568b4531b0ba28a445bf0bb720aba5 src/parser.c

package grammarruntime

// dockerfileExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var dockerfileExternalLexStates = [][]bool{
	/* 0 */ {false, false, false, false, false},
	/* 1 */ {true, true, true, true, true},
	/* 2 */ {true, false, false, false, false},
	/* 3 */ {true, false, false, true, false},
	/* 4 */ {false, false, false, true, false},
	/* 5 */ {false, true, true, false, false},
}

func init() {
	RegisterExternalLexStates("dockerfile", dockerfileExternalLexStates)
}
