//go:build !grammar_subset || grammar_subset_dtd

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/tree-sitter-grammars/tree-sitter-xml 5000ae8f22d11fbe93939b05c1e37cf21117162d dtd/src/parser.c

package grammarruntime

// dtdExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var dtdExternalLexStates = [][]bool{
	/* 0 */ {false, false, false},
	/* 1 */ {true, true, true},
	/* 2 */ {false, false, true},
	/* 3 */ {true, false, false},
	/* 4 */ {false, true, false},
}

func init() {
	RegisterExternalLexStates("dtd", dtdExternalLexStates)
}
