//go:build !grammar_subset || grammar_subset_earthfile

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/glehmann/tree-sitter-earthfile 5baef88717ad0156fd29a8b12d0d8245bb1096a8 src/parser.c

package grammarruntime

// earthfileExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var earthfileExternalLexStates = [][]bool{
	/* 0 */ {false, false},
	/* 1 */ {true, true},
	/* 2 */ {false, true},
	/* 3 */ {true, false},
}

func init() {
	RegisterExternalLexStates("earthfile", earthfileExternalLexStates)
}
