//go:build !grammar_subset || grammar_subset_editorconfig

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/ValdezFOmar/tree-sitter-editorconfig 63f104dab268a25237f773323c172a4a380a00e1 src/parser.c

package grammarruntime

// editorconfigExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var editorconfigExternalLexStates = [][]bool{
	/* 0 */ {false, false},
	/* 1 */ {true, true},
	/* 2 */ {false, true},
	/* 3 */ {true, false},
}

func init() {
	RegisterExternalLexStates("editorconfig", editorconfigExternalLexStates)
}
