//go:build !grammar_subset || grammar_subset_elm

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: tree-sitter-elm 6d9511c28181db66daee4e883f811f6251220943 src/parser.c

package grammarruntime

// elmExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
// Rows are external lex state IDs; columns are Elm external token indices.
var elmExternalLexStates = [][]bool{
	/*  0 */ {false, false, false, false, false, false, false},
	/*  1 */ {true, true, true, true, true, true, true},
	/*  2 */ {false, false, false, true, false, false, false},
	/*  3 */ {true, false, true, true, false, false, false},
	/*  4 */ {true, false, false, true, false, false, false},
	/*  5 */ {true, false, false, false, false, false, false},
	/*  6 */ {true, false, true, false, false, false, false},
	/*  7 */ {false, false, false, false, false, false, true},
	/*  8 */ {false, false, true, false, false, false, false},
	/*  9 */ {false, false, false, false, true, false, false},
	/* 10 */ {false, true, false, false, false, false, false},
	/* 11 */ {false, false, false, false, false, true, false},
}
