//go:build !grammar_subset || grammar_subset_erlang

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/WhatsApp/tree-sitter-erlang 1d78195c4fbb1fc027eb3e4220427f1eb8bfc89e src/parser.c

package grammarruntime

// erlangExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var erlangExternalLexStates = [][]bool{
	/* 0 */ {false, false, false},
	/* 1 */ {true, true, true},
	/* 2 */ {true, true, false},
}

func init() {
	RegisterExternalLexStates("erlang", erlangExternalLexStates)
}
