//go:build !grammar_subset || grammar_subset_fennel

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/alexmozaidze/tree-sitter-fennel 3f0f6b24d599e92460b969aabc4f4c5a914d15a0 src/parser.c

package grammarruntime

// fennelExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var fennelExternalLexStates = [][]bool{
	/* 0 */ {false, false, false, false, false, false, false, false, false},
	/* 1 */ {true, true, true, true, true, true, true, true, true},
	/* 2 */ {true, true, true, true, false, false, false, true, false},
	/* 3 */ {true, true, true, true, false, false, false, false, false},
	/* 4 */ {true, true, true, true, false, true, false, false, false},
	/* 5 */ {true, true, true, true, false, false, true, false, false},
	/* 6 */ {false, false, false, false, false, true, false, false, false},
	/* 7 */ {false, false, false, false, false, false, true, false, false},
}

func init() {
	RegisterExternalLexStates("fennel", fennelExternalLexStates)
}
