//go:build !grammar_subset || grammar_subset_firrtl

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/amaanq/tree-sitter-firrtl 8503d3a0fe0f9e427863cb0055699ff2d29ae5f5 src/parser.c

package grammarruntime

// firrtlExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var firrtlExternalLexStates = [][]bool{
	/* 0 */ {false, false, false},
	/* 1 */ {true, true, true},
	/* 2 */ {false, false, true},
	/* 3 */ {false, true, true},
	/* 4 */ {false, true, false},
	/* 5 */ {true, false, false},
}

func init() {
	RegisterExternalLexStates("firrtl", firrtlExternalLexStates)
}
