//go:build !grammar_subset || grammar_subset_foam

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/FoamScience/tree-sitter-foam 472c24f11a547820327fb1be565bcfff98ea96a4 src/parser.c

package grammarruntime

// foamExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var foamExternalLexStates = [][]bool{
	/* 0 */ {false, false, false},
	/* 1 */ {true, true, true},
	/* 2 */ {true, false, true},
	/* 3 */ {true, true, false},
	/* 4 */ {true, false, false},
}

func init() {
	RegisterExternalLexStates("foam", foamExternalLexStates)
}
