//go:build !grammar_subset || grammar_subset_fortran

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/stadelmanma/tree-sitter-fortran 2880b7aab4fb7cc618de1ef3d4c6d93b2396c031 src/parser.c

package grammarruntime

// fortranExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var fortranExternalLexStates = [][]bool{
	/*  0 */ {false, false, false, false, false, false, false, false, false, false, false, false},
	/*  1 */ {true, true, true, true, true, true, true, true, true, true, true, true},
	/*  2 */ {true, true, true, true, true, true, false, false, false, false, false, false},
	/*  3 */ {true, true, true, true, true, true, false, false, false, false, true, true},
	/*  4 */ {true, true, true, true, true, true, true, false, false, false, false, false},
	/*  5 */ {true, false, false, false, false, false, false, false, false, false, false, false},
	/*  6 */ {true, false, false, false, false, false, true, false, false, true, false, false},
	/*  7 */ {true, false, false, false, false, false, true, false, false, false, false, false},
	/*  8 */ {true, true, true, true, true, true, false, true, false, false, false, false},
	/*  9 */ {true, true, true, true, false, false, false, false, false, false, false, false},
	/* 10 */ {true, true, false, false, true, true, false, false, false, false, false, false},
	/* 11 */ {true, true, false, false, false, false, false, false, false, false, false, false},
	/* 12 */ {true, true, false, false, true, true, false, false, true, false, false, false},
	/* 13 */ {true, true, false, false, true, true, true, false, false, false, false, false},
	/* 14 */ {true, false, false, false, true, false, false, false, false, false, false, false},
}

func init() {
	RegisterExternalLexStates("fortran", fortranExternalLexStates)
}
