//go:build !grammar_subset || grammar_subset_gdscript

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/PrestonKnopp/tree-sitter-gdscript 89e66b6bdc002ab976283f277cbb48b780c5d0e9 src/parser.c

package grammarruntime

// gdscriptExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var gdscriptExternalLexStates = [][]bool{
	/*  0 */ {false, false, false, false, false, false, false, false, false, false, false, false, false},
	/*  1 */ {true, true, true, true, true, true, true, true, true, true, true, true, true},
	/*  2 */ {false, false, false, true, false, false, true, true, false, false, false, false, false},
	/*  3 */ {false, false, true, true, false, false, true, true, false, false, false, false, true},
	/*  4 */ {true, true, false, true, false, false, true, true, false, false, false, false, true},
	/*  5 */ {true, false, false, true, false, false, true, true, false, false, false, false, true},
	/*  6 */ {true, false, false, false, false, false, false, false, false, false, false, false, true},
	/*  7 */ {false, false, true, true, false, false, true, true, false, false, false, false, false},
	/*  8 */ {false, false, false, true, false, false, true, true, true, false, false, false, false},
	/*  9 */ {false, false, false, true, false, false, true, true, false, false, true, false, false},
	/* 10 */ {false, true, false, true, false, false, true, true, false, false, false, false, false},
	/* 11 */ {false, false, false, true, false, false, true, true, false, true, false, false, false},
	/* 12 */ {true, true, false, false, false, false, false, false, false, false, false, false, true},
	/* 13 */ {false, false, true, false, false, false, false, false, false, false, false, false, true},
	/* 14 */ {false, false, false, false, false, false, false, false, false, false, true, true, false},
	/* 15 */ {false, false, false, false, false, false, false, false, false, true, false, true, false},
	/* 16 */ {false, false, false, false, false, false, false, false, true, false, false, true, false},
	/* 17 */ {false, false, false, false, false, false, false, false, false, false, false, true, false},
	/* 18 */ {false, false, false, false, false, false, false, false, false, true, false, false, false},
	/* 19 */ {true, false, false, true, false, false, true, true, false, false, false, false, false},
	/* 20 */ {true, false, false, false, false, false, false, false, false, false, false, true, true},
	/* 21 */ {false, true, false, false, false, false, false, false, false, false, false, false, false},
	/* 22 */ {false, false, false, false, false, false, false, false, false, false, true, false, false},
	/* 23 */ {false, false, false, false, true, true, false, false, false, false, false, false, false},
	/* 24 */ {false, false, false, true, false, false, false, false, false, false, false, false, false},
	/* 25 */ {false, false, true, false, false, false, false, false, false, false, false, false, false},
	/* 26 */ {false, false, true, false, false, false, false, false, false, false, false, true, false},
	/* 27 */ {false, false, false, false, false, false, false, false, true, false, false, false, false},
}

func init() {
	RegisterExternalLexStates("gdscript", gdscriptExternalLexStates)
}
