//go:build !grammar_subset || grammar_subset_gitcommit

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/gbprod/tree-sitter-gitcommit a716678c0f00645fed1e6f1d0eb221481dbd6f6d src/parser.c

package grammarruntime

// gitcommitExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var gitcommitExternalLexStates = [][]bool{
	/* 0 */ {false, false},
	/* 1 */ {true, true},
	/* 2 */ {true, false},
}

func init() {
	RegisterExternalLexStates("gitcommit", gitcommitExternalLexStates)
}
