//go:build !grammar_subset || grammar_subset_gleam

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/gleam-lang/tree-sitter-gleam 6ea757f7eb8d391dbf24dbb9461990757946dd5e src/parser.c

package grammarruntime

// gleamExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var gleamExternalLexStates = [][]bool{
	/* 0 */ {false, false},
	/* 1 */ {true, true},
	/* 2 */ {true, false},
	/* 3 */ {false, true},
}

func init() {
	RegisterExternalLexStates("gleam", gleamExternalLexStates)
}
