//go:build !grammar_subset || grammar_subset_gn

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/tree-sitter-grammars/tree-sitter-gn bc06955bc1e3c9ff8e9b2b2a55b38b94da923c05 src/parser.c

package grammarruntime

// gnExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var gnExternalLexStates = [][]bool{
	/* 0 */ {false},
	/* 1 */ {true},
}

func init() {
	RegisterExternalLexStates("gn", gnExternalLexStates)
}
