//go:build !grammar_subset || grammar_subset_hack

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/slackhq/tree-sitter-hack 1a7ded90288189746c54861ac144ede97df95081 src/parser.c

package grammarruntime

// hackExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var hackExternalLexStates = [][]bool{
	/* 0 */ {false, false, false, false, false, false},
	/* 1 */ {true, true, true, true, true, true},
	/* 2 */ {false, true, true, true, true, true},
	/* 3 */ {false, false, true, true, true, true},
	/* 4 */ {false, false, false, false, true, false},
	/* 5 */ {true, false, false, false, false, false},
}

func init() {
	RegisterExternalLexStates("hack", hackExternalLexStates)
}
