//go:build !grammar_subset || grammar_subset_haxe

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/vantreeseba/tree-sitter-haxe f2a2394d9ca7a6099f78d8b0d178530e7c9a8e26 src/parser.c

package grammarruntime

// haxeExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var haxeExternalLexStates = [][]bool{
	/* 0 */ {false, false, false},
	/* 1 */ {true, true, true},
	/* 2 */ {false, false, true},
	/* 3 */ {false, true, true},
	/* 4 */ {true, false, true},
}

func init() {
	RegisterExternalLexStates("haxe", haxeExternalLexStates)
}
