//go:build !grammar_subset || grammar_subset_hlsl

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/tree-sitter-grammars/tree-sitter-hlsl bab9111922d53d43668fabb61869bec51bbcb915 src/parser.c

package grammarruntime

// hlslExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var hlslExternalLexStates = [][]bool{
	/* 0 */ {false, false},
	/* 1 */ {true, true},
	/* 2 */ {true, false},
	/* 3 */ {false, true},
}

func init() {
	RegisterExternalLexStates("hlsl", hlslExternalLexStates)
}
