//go:build !grammar_subset || grammar_subset_html

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/tree-sitter/tree-sitter-html 73a3947324f6efddf9e17c0ea58d454843590cc0 src/parser.c

package grammarruntime

// htmlExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var htmlExternalLexStates = [][]bool{
	/* 0 */ {false, false, false, false, false, false, false, false, false},
	/* 1 */ {true, true, true, true, true, true, true, true, true},
	/* 2 */ {false, false, false, false, false, false, false, false, true},
	/* 3 */ {false, false, false, false, false, false, true, false, true},
	/* 4 */ {false, false, false, false, false, true, false, false, true},
	/* 5 */ {false, false, false, false, false, false, false, true, true},
	/* 6 */ {true, true, true, false, false, false, false, false, true},
	/* 7 */ {false, false, false, true, true, false, false, false, true},
	/* 8 */ {false, false, false, false, true, false, false, false, true},
	/* 9 */ {false, false, false, true, false, false, false, false, true},
}

func init() {
	RegisterExternalLexStates("html", htmlExternalLexStates)
}
