//go:build !grammar_subset || grammar_subset_janet

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/sogaiu/tree-sitter-janet-simple d183186995204314700be3e9e0a48053ea16b350 src/parser.c

package grammarruntime

// janetExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var janetExternalLexStates = [][]bool{
	/* 0 */ {false, false},
	/* 1 */ {true, true},
}

func init() {
	RegisterExternalLexStates("janet", janetExternalLexStates)
}
