//go:build !grammar_subset || grammar_subset_javascript

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/tree-sitter/tree-sitter-javascript 58404d8cf191d69f2674a8fd507bd5776f46cb11 src/parser.c

package grammarruntime

import "github.com/wotjr1649/go-treesitter/internal/runtime"

// javascriptReservedWords mirrors C tree-sitter ts_reserved_words (ABI 15),
// flattened with stride 35.
var javascriptReservedWords = []gotreesitter.Symbol{
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	3, 5, 10, 12, 13, 15, 19, 20, 21, 22, 26, 27, 28, 29, 30, 31, 32, 33, 34, 36, 37, 38, 54, 55, 57, 60, 97, 100, 101, 102, 118, 119, 120, 121, 122,
	5, 12, 13, 15, 19, 20, 21, 22, 27, 28, 29, 30, 31, 32, 33, 34, 36, 37, 38, 55, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	19, 26, 37, 38, 55, 97, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	5, 19, 26, 36, 37, 38, 55, 97, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	37, 38, 55, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	5, 12, 19, 20, 21, 22, 26, 27, 28, 29, 30, 31, 32, 33, 34, 36, 37, 38, 55, 97, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	5, 12, 13, 15, 19, 20, 21, 22, 26, 27, 28, 29, 30, 31, 32, 33, 34, 36, 37, 38, 55, 97, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	5, 10, 12, 13, 15, 19, 20, 21, 22, 27, 28, 29, 30, 31, 32, 33, 34, 36, 37, 38, 54, 55, 60, 100, 101, 102, 118, 119, 120, 121, 122, 0, 0, 0, 0,
	3, 5, 10, 12, 13, 15, 19, 20, 21, 22, 27, 28, 29, 30, 31, 32, 33, 34, 36, 37, 38, 54, 55, 57, 60, 100, 101, 102, 118, 119, 120, 121, 122, 0, 0,
	26, 55, 97, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	26, 37, 55, 97, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	26, 37, 38, 55, 97, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	3, 5, 10, 12, 13, 15, 19, 20, 21, 22, 26, 27, 28, 29, 30, 31, 32, 33, 34, 36, 37, 38, 54, 57, 60, 97, 100, 101, 102, 118, 119, 120, 121, 122, 0,
}

// javascriptReservedWordsSymbolNames records, for every symbol ID javascriptReservedWords
// references, that symbol's C ts_symbol_names display name at generation
// time.
var javascriptReservedWordsSymbolNames = map[gotreesitter.Symbol]string{
	3:   "export",
	5:   "default",
	10:  "import",
	12:  "with",
	13:  "var",
	15:  "const",
	19:  "else",
	20:  "if",
	21:  "switch",
	22:  "for",
	26:  "in",
	27:  "while",
	28:  "do",
	29:  "try",
	30:  "break",
	31:  "continue",
	32:  "debugger",
	33:  "return",
	34:  "throw",
	36:  "case",
	37:  "catch",
	38:  "finally",
	54:  "class",
	55:  "extends",
	57:  "function",
	60:  "new",
	97:  "instanceof",
	100: "typeof",
	101: "void",
	102: "delete",
	118: "this",
	119: "super",
	120: "true",
	121: "false",
	122: "null",
}

func init() {
	RegisterReservedWords("javascript", ReservedWordTable{
		MaxSetSize:  35,
		Words:       javascriptReservedWords,
		SymbolCount: 265,
		SymbolNames: javascriptReservedWordsSymbolNames,
	})
}
