//go:build !grammar_subset || grammar_subset_jsdoc

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/tree-sitter/tree-sitter-jsdoc 658d18dcdddb75c760363faa4963427a7c6b52db src/parser.c

package grammarruntime

// jsdocExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var jsdocExternalLexStates = [][]bool{
	/* 0 */ {false, false},
	/* 1 */ {true, false},
	/* 2 */ {false, true},
}

func init() {
	RegisterExternalLexStates("jsdoc", jsdocExternalLexStates)
}
