//go:build !grammar_subset || grammar_subset_jsonnet

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: parser.c

package grammarruntime

// jsonnetExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var jsonnetExternalLexStates = [][]bool{
	/* 0 */ {false, false, false},
	/* 1 */ {true, true, true},
	/* 2 */ {true, false, false},
	/* 3 */ {false, false, true},
	/* 4 */ {false, true, false},
}

func init() {
	RegisterExternalLexStates("jsonnet", jsonnetExternalLexStates)
}
