//go:build !grammar_subset || grammar_subset_julia

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/tree-sitter/tree-sitter-julia e0f9dcd180fdcfcfa8d79a3531e11d99e79321d3 src/parser.c

package grammarruntime

// juliaExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var juliaExternalLexStates = [][]bool{
	/*  0 */ {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
	/*  1 */ {true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
	/*  2 */ {false, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false},
	/*  3 */ {false, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false},
	/*  4 */ {false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
	/*  5 */ {false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false},
	/*  6 */ {false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, true},
	/*  7 */ {false, false, false, false, false, false, false, false, true, false, false, false, false, false, true, false},
	/*  8 */ {false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, true},
	/*  9 */ {false, false, false, false, false, false, true, false, false, false, false, false, false, false, true, false},
	/* 10 */ {false, false, false, false, false, false, false, true, false, false, false, false, false, false, true, false},
	/* 11 */ {false, false, false, false, false, false, false, false, false, true, false, false, false, false, true, false},
	/* 12 */ {false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, true},
	/* 13 */ {false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, true},
	/* 14 */ {true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
}

func init() {
	RegisterExternalLexStates("julia", juliaExternalLexStates)
}
