//go:build !grammar_subset || grammar_subset_just

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/IndianBoy42/tree-sitter-just 60df3d5b3fda2a22fdb3621226cafab50b763663 src/parser.c

package grammarruntime

// justExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var justExternalLexStates = [][]bool{
	/* 0 */ {false, false, false, false, false},
	/* 1 */ {true, true, true, true, true},
	/* 2 */ {false, true, true, true, false},
	/* 3 */ {true, false, false, false, false},
	/* 4 */ {false, false, true, false, false},
	/* 5 */ {false, false, true, true, false},
	/* 6 */ {false, false, false, true, false},
}

func init() {
	RegisterExternalLexStates("just", justExternalLexStates)
}
