//go:build !grammar_subset || grammar_subset_kconfig

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/amaanq/tree-sitter-kconfig 9ac99fe4c0c27a35dc6f757cef534c646e944881 src/parser.c

package grammarruntime

// kconfigExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var kconfigExternalLexStates = [][]bool{
	/* 0 */ {false},
	/* 1 */ {true},
}

func init() {
	RegisterExternalLexStates("kconfig", kconfigExternalLexStates)
}
