//go:build !grammar_subset || grammar_subset_kdl

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/tree-sitter-grammars/tree-sitter-kdl b37e3d58e5c5cf8d739b315d6114e02d42e66664 src/parser.c

package grammarruntime

// kdlExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var kdlExternalLexStates = [][]bool{
	/* 0 */ {false, false, false},
	/* 1 */ {true, true, true},
	/* 2 */ {false, true, true},
	/* 3 */ {true, true, false},
	/* 4 */ {false, true, false},
}

func init() {
	RegisterExternalLexStates("kdl", kdlExternalLexStates)
}
