//go:build !grammar_subset || grammar_subset_kotlin

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/fwcd/tree-sitter-kotlin cbed96ab13dbc082eeeb2e8333c342a62829c29d src/parser.c

package grammarruntime

// kotlinExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var kotlinExternalLexStates = [][]bool{
	/*  0 */ {false, false, false, false, false, false, false, false, false},
	/*  1 */ {true, true, true, true, true, true, true, true, true},
	/*  2 */ {false, false, false, true, true, false, false, false, false},
	/*  3 */ {false, false, true, true, true, false, false, false, false},
	/*  4 */ {true, false, true, true, true, false, false, false, false},
	/*  5 */ {true, false, false, true, true, false, false, false, false},
	/*  6 */ {true, false, true, true, true, false, false, true, false},
	/*  7 */ {false, false, true, true, false, false, false, false, false},
	/*  8 */ {true, false, true, true, false, false, false, false, false},
	/*  9 */ {false, false, true, true, false, false, false, true, false},
	/* 10 */ {true, false, true, true, false, false, false, true, false},
	/* 11 */ {true, false, false, true, true, false, false, true, false},
	/* 12 */ {false, false, false, true, false, false, false, false, false},
	/* 13 */ {true, false, false, true, false, false, false, false, false},
	/* 14 */ {true, false, false, true, false, false, false, true, false},
	/* 15 */ {false, false, false, true, false, false, false, true, false},
	/* 16 */ {false, false, false, true, false, true, true, false, false},
	/* 17 */ {true, false, false, true, false, false, false, false, true},
	/* 18 */ {false, true, false, true, false, false, false, false, false},
}

func init() {
	RegisterExternalLexStates("kotlin", kotlinExternalLexStates)
}
