//go:build !grammar_subset || grammar_subset_liquid

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/hankthetank27/tree-sitter-liquid fa11c7ba45038b61e03a8a00ad667fb5f3d72088 src/parser.c

package grammarruntime

// liquidExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var liquidExternalLexStates = [][]bool{
	/* 0 */ {false, false, false, false, false, false},
	/* 1 */ {true, true, true, true, true, true},
	/* 2 */ {false, false, false, false, true, false},
	/* 3 */ {true, false, false, false, false, false},
	/* 4 */ {false, false, true, false, false, false},
	/* 5 */ {false, true, false, false, false, false},
	/* 6 */ {false, false, false, true, false, false},
}

func init() {
	RegisterExternalLexStates("liquid", liquidExternalLexStates)
}
