//go:build !grammar_subset || grammar_subset_luau

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/tree-sitter-grammars/tree-sitter-luau a8914d6c1fc5131f8e1c13f769fa704c9f5eb02f src/parser.c

package grammarruntime

// luauExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var luauExternalLexStates = [][]bool{
	/* 0 */ {false, false, false, false, false, false},
	/* 1 */ {true, true, true, true, true, true},
	/* 2 */ {true, false, false, false, false, false},
	/* 3 */ {true, false, false, true, false, false},
	/* 4 */ {true, false, false, false, true, false},
	/* 5 */ {true, false, true, false, false, false},
	/* 6 */ {true, false, false, false, false, true},
	/* 7 */ {true, true, false, false, false, false},
}

func init() {
	RegisterExternalLexStates("luau", luauExternalLexStates)
}
