//go:build !grammar_subset || grammar_subset_matlab

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/acristoffers/tree-sitter-matlab 574dde565caddf8cf44eec7df3cb89eb96053ed7 src/parser.c

package grammarruntime

// matlabExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var matlabExternalLexStates = [][]bool{
	/*  0 */ {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
	/*  1 */ {true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
	/*  2 */ {true, true, true, false, true, false, true, false, false, false, false, false, true, true, false, false, false, false},
	/*  3 */ {true, true, true, false, true, false, true, false, false, false, false, false, true, true, false, true, true, false},
	/*  4 */ {true, true, true, false, true, false, true, false, false, false, false, false, true, true, true, false, false, false},
	/*  5 */ {true, true, false, false, true, false, true, false, false, false, false, false, false, true, false, false, false, false},
	/*  6 */ {true, true, false, false, true, false, true, false, false, false, false, true, false, true, false, false, false, false},
	/*  7 */ {true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false},
	/*  8 */ {true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false},
	/*  9 */ {true, true, false, false, false, false, false, false, false, false, false, true, false, false, false, true, true, false},
	/* 10 */ {true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
	/* 11 */ {true, true, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false},
	/* 12 */ {true, true, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false},
	/* 13 */ {true, true, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
	/* 14 */ {true, true, false, false, false, true, false, false, true, true, true, false, false, false, false, false, false, false},
	/* 15 */ {true, true, false, false, false, false, false, true, true, true, true, false, false, false, false, false, false, false},
}

func init() {
	RegisterExternalLexStates("matlab", matlabExternalLexStates)
}
