//go:build !grammar_subset || grammar_subset_mojo

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/whistlebee/tree-sitter-mojo c307dab71a43add26b4715f14e2d6de2a42e6007 src/parser.c

package grammarruntime

// mojoExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var mojoExternalLexStates = [][]bool{
	/*  0 */ {false, false, false, false, false, false, false, false, false, false, false},
	/*  1 */ {true, true, true, true, true, true, true, true, true, true, true},
	/*  2 */ {false, false, false, true, false, false, false, true, false, false, false},
	/*  3 */ {false, false, true, true, false, false, false, true, false, false, false},
	/*  4 */ {false, false, false, true, false, false, false, true, false, true, false},
	/*  5 */ {false, false, false, true, false, false, false, true, false, false, true},
	/*  6 */ {false, false, false, true, false, false, false, true, true, false, false},
	/*  7 */ {true, false, false, true, false, false, false, true, false, false, false},
	/*  8 */ {true, true, false, true, false, false, false, true, false, false, false},
	/*  9 */ {true, false, false, false, false, false, false, true, false, false, false},
	/* 10 */ {false, false, false, false, false, false, false, true, false, true, false},
	/* 11 */ {false, false, false, false, false, false, false, true, false, false, true},
	/* 12 */ {false, false, false, false, false, false, false, true, false, false, false},
	/* 13 */ {false, false, false, false, false, false, false, true, true, false, false},
	/* 14 */ {false, false, false, false, true, false, true, true, false, false, false},
}

func init() {
	RegisterExternalLexStates("mojo", mojoExternalLexStates)
}
