//go:build !grammar_subset || grammar_subset_move

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/aptos-labs/tree-sitter-move-on-aptos 12906b341de7cef81cf03d7d91dae51d8a9299e7 src/parser.c

package grammarruntime

// moveExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var moveExternalLexStates = [][]bool{
	/* 0 */ {false, false, false, false},
	/* 1 */ {true, true, true, true},
	/* 2 */ {true, true, false, false},
	/* 3 */ {false, true, false, false},
}

func init() {
	RegisterExternalLexStates("move", moveExternalLexStates)
}
