//go:build !grammar_subset || grammar_subset_nickel

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/nickel-lang/tree-sitter-nickel b5b6cc3bc7b9ea19f78fed264190685419cd17a8 src/parser.c

package grammarruntime

// nickelExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var nickelExternalLexStates = [][]bool{
	/*  0 */ {false, false, false, false, false, false, false, false},
	/*  1 */ {true, true, true, true, true, true, true, true},
	/*  2 */ {true, false, true, false, false, false, true, true},
	/*  3 */ {true, false, true, false, false, true, true, true},
	/*  4 */ {false, false, false, false, false, false, false, true},
	/*  5 */ {false, false, false, false, false, true, false, true},
	/*  6 */ {true, false, true, false, false, false, false, true},
	/*  7 */ {false, true, false, false, true, false, false, true},
	/*  8 */ {false, false, false, true, true, false, false, true},
	/*  9 */ {false, false, false, false, false, false, true, true},
	/* 10 */ {false, true, false, false, false, false, false, true},
	/* 11 */ {false, false, false, true, false, false, false, true},
}

func init() {
	RegisterExternalLexStates("nickel", nickelExternalLexStates)
}
