//go:build !grammar_subset || grammar_subset_nushell

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/nushell/tree-sitter-nu bb3f533e5792260291945e1f329e1f0a779def6e src/parser.c

package grammarruntime

// nushellExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var nushellExternalLexStates = [][]bool{
	/* 0 */ {false, false, false},
	/* 1 */ {true, true, true},
	/* 2 */ {true, false, false},
	/* 3 */ {false, false, true},
	/* 4 */ {false, true, false},
}

func init() {
	RegisterExternalLexStates("nushell", nushellExternalLexStates)
}
