//go:build !grammar_subset || grammar_subset_odin

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/tree-sitter-grammars/tree-sitter-odin d2ca8efb4487e156a60d5bd6db2598b872629403 src/parser.c

package grammarruntime

// odinExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var odinExternalLexStates = [][]bool{
	/*  0 */ {false, false, false, false, false, false, false},
	/*  1 */ {true, true, true, true, true, true, true},
	/*  2 */ {false, true, false, true, true, true, true},
	/*  3 */ {true, true, false, true, true, true, true},
	/*  4 */ {true, true, false, false, true, true, false},
	/*  5 */ {true, true, false, false, true, false, false},
	/*  6 */ {false, true, false, false, true, true, false},
	/*  7 */ {false, true, false, false, true, false, false},
	/*  8 */ {true, true, true, false, true, true, false},
	/*  9 */ {true, true, true, false, true, false, false},
	/* 10 */ {false, true, false, false, true, true, true},
	/* 11 */ {false, true, false, false, true, false, true},
}

func init() {
	RegisterExternalLexStates("odin", odinExternalLexStates)
}
