//go:build !grammar_subset || grammar_subset_org

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/emiasims/tree-sitter-org 64cfbc213f5a83da17632c95382a5a0a2f3357c1 src/parser.c

package grammarruntime

// orgExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var orgExternalLexStates = [][]bool{
	/*  0 */ {false, false, false, false, false, false, false},
	/*  1 */ {true, true, true, true, true, true, true},
	/*  2 */ {true, false, false, false, true, false, false},
	/*  3 */ {true, false, false, false, true, true, false},
	/*  4 */ {false, false, false, false, false, false, true},
	/*  5 */ {true, false, false, false, false, false, true},
	/*  6 */ {true, true, true, false, false, false, false},
	/*  7 */ {true, false, true, false, false, false, false},
	/*  8 */ {true, false, false, false, false, false, false},
	/*  9 */ {false, false, false, false, true, true, false},
	/* 10 */ {false, false, false, false, true, false, false},
	/* 11 */ {false, true, true, false, false, false, false},
	/* 12 */ {false, false, false, true, false, false, false},
	/* 13 */ {false, false, true, false, false, false, false},
}

func init() {
	RegisterExternalLexStates("org", orgExternalLexStates)
}
