//go:build !grammar_subset || grammar_subset_php

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/tree-sitter/tree-sitter-php 3f2465c217d0a966d41e584b42d75522f2a3149e php/src/parser.c

package grammarruntime

// phpExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var phpExternalLexStates = [][]bool{
	/*  0 */ {false, false, false, false, false, false, false, false, false, false, false, false},
	/*  1 */ {true, true, true, true, true, true, true, true, true, true, true, true},
	/*  2 */ {true, false, false, false, false, false, false, false, false, false, false, false},
	/*  3 */ {false, false, false, false, false, true, false, false, false, true, false, false},
	/*  4 */ {false, false, false, false, false, true, false, false, false, false, false, false},
	/*  5 */ {false, false, false, true, false, false, false, false, false, false, false, false},
	/*  6 */ {false, true, false, false, false, false, false, false, false, false, false, false},
	/*  7 */ {false, false, false, false, false, true, true, false, false, true, false, false},
	/*  8 */ {false, false, false, true, true, false, false, false, false, false, false, false},
	/*  9 */ {false, true, true, false, false, false, false, false, false, false, false, false},
	/* 10 */ {false, false, false, false, false, false, false, true, false, false, false, false},
	/* 11 */ {false, false, false, false, false, false, false, false, false, true, true, false},
	/* 12 */ {false, false, false, false, false, false, false, false, false, true, false, false},
	/* 13 */ {false, false, false, false, false, false, false, false, true, false, false, false},
	/* 14 */ {false, false, false, false, false, false, false, false, false, false, true, false},
}

func init() {
	RegisterExternalLexStates("php", phpExternalLexStates)
}
