//go:build !grammar_subset || grammar_subset_php

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/tree-sitter/tree-sitter-php 3f2465c217d0a966d41e584b42d75522f2a3149e php/src/parser.c

package grammarruntime

import "github.com/wotjr1649/go-treesitter/internal/runtime"

// phpReservedWords mirrors C tree-sitter ts_reserved_words (ABI 15),
// flattened with stride 74.
var phpReservedWords = []gotreesitter.Symbol{
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	8, 11, 12, 13, 15, 16, 20, 21, 22, 27, 28, 29, 30, 31, 34, 35, 36, 37, 38, 43, 50, 71, 74, 75, 80, 81, 82, 83, 84, 85, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 109, 111, 112, 152, 153, 180, 181, 182, 183, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	11, 13, 14, 20, 21, 22, 27, 32, 35, 43, 71, 74, 75, 80, 81, 82, 83, 84, 85, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 109, 111, 112, 152, 153, 154, 157, 158, 159, 180, 181, 182, 183, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	11, 12, 13, 14, 22, 32, 35, 50, 71, 74, 75, 80, 81, 82, 83, 84, 85, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 109, 111, 112, 152, 153, 154, 157, 158, 159, 180, 181, 182, 183, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	8, 11, 12, 13, 14, 15, 16, 20, 21, 22, 27, 28, 29, 30, 31, 32, 34, 35, 36, 37, 38, 43, 50, 71, 74, 75, 80, 81, 82, 83, 84, 85, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 109, 111, 112, 152, 153, 154, 157, 158, 159, 180, 181, 182, 183, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	8, 11, 12, 13, 14, 15, 16, 20, 21, 22, 27, 28, 29, 30, 31, 32, 34, 35, 36, 37, 38, 43, 46, 50, 51, 53, 54, 57, 58, 61, 64, 65, 67, 69, 71, 74, 75, 80, 81, 82, 83, 84, 85, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 109, 111, 112, 135, 152, 153, 154, 157, 158, 159, 180, 181, 182, 183,
}

// phpReservedWordsSymbolNames records, for every symbol ID phpReservedWords
// references, that symbol's C ts_symbol_names display name at generation
// time.
var phpReservedWordsSymbolNames = map[gotreesitter.Symbol]string{
	8:   "static",
	11:  "global",
	12:  "namespace",
	13:  "use",
	14:  "as",
	15:  "function",
	16:  "const",
	20:  "trait",
	21:  "interface",
	22:  "extends",
	27:  "case",
	28:  "class",
	29:  "final",
	30:  "abstract",
	31:  "readonly",
	32:  "implements",
	34:  "var_modifier",
	35:  "insteadof",
	36:  "public",
	37:  "protected",
	38:  "private",
	43:  "fn",
	46:  "bottom_type",
	50:  "primitive_type_token1",
	51:  "primitive_type_token2",
	53:  "primitive_type_token3",
	54:  "primitive_type_token4",
	57:  "primitive_type_token5",
	58:  "primitive_type_token6",
	61:  "cast_type_token3",
	64:  "cast_type_token6",
	65:  "cast_type_token7",
	67:  "cast_type_token9",
	69:  "cast_type_token11",
	71:  "echo",
	74:  "declare",
	75:  "enddeclare",
	80:  "try",
	81:  "catch",
	82:  "finally",
	83:  "goto",
	84:  "continue",
	85:  "break",
	87:  "return",
	88:  "throw",
	89:  "while",
	90:  "endwhile",
	91:  "do",
	92:  "for",
	93:  "endfor",
	94:  "foreach",
	95:  "endforeach",
	96:  "if",
	97:  "endif",
	98:  "elseif",
	99:  "else",
	100: "match",
	101: "default",
	102: "switch",
	103: "endswitch",
	109: "clone",
	111: "print",
	112: "new",
	135: "_argument_name_token1",
	152: "yield",
	153: "yield from",
	154: "instanceof",
	157: "and",
	158: "or",
	159: "xor",
	180: "include",
	181: "include_once",
	182: "require",
	183: "require_once",
}

func init() {
	RegisterReservedWords("php", ReservedWordTable{
		MaxSetSize:  74,
		Words:       phpReservedWords,
		SymbolCount: 434,
		SymbolNames: phpReservedWordsSymbolNames,
	})
}
