//go:build !grammar_subset || grammar_subset_pkl

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/apple/tree-sitter-pkl a02fc36f6001a22e7fdf35eaabbadb7b39c74ba5 src/parser.c

package grammarruntime

// pklExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var pklExternalLexStates = [][]bool{
	/*  0 */ {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
	/*  1 */ {true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
	/*  2 */ {false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true},
	/*  3 */ {false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, true},
	/*  4 */ {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false},
	/*  5 */ {true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
	/*  6 */ {false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false},
	/*  7 */ {false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false},
	/*  8 */ {false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false},
	/*  9 */ {false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false},
	/* 10 */ {false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false},
	/* 11 */ {false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false},
	/* 12 */ {false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
	/* 13 */ {false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
	/* 14 */ {false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false},
	/* 15 */ {false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false},
	/* 16 */ {false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false},
	/* 17 */ {false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false},
	/* 18 */ {false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false},
	/* 19 */ {false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false},
}

func init() {
	RegisterExternalLexStates("pkl", pklExternalLexStates)
}
