//go:build !grammar_subset || grammar_subset_powershell

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/airbus-cert/tree-sitter-powershell da65ba3acc93777255781b447f5e7448245df4bf src/parser.c

package grammarruntime

// powershellExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var powershellExternalLexStates = [][]bool{
	/* 0 */ {false},
	/* 1 */ {true},
}

func init() {
	RegisterExternalLexStates("powershell", powershellExternalLexStates)
}
