//go:build !grammar_subset || grammar_subset_pug

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/zealot128/tree-sitter-pug 13e9195370172c86a8b88184cc358b23b677cc46 src/parser.c

package grammarruntime

// pugExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var pugExternalLexStates = [][]bool{
	/* 0 */ {false, false, false},
	/* 1 */ {true, true, true},
	/* 2 */ {true, false, true},
	/* 3 */ {true, false, false},
	/* 4 */ {false, true, true},
	/* 5 */ {false, false, true},
	/* 6 */ {false, true, false},
}

func init() {
	RegisterExternalLexStates("pug", pugExternalLexStates)
}
