//go:build !grammar_subset || grammar_subset_python

// Code generated by cmd/ts2go; DO NOT EDIT.

package grammarruntime

// pythonExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
// Rows are external lex state IDs; columns are Python external token indices.
var pythonExternalLexStates = [][]bool{
	/*  0 */ {false, false, false, false, false, false, false, false, false, false, false, false},
	/*  1 */ {true, true, true, true, true, true, true, true, true, true, true, true},
	/*  2 */ {false, false, false, true, false, false, false, true, false, false, false, false},
	/*  3 */ {false, false, true, true, false, false, false, true, false, false, false, false},
	/*  4 */ {true, false, false, true, false, false, false, true, false, false, false, false},
	/*  5 */ {true, true, false, true, false, false, false, true, false, false, false, false},
	/*  6 */ {false, false, false, true, false, false, false, true, false, false, true, false},
	/*  7 */ {false, false, false, true, false, false, false, true, false, true, false, false},
	/*  8 */ {false, false, false, true, false, false, false, true, true, false, false, false},
	/*  9 */ {true, false, false, false, false, false, false, true, false, false, false, false},
	/* 10 */ {false, false, true, true, false, false, false, true, false, false, false, true},
	/* 11 */ {false, false, false, true, false, false, false, true, false, false, false, true},
	/* 12 */ {false, false, false, false, false, false, false, true, true, false, false, false},
	/* 13 */ {false, false, false, false, false, false, false, true, false, false, true, false},
	/* 14 */ {false, false, false, false, false, false, false, true, false, true, false, false},
	/* 15 */ {false, false, false, false, false, false, false, true, false, false, false, false},
	/* 16 */ {false, false, false, false, true, true, true, true, false, false, false, false},
	/* 17 */ {false, false, true, false, false, false, false, true, false, false, false, false},
	/* 18 */ {true, true, false, false, false, false, false, true, false, false, false, false},
}
