//go:build !grammar_subset || grammar_subset_python

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/tree-sitter/tree-sitter-python 26855eabccb19c6abf499fbc5b8dc7cc9ab8bc64 src/parser.c

package grammarruntime

import "github.com/wotjr1649/go-treesitter/internal/runtime"

// pythonReservedWords mirrors C tree-sitter ts_reserved_words (ABI 15),
// flattened with stride 35.
var pythonReservedWords = []gotreesitter.Symbol{
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	3, 5, 10, 14, 16, 17, 18, 19, 20, 21, 22, 24, 25, 28, 29, 30, 31, 32, 33, 35, 36, 37, 40, 41, 45, 55, 56, 57, 65, 73, 87, 95, 96, 97, 98,
	10, 24, 25, 30, 33, 35, 56, 57, 65, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	10, 22, 24, 25, 29, 30, 31, 32, 33, 35, 36, 37, 45, 56, 57, 65, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	3, 5, 14, 16, 17, 18, 19, 20, 21, 24, 25, 29, 31, 32, 33, 35, 36, 37, 40, 41, 45, 73, 87, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	3, 14, 16, 17, 18, 19, 20, 21, 24, 25, 29, 31, 32, 33, 35, 36, 37, 40, 41, 45, 73, 87, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	3, 5, 14, 16, 17, 18, 19, 20, 21, 24, 25, 31, 32, 33, 35, 36, 37, 40, 41, 45, 73, 87, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	3, 5, 14, 16, 17, 18, 19, 20, 21, 24, 29, 31, 32, 33, 35, 36, 37, 40, 41, 45, 73, 87, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	3, 5, 10, 14, 16, 17, 18, 19, 20, 21, 22, 24, 25, 29, 30, 31, 32, 33, 35, 36, 37, 40, 41, 45, 56, 57, 65, 0, 0, 0, 0, 0, 0, 0, 0,
	3, 5, 10, 14, 16, 17, 18, 19, 20, 21, 22, 24, 25, 29, 30, 31, 32, 33, 35, 36, 37, 40, 41, 45, 56, 57, 65, 87, 0, 0, 0, 0, 0, 0, 0,
	3, 10, 14, 16, 17, 18, 19, 20, 21, 22, 24, 25, 29, 30, 31, 32, 33, 35, 36, 37, 40, 41, 45, 56, 57, 65, 87, 0, 0, 0, 0, 0, 0, 0, 0,
	10, 30, 56, 57, 65, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	10, 24, 25, 30, 33, 56, 57, 65, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	3, 5, 10, 14, 16, 17, 18, 19, 20, 21, 22, 24, 25, 29, 30, 31, 32, 33, 35, 36, 37, 40, 41, 45, 56, 57, 65, 73, 87, 0, 0, 0, 0, 0, 0,
	3, 5, 10, 14, 16, 17, 18, 19, 20, 21, 22, 24, 25, 29, 30, 31, 32, 33, 35, 36, 37, 40, 41, 45, 55, 56, 57, 65, 73, 87, 0, 0, 0, 0, 0,
	3, 5, 10, 14, 16, 17, 18, 19, 20, 21, 22, 24, 25, 28, 29, 30, 31, 32, 33, 35, 36, 37, 40, 41, 45, 55, 56, 57, 65, 73, 87, 95, 0, 0, 0,
}

// pythonReservedWordsSymbolNames records, for every symbol ID pythonReservedWords
// references, that symbol's C ts_symbol_names display name at generation
// time.
var pythonReservedWordsSymbolNames = map[gotreesitter.Symbol]string{
	3:  "import",
	5:  "from",
	10: "as",
	14: "assert",
	16: "return",
	17: "del",
	18: "raise",
	19: "pass",
	20: "break",
	21: "continue",
	22: "if",
	24: "elif",
	25: "else",
	28: "async",
	29: "for",
	30: "in",
	31: "while",
	32: "try",
	33: "except",
	35: "finally",
	36: "with",
	37: "def",
	40: "global",
	41: "nonlocal",
	45: "class",
	55: "not",
	56: "and",
	57: "or",
	65: "is",
	73: "lambda",
	87: "yield",
	95: "await",
	96: "true",
	97: "false",
	98: "none",
}

func init() {
	RegisterReservedWords("python", ReservedWordTable{
		MaxSetSize:  35,
		Words:       pythonReservedWords,
		SymbolCount: 275,
		SymbolNames: pythonReservedWordsSymbolNames,
	})
}
