//go:build !grammar_subset || grammar_subset_r

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/r-lib/tree-sitter-r 0e6ef7741712c09dc3ee6e81c42e919820cc65ef src/parser.c

package grammarruntime

// rExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var rExternalLexStates = [][]bool{
	/*  0 */ {false, false, false, false, false, false, false, false, false, false, false, false, false, false},
	/*  1 */ {true, true, true, true, true, true, true, true, true, true, true, true, true, true},
	/*  2 */ {true, false, false, false, false, false, false, false, false, false, false, false, false, false},
	/*  3 */ {false, true, true, true, true, true, false, true, false, true, false, true, false, false},
	/*  4 */ {false, true, true, true, true, true, false, true, true, true, false, true, false, false},
	/*  5 */ {false, true, true, true, false, true, false, true, false, true, false, true, false, false},
	/*  6 */ {false, true, true, true, false, true, false, true, true, true, false, true, false, false},
	/*  7 */ {false, false, false, true, false, true, true, true, false, false, false, false, false, false},
	/*  8 */ {false, false, false, true, false, true, false, true, false, false, false, false, true, false},
	/*  9 */ {false, false, false, true, false, true, false, true, false, false, true, false, false, false},
	/* 10 */ {false, true, true, true, false, true, false, true, true, false, false, false, false, false},
	/* 11 */ {false, true, true, true, false, true, false, true, false, false, false, false, false, false},
	/* 12 */ {false, true, false, true, false, true, false, true, false, false, false, false, false, false},
	/* 13 */ {false, false, false, true, false, true, false, true, false, false, false, false, false, false},
	/* 14 */ {false, true, false, true, true, true, true, false, false, true, false, true, false, false},
	/* 15 */ {false, true, false, true, true, true, false, false, false, true, true, true, false, false},
	/* 16 */ {false, true, false, true, true, true, false, false, false, true, false, true, true, false},
	/* 17 */ {false, true, false, true, false, true, false, false, false, true, true, true, false, false},
	/* 18 */ {false, true, false, true, false, true, true, false, false, true, false, true, false, false},
	/* 19 */ {false, true, false, true, false, true, false, false, false, true, false, true, true, false},
	/* 20 */ {false, false, false, true, true, true, false, false, false, true, true, true, false, false},
	/* 21 */ {false, false, false, true, true, true, false, false, false, true, false, true, true, false},
	/* 22 */ {false, false, false, true, true, true, true, false, false, true, false, true, false, false},
	/* 23 */ {false, false, false, true, false, true, true, false, false, true, false, true, false, false},
	/* 24 */ {false, false, false, true, false, true, false, false, false, true, false, true, true, false},
	/* 25 */ {false, false, false, true, false, true, false, false, false, true, true, true, false, false},
	/* 26 */ {false, false, false, false, true, true, true, false, false, true, false, true, false, false},
	/* 27 */ {false, false, false, false, true, true, false, false, false, true, false, true, true, false},
	/* 28 */ {false, false, false, false, true, true, false, false, false, true, true, true, false, false},
	/* 29 */ {false, false, false, false, false, true, false, false, false, true, false, true, true, false},
	/* 30 */ {false, false, false, false, false, true, true, false, false, true, false, true, false, false},
	/* 31 */ {false, false, false, false, false, true, false, false, false, true, true, true, false, false},
	/* 32 */ {false, false, false, false, false, false, true, false, false, false, false, false, false, false},
	/* 33 */ {false, true, false, false, false, true, false, false, false, false, false, false, false, false},
	/* 34 */ {false, false, false, false, false, false, false, false, false, false, false, false, true, false},
	/* 35 */ {false, false, false, false, false, false, false, false, false, false, true, false, false, false},
}

func init() {
	RegisterExternalLexStates("r", rExternalLexStates)
}
