//go:build !grammar_subset || grammar_subset_rescript

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/rescript-lang/tree-sitter-rescript 43c2f1f35024918d415dc933d4cc534d6419fedf src/parser.c

package grammarruntime

// rescriptExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var rescriptExternalLexStates = [][]bool{
	/*  0 */ {false, false, false, false, false, false, false, false, false, false, false, false},
	/*  1 */ {true, true, true, true, true, true, true, true, true, true, true, true},
	/*  2 */ {true, true, true, true, false, false, false, false, true, true, true, true},
	/*  3 */ {false, true, false, true, false, false, false, false, true, true, true, true},
	/*  4 */ {false, true, false, false, false, false, false, false, false, false, true, true},
	/*  5 */ {true, true, true, false, false, false, false, false, false, false, true, true},
	/*  6 */ {false, true, false, true, false, false, false, false, false, false, true, true},
	/*  7 */ {false, true, false, false, true, true, false, false, false, false, true, true},
	/*  8 */ {false, true, false, false, false, false, false, false, true, false, true, true},
	/*  9 */ {true, true, false, false, false, false, false, false, false, false, true, true},
	/* 10 */ {false, true, false, false, true, false, false, false, false, false, true, true},
}

func init() {
	RegisterExternalLexStates("rescript", rescriptExternalLexStates)
}
