//go:build !grammar_subset || grammar_subset_ron

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/amaanq/tree-sitter-ron 78938553b93075e638035f624973083451b29055 src/parser.c

package grammarruntime

// ronExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var ronExternalLexStates = [][]bool{
	/* 0 */ {false, false, false, false},
	/* 1 */ {true, true, true, true},
	/* 2 */ {false, false, true, true},
	/* 3 */ {false, false, false, true},
	/* 4 */ {true, false, false, true},
}

func init() {
	RegisterExternalLexStates("ron", ronExternalLexStates)
}
