//go:build !grammar_subset || grammar_subset_ruby

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/tree-sitter/tree-sitter-ruby ad907a69da0c8a4f7a943a7fe012712208da6dee src/parser.c

package grammarruntime

// rubyExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var rubyExternalLexStates = [][]bool{
	/*  0 */ {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
	/*  1 */ {true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
	/*  2 */ {false, false, true, true, true, true, true, true, true, true, false, false, false, false, true, false, false, false, true, true, true, false, false, false, true, true, false, false, false, false},
	/*  3 */ {true, false, true, true, true, true, true, true, true, true, false, false, false, false, true, true, true, true, true, true, true, true, false, true, true, true, true, true, true, false},
	/*  4 */ {false, false, true, true, true, true, true, true, true, true, false, false, false, false, true, true, true, true, true, true, true, true, false, true, true, true, true, true, true, false},
	/*  5 */ {false, false, true, true, true, true, true, true, true, true, false, false, false, false, true, false, true, true, true, true, true, false, false, true, true, true, true, false, false, false},
	/*  6 */ {true, false, true, true, true, true, true, true, true, true, false, false, false, false, true, false, false, false, true, true, true, false, false, false, true, true, false, false, true, false},
	/*  7 */ {true, false, true, true, true, true, true, true, true, true, false, false, false, false, true, false, false, false, true, true, true, false, false, false, true, true, false, false, false, false},
	/*  8 */ {true, false, true, true, true, true, true, true, true, true, false, false, false, false, true, true, false, false, true, true, true, true, false, false, true, true, false, true, true, false},
	/*  9 */ {true, false, true, true, true, true, true, true, true, true, false, false, false, false, true, false, true, true, true, true, true, false, false, true, true, true, true, false, false, false},
	/* 10 */ {false, false, true, true, true, true, true, true, true, true, false, false, false, false, true, false, false, false, true, true, true, false, false, true, true, true, true, false, false, false},
	/* 11 */ {true, false, true, true, true, true, true, true, true, true, false, false, false, false, true, true, false, false, true, true, true, true, false, false, true, true, false, true, false, false},
	/* 12 */ {false, false, true, true, true, true, true, true, true, true, false, false, false, false, true, true, false, false, true, true, true, true, false, false, true, true, false, true, true, false},
	/* 13 */ {false, false, true, true, true, true, true, true, true, true, false, false, false, false, true, true, false, false, true, true, true, true, false, false, true, true, false, true, false, false},
	/* 14 */ {false, true, true, true, true, true, true, true, true, true, false, false, false, false, true, false, false, false, true, true, true, false, false, false, true, true, false, false, false, false},
	/* 15 */ {false, false, true, true, true, true, true, true, true, true, false, false, false, false, true, false, false, true, true, true, true, false, false, false, true, true, false, false, false, false},
	/* 16 */ {true, true, true, true, true, true, true, true, true, true, false, false, false, false, true, false, false, false, true, true, true, false, false, false, true, true, false, false, false, false},
	/* 17 */ {true, false, true, true, true, true, true, true, true, true, false, false, false, false, true, false, false, true, true, true, true, false, false, false, true, true, false, false, false, false},
	/* 18 */ {true, false, true, true, true, true, true, true, true, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, true, false, false, false, false},
	/* 19 */ {false, false, true, true, true, true, true, true, true, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, true, false, false, false, false},
	/* 20 */ {false, false, true, true, true, true, true, true, true, true, false, false, false, false, true, false, false, false, false, true, false, false, true, false, true, true, false, false, false, false},
	/* 21 */ {true, false, true, true, true, true, true, true, true, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false},
	/* 22 */ {false, false, true, true, true, true, true, true, true, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false},
	/* 23 */ {true, false, false, false, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, true, true, false, false, false, false, false, true, true, false},
	/* 24 */ {false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, true, true, false, false, false, false, false, true, true, false},
	/* 25 */ {true, false, false, true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, true, true, false, false, false, false, false, true, true, false},
	/* 26 */ {false, false, true, false, true, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, false, false},
	/* 27 */ {true, false, false, false, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, true, true, false, false, false, false, false, true, false, false},
	/* 28 */ {false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, true, true, false, false, false, false, false, true, true, false},
	/* 29 */ {false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, false, false},
	/* 30 */ {false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, true, true, false, false, false, false, false, true, false, false},
	/* 31 */ {true, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false},
	/* 32 */ {true, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
	/* 33 */ {true, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false},
	/* 34 */ {false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false},
	/* 35 */ {false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
	/* 36 */ {false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false},
	/* 37 */ {false, false, false, false, false, false, false, false, false, true, true, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true},
	/* 38 */ {false, false, false, false, false, false, false, false, false, true, false, true, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true},
	/* 39 */ {false, false, false, true, false, false, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false},
	/* 40 */ {false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true},
	/* 41 */ {false, false, false, false, false, false, false, false, false, true, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
}

func init() {
	RegisterExternalLexStates("ruby", rubyExternalLexStates)
}
