//go:build !grammar_subset || grammar_subset_rust

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/tree-sitter/tree-sitter-rust 77a3747266f4d621d0757825e6b11edcbf991ca5 src/parser.c

package grammarruntime

// rustExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var rustExternalLexStates = [][]bool{
	/* 0 */ {false, false, false, false, false, false, false, false, false, false, false},
	/* 1 */ {true, true, true, true, true, true, true, true, true, true, true},
	/* 2 */ {false, false, true, false, false, true, false, false, false, false, false},
	/* 3 */ {false, false, false, false, false, false, true, true, true, false, false},
	/* 4 */ {true, true, false, false, false, false, false, false, false, false, false},
	/* 5 */ {false, false, false, false, false, false, false, false, true, false, false},
	/* 6 */ {false, false, false, false, false, true, false, false, false, false, false},
	/* 7 */ {false, false, false, false, true, false, false, false, false, false, false},
	/* 8 */ {false, false, false, false, false, false, false, false, false, true, false},
	/* 9 */ {false, false, false, true, false, false, false, false, false, false, false},
}

func init() {
	RegisterExternalLexStates("rust", rustExternalLexStates)
}
