//go:build !grammar_subset || grammar_subset_sql

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/m-novikov/tree-sitter-sql 587f30d184b058450be2a2330878210c5f33b3f9 src/parser.c

package grammarruntime

// sqlExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var sqlExternalLexStates = [][]bool{
	/* 0 */ {false, false, false},
	/* 1 */ {true, true, true},
	/* 2 */ {true, false, false},
	/* 3 */ {false, false, true},
	/* 4 */ {false, true, false},
}

func init() {
	RegisterExternalLexStates("sql", sqlExternalLexStates)
}
