//go:build !grammar_subset || grammar_subset_squirrel

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/amaanq/tree-sitter-squirrel 072c969749e66f000dba35a33c387650e203e96e src/parser.c

package grammarruntime

// squirrelExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var squirrelExternalLexStates = [][]bool{
	/* 0 */ {false},
	/* 1 */ {true},
}

func init() {
	RegisterExternalLexStates("squirrel", squirrelExternalLexStates)
}
