//go:build !grammar_subset || grammar_subset_starlark

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/tree-sitter-grammars/tree-sitter-starlark a453dbf3ba433db0e5ec621a38a7e59d72e4dc69 src/parser.c

package grammarruntime

// starlarkExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var starlarkExternalLexStates = [][]bool{
	/*  0 */ {false, false, false, false, false, false, false, false, false, false, false, false},
	/*  1 */ {true, true, true, true, true, true, true, true, true, true, true, true},
	/*  2 */ {false, false, false, true, false, false, false, true, false, false, false, false},
	/*  3 */ {false, false, true, true, false, false, false, true, false, false, false, false},
	/*  4 */ {true, false, false, true, false, false, false, true, false, false, false, false},
	/*  5 */ {true, true, false, true, false, false, false, true, false, false, false, false},
	/*  6 */ {false, false, false, true, false, false, false, true, false, true, false, false},
	/*  7 */ {false, false, false, true, false, false, false, true, true, false, false, false},
	/*  8 */ {false, false, false, true, false, false, false, true, false, false, true, false},
	/*  9 */ {true, false, false, false, false, false, false, true, false, false, false, false},
	/* 10 */ {false, false, false, false, false, false, false, true, false, false, true, false},
	/* 11 */ {false, false, false, false, false, false, false, true, false, true, false, false},
	/* 12 */ {false, false, false, false, false, false, false, true, true, false, false, false},
	/* 13 */ {false, false, false, false, false, false, false, true, false, false, false, false},
	/* 14 */ {false, false, false, false, true, true, true, true, false, false, false, false},
	/* 15 */ {false, false, true, false, false, false, false, true, false, false, false, false},
	/* 16 */ {true, true, false, false, false, false, false, true, false, false, false, false},
}

func init() {
	RegisterExternalLexStates("starlark", starlarkExternalLexStates)
}
