//go:build !grammar_subset || grammar_subset_svelte

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/tree-sitter-grammars/tree-sitter-svelte ae5199db47757f785e43a14b332118a5474de1a2 src/parser.c

package grammarruntime

// svelteExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var svelteExternalLexStates = [][]bool{
	/*  0 */ {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false},
	/*  1 */ {true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true},
	/*  2 */ {false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, false},
	/*  3 */ {false, false, false, false, false, false, true, false, true, false, false, false, false, false, false, false},
	/*  4 */ {false, false, false, false, false, false, false, false, true, true, false, false, true, true, true, true},
	/*  5 */ {false, false, false, false, false, false, false, false, true, true, false, false, true, true, true, false},
	/*  6 */ {false, false, false, false, false, false, false, false, true, true, false, false, true, true, false, false},
	/*  7 */ {false, false, false, false, false, true, false, false, true, false, false, false, false, false, false, false},
	/*  8 */ {false, false, false, false, false, false, false, false, true, false, false, false, false, false, true, true},
	/*  9 */ {false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false},
	/* 10 */ {true, true, true, false, false, false, false, false, true, false, false, false, false, false, false, false},
	/* 11 */ {false, false, false, false, false, false, false, false, true, false, false, false, false, false, true, false},
	/* 12 */ {false, false, false, false, false, false, false, false, true, true, true, false, false, false, false, false},
	/* 13 */ {false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false},
	/* 14 */ {false, false, false, false, false, false, false, false, true, false, false, false, false, false, false, true},
	/* 15 */ {false, false, false, false, false, false, false, false, true, false, false, true, false, false, false, false},
	/* 16 */ {false, false, false, true, true, false, false, false, true, false, false, false, false, false, false, false},
	/* 17 */ {false, false, false, true, false, false, false, false, true, false, false, false, false, false, false, false},
	/* 18 */ {false, false, false, false, true, false, false, false, true, false, false, false, false, false, false, false},
}

func init() {
	RegisterExternalLexStates("svelte", svelteExternalLexStates)
}
