//go:build !grammar_subset || grammar_subset_tablegen

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/amaanq/tree-sitter-tablegen b1170880c61355aaf38fc06f4af7d3c55abdabc4 src/parser.c

package grammarruntime

// tablegenExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var tablegenExternalLexStates = [][]bool{
	/* 0 */ {false},
	/* 1 */ {true},
}

func init() {
	RegisterExternalLexStates("tablegen", tablegenExternalLexStates)
}
