//go:build !grammar_subset || grammar_subset_tcl

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/tree-sitter-grammars/tree-sitter-tcl 8f11ac7206a54ed11210491cee1e0657e2962c47 src/parser.c

package grammarruntime

// tclExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var tclExternalLexStates = [][]bool{
	/* 0 */ {false, false},
	/* 1 */ {true, true},
	/* 2 */ {true, false},
}

func init() {
	RegisterExternalLexStates("tcl", tclExternalLexStates)
}
