//go:build !grammar_subset || grammar_subset_teal

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/euclidianAce/tree-sitter-teal 05d276e737055e6f77a21335b7573c9d3c091e2f src/parser.c

package grammarruntime

// tealExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var tealExternalLexStates = [][]bool{
	/* 0 */ {false, false, false, false, false, false, false},
	/* 1 */ {true, true, true, true, true, true, true},
	/* 2 */ {true, false, false, false, false, false, false},
	/* 3 */ {true, true, false, false, true, false, false},
	/* 4 */ {true, false, false, false, false, true, true},
	/* 5 */ {true, false, true, true, false, false, false},
	/* 6 */ {true, false, false, false, false, false, true},
	/* 7 */ {true, false, false, true, false, false, false},
}

func init() {
	RegisterExternalLexStates("teal", tealExternalLexStates)
}
