//go:build !grammar_subset || grammar_subset_templ

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/vrischmann/tree-sitter-templ 1c6db04effbcd7773c826bded9783cbc3061bd55 src/parser.c

package grammarruntime

import "github.com/wotjr1649/go-treesitter/internal/runtime"

// templReservedWords mirrors C tree-sitter ts_reserved_words (ABI 15),
// flattened with stride 25.
var templReservedWords = []gotreesitter.Symbol{
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	5, 6, 11, 14, 15, 19, 21, 25, 27, 28, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
	5, 6, 53, 55, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	5, 6, 53, 55, 57, 58, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	5, 6, 11, 14, 19, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 56, 57, 58, 59, 0, 0, 0, 0, 0, 0,
	5, 6, 11, 14, 19, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 0, 0, 0, 0, 0,
	5, 6, 11, 14, 19, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 59, 0, 0, 0, 0, 0, 0, 0,
	5, 6, 11, 14, 15, 19, 21, 25, 27, 28, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 59, 0, 0,
}

// templReservedWordsSymbolNames records, for every symbol ID templReservedWords
// references, that symbol's C ts_symbol_names display name at generation
// time.
var templReservedWordsSymbolNames = map[gotreesitter.Symbol]string{
	5:  "package",
	6:  "import",
	11: "const",
	14: "var",
	15: "func",
	19: "type",
	21: "struct",
	25: "interface",
	27: "map",
	28: "chan",
	45: "fallthrough",
	46: "break",
	47: "continue",
	48: "goto",
	49: "return",
	50: "go",
	51: "defer",
	52: "if",
	53: "else",
	54: "for",
	55: "range",
	56: "switch",
	57: "case",
	58: "default",
	59: "select",
}

func init() {
	RegisterReservedWords("templ", ReservedWordTable{
		MaxSetSize:  25,
		Words:       templReservedWords,
		SymbolCount: 315,
		SymbolNames: templReservedWordsSymbolNames,
	})
}
