//go:build !grammar_subset || grammar_subset_templ

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/vrischmann/tree-sitter-templ 1c6db04effbcd7773c826bded9783cbc3061bd55 src/parser.c

package grammarruntime

// templExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var templExternalLexStates = [][]bool{
	/* 0 */ {false, false, false, false},
	/* 1 */ {true, true, true, true},
	/* 2 */ {false, false, true, false},
	/* 3 */ {false, false, false, true},
	/* 4 */ {true, false, false, false},
	/* 5 */ {false, true, false, false},
}

func init() {
	RegisterExternalLexStates("templ", templExternalLexStates)
}
