//go:build !grammar_subset || grammar_subset_typescript

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/tree-sitter/tree-sitter-typescript 75b3874edb2dc714fb1fd77a32013d0f8699989f typescript/src/parser.c + grammars/patches/tree-sitter-typescript-import-type.patch

package grammarruntime

// typescriptExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var typescriptExternalLexStates = [][]bool{
	/*  0 */ {false, false, false, false, false, false, false, false, false, false},
	/*  1 */ {true, true, true, true, true, true, false, true, true, true},
	/*  2 */ {false, false, false, true, false, false, false, false, false, false},
	/*  3 */ {false, false, true, true, true, false, false, false, false, false},
	/*  4 */ {true, false, true, true, true, false, false, false, false, false},
	/*  5 */ {true, false, false, true, false, false, false, false, false, false},
	/*  6 */ {true, false, false, true, false, false, false, false, true, false},
	/*  7 */ {false, true, false, true, false, true, false, false, false, false},
	/*  8 */ {false, true, false, true, false, false, false, false, false, false},
	/*  9 */ {false, false, false, true, false, true, false, false, false, false},
	/* 10 */ {false, false, false, true, false, false, true, false, false, false},
}

func init() {
	RegisterExternalLexStates("typescript", typescriptExternalLexStates)
}
