//go:build !grammar_subset || grammar_subset_uxntal

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/amaanq/tree-sitter-uxntal ad9b638b914095320de85d59c49ab271603af048 src/parser.c

package grammarruntime

// uxntalExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var uxntalExternalLexStates = [][]bool{
	/* 0 */ {false},
	/* 1 */ {true},
}

func init() {
	RegisterExternalLexStates("uxntal", uxntalExternalLexStates)
}
