//go:build !grammar_subset || grammar_subset_vue

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/tree-sitter-grammars/tree-sitter-vue ce8011a414fdf8091f4e4071752efc376f4afb08 src/parser.c

package grammarruntime

// vueExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var vueExternalLexStates = [][]bool{
	/*  0 */ {false, false, false, false, false, false, false, false, false, false, false, false},
	/*  1 */ {true, true, true, true, true, true, true, true, true, true, true, true},
	/*  2 */ {false, false, false, false, false, false, false, false, true, false, true, false},
	/*  3 */ {false, false, false, false, false, false, true, false, true, false, true, false},
	/*  4 */ {false, false, false, false, false, true, false, false, true, false, false, false},
	/*  5 */ {false, false, false, false, false, false, false, false, true, false, false, false},
	/*  6 */ {true, true, true, false, false, false, false, false, true, true, false, false},
	/*  7 */ {false, false, false, false, false, false, false, true, true, false, false, false},
	/*  8 */ {false, false, false, true, true, false, false, false, true, false, false, false},
	/*  9 */ {false, false, false, false, false, false, false, false, true, false, false, true},
	/* 10 */ {false, false, false, false, true, false, false, false, true, false, false, false},
	/* 11 */ {false, false, false, true, false, false, false, false, true, false, false, false},
}

func init() {
	RegisterExternalLexStates("vue", vueExternalLexStates)
}
