//go:build !grammar_subset || grammar_subset_wgsl

// Code generated by cmd/ts2go; DO NOT EDIT.
// Source: https://github.com/szebniok/tree-sitter-wgsl 40259f3c77ea856841a4e0c4c807705f3e4a2b65 src/parser.c

package grammarruntime

// wgslExternalLexStates mirrors C tree-sitter ts_external_scanner_states.
var wgslExternalLexStates = [][]bool{
	/* 0 */ {false},
	/* 1 */ {true},
}

func init() {
	RegisterExternalLexStates("wgsl", wgslExternalLexStates)
}
