"""Separate the three pinned GPL grammars without changing their artifacts."""
import re

GPL = ('caddy', 'disassembly', 'jq')
SYMBOLS = ('Caddy', 'Disassembly', 'Jq')


def separate(files, module):
    """Return the main carrier and optional adapter payload, from reviewed bytes."""
    main = dict(files)
    optional = {}
    for name, data in files.items():
        if not name.startswith('grammars/'):
            continue
        stem = name.rsplit('/', 1)[-1].split('.')[0]
        if any(stem == lang or stem.startswith(lang + '_') or
               stem.endswith('_' + lang) for lang in GPL):
            del main[name]
            if name.startswith('grammars/grammar_blobs/'):
                optional['grammar_blobs/' + name.rsplit('/', 1)[-1]] = data
            elif name.startswith('grammars/runtime/') and not stem.startswith('support_'):
                data = re.sub(rb'^//go:build[^\n]+\n\n', b'', data)
                data = data.replace(b'package grammarruntime', b'package gtsadapter', 1)
                optional[name.rsplit('/', 1)[-1]] = data

    def remove(path, pattern, count):
        data, actual = re.subn(pattern, b'', main[path], flags=re.M | re.S)
        if actual != count:
            raise ValueError(f'GPL separation inventory drift: {path}: {actual} != {count}')
        main[path] = data

    entries = []
    for name, symbol in zip(GPL, SYMBOLS):
        pattern = (rb'\tRegister\(LangEntry\{\n\t\tName:\s+"' + name.encode() +
                   rb'",\n.*?\n\t\}\)\n')
        matches = re.findall(pattern, main['grammars/registry_builtin_gen.go'], flags=re.S)
        if len(matches) != 1:
            raise ValueError('GPL registry entry drift: ' + name)
        entry = matches[0].replace(b'Register(LangEntry{', b'grammars.Register(grammars.LangEntry{')
        entry = entry.replace(b'GrammarSourceTS2GoBlob', b'grammars.GrammarSourceTS2GoBlob')
        entry = entry.replace(symbol.encode() + b'Language,', b'loader("' + name.encode() + b'"),')
        entries.append(entry)
        remove('grammars/registry_builtin_gen.go', pattern, 1)
        remove('grammars/embedded_grammars_gen.go',
               rb'// ' + symbol.encode() + rb'Language[^\n]*\nfunc ' + symbol.encode() +
               rb'Language\(\) \*gotreesitter.Language \{\n[^}]*\}\n\n', 1)
        if name != 'jq':
            remove('grammars/runtime/builtin_scanners_gen.go',
                   rb'^\tRegister' + symbol.encode() + rb'Support\(\)\n', 1)
            remove('grammars/blob_source_embedded_core.go',
                   rb'^//go:embed grammar_blobs/' + name.encode() + rb'\.bin\n', 1)
    optional['catalog.go'] = ('''// Code generated by tools/runtime-bundle/import.py; DO NOT EDIT.
// The GPL grammar payload is distributed only in this optional module.
package gtsadapter

import (
    "embed"
    gotreesitter "''' + module + '''"
    "''' + module + '''/grammars"
    grammarruntime "''' + module + '''/grammars/runtime"
)

//go:embed grammar_blobs/*.bin
var blobs embed.FS

var RegisterExternalLexStates = grammars.RegisterExternalLexStates

func loader(name string) func() *gotreesitter.Language {
    return func() *gotreesitter.Language { return grammarruntime.Language(name) }
}

func init() {
    for _, name := range []string{"caddy", "disassembly", "jq"} {
        data, err := blobs.ReadFile("grammar_blobs/" + name + ".bin")
        if err != nil { panic(err) }
        grammarruntime.RegisterBlob(name, func() []byte { return data })
    }
    grammars.RegisterExternalScanner("caddy", CaddyExternalScanner{})
    grammars.RegisterExternalScanner("disassembly", DisassemblyExternalScanner{})
''').encode() + b''.join(entries) + b'}\n'
    if len(optional) != 8 or len(files) - len(main) != 19:
        raise ValueError('GPL file inventory drift')
    return main, optional
